// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelVerdict } from "./CancelVerdict";

/**
 * One action (a tool or provider call with a correlation id, spec §3.16).
 */
export type ActionInfo = { correlation_id: string, execution_id: string, session_id: string, tool: string, state: string, retry_class: string, planned_at_ms: number, authorized_at_ms?: number, dispatched_at_ms?: number, settled_at_ms?: number, deadline_at_ms: number, 
/**
 * What the action's budget reservation holds, in US dollars.
 */
reserved_usd: number, confirmed: boolean, cancel?: string, 
/**
 * The cancel's verdict (M4 18a): how it knows the call stopped.
 */
verdict?: CancelVerdict, external_op_id?: string, result_ref?: string, resolution?: string, completions_seen: number, };
