// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionInfo } from "./ActionInfo";

export type ActionListResult = { actions: Array<ActionInfo>, total: number, };
