// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionConfirmResult = { correlation_id: string, approved: boolean, session_id: string, execution_id: string, 
/**
 * The answer woke the execution, so a continuation turn follows. False
 * for a declined budget question: the session keeps waiting, and its
 * next message asks again.
 */
resumes: boolean, };
