// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalChannel } from "./ApprovalChannel";

/**
 * `[approval]` as health reports it (spec §3.9 "Approval"): the trusted
 * users, and each listed channel with its state now.
 */
export type ApprovalStatus = { 
/**
 * The config has an `[approval]` section. Without one, every surface
 * answers as before theseus-sgh: the CLI, the local web UI, and a
 * place's listed Discord users.
 */
configured: boolean, 
/**
 * Surface-qualified ids, as configured (`discord:<user id>`).
 */
trusted_users: Array<string>, channels: Array<ApprovalChannel>, };
