// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of `[approval].channels` and whether it is trusted now.
 */
export type ApprovalChannel = { 
/**
 * As configured: `cli`, `web`, `discord:dm`, or `discord:<channel id>`.
 */
channel: string, 
/**
 * `trusted` | `not_trusted`.
 */
state: string, 
/**
 * Why, in words: what the channel is, or why it does not count.
 */
detail: string, 
/**
 * When Discord last checked who can view it (a guild channel); 0 if never.
 */
checked_at_ms: number, };
