// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The process behind an answer, as the process tree says (theseus-6qy).
 */
export type Asker = { pid?: number, 
/**
 * Its program: the file name of its `argv[0]`, else its `comm`.
 */
argv0?: string, 
/**
 * How long the trace took, in µs.
 */
trace_us: number, 
/**
 * The job whose wrapper is above it.
 */
job?: string, wrapper_pid?: number, 
/**
 * It is under this daemon with no wrapper between: a job's orphan
 * (theseus-z4b). The daemon's pid.
 */
under_daemon?: number, 
/**
 * It is under another serving daemon (theseus-6uo). That daemon's pid.
 */
under_other_daemon?: number, 
/**
 * Why it could not be traced.
 */
untraceable?: string, };
