// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file sent with a turn's input (theseus-9g2): a Discord attachment, or
 * `theseus ask --attach`. Text travels as `text` and an image as base64
 * `data`. A file the sender did not read carries `not_read` instead, with
 * the reason, and the model is told it exists.
 */
export type Attachment = { name: string, 
/**
 * As the sender knows it (`text/plain`, `image/png`); may be empty.
 */
media_type: string, 
/**
 * Bytes of the whole file.
 */
size: number, text?: string, 
/**
 * The file's bytes, base64 (standard alphabet, padded).
 */
data?: string, 
/**
 * Why it was not read: too large, a type that is not read, a failed download.
 */
not_read?: string, };
