// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session's audience, as a compile evaluated it: who sees what its model
 * says. It comes from the session's place (`outbox.target`).
 */
export type Audience = { "kind": "owner" } | { "kind": "people", people: Array<string>, } | { "kind": "place", place: string, 
/**
 * The channel's name, when the binding gave it.
 */
name?: string, 
/**
 * How many can view it, the bot aside. Absent when they cannot be
 * read (the Server Members intent is off, or the binding has not
 * said yet): then the channel counts as public.
 */
viewers?: number, 
/**
 * The first 16 hex digits of the SHA-256 of the viewers' ids,
 * sorted, so a change of who views it with the same count is a
 * change of audience.
 */
digest?: string, };
