// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwsBootstrapStack } from "./AwsBootstrapStack";

/**
 * `aws.bootstrap`'s result: the plan, and whether it was applied.
 */
export type AwsBootstrapResult = { account: string, region: string, stacks: Array<AwsBootstrapStack>, 
/**
 * What the read-only checks found that the operator should know.
 */
warnings: Array<string>, 
/**
 * The plan's digest, which `apply` names.
 */
digest: string, 
/**
 * Some stack is created or changed.
 */
changes: boolean, applied: boolean, 
/**
 * What the operator does next.
 */
next: Array<string>, };
