// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stack of the bootstrap's plan.
 */
export type AwsBootstrapStack = { stack: string, region: string, 
/**
 * `create`, `update`, or `none` (it is as planned).
 */
action: string, 
/**
 * Each resource a create makes, as `LogicalId (AWS::Type)`.
 */
resources: Array<string>, 
/**
 * What an update changes: the template, a parameter, a tag.
 */
changes: Array<string>, parameters: { [key in string]: string }, };
