// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account's monthly budget (`theseus-monthly`), from `DescribeBudget`,
 * which is free, read every six hours after serving. Amounts in cents.
 */
export type AwsBudgetStatus = { limit_cents: number, actual_cents: number, forecast_cents?: number, read_at_unix_ms: number, };
