// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboxStatus } from "./OutboxStatus";
import type { PlaceStatus } from "./PlaceStatus";

/**
 * One channel binding as health reports it (spec P5: bindings as a file).
 */
export type BindingStatus = { 
/**
 * "discord".
 */
kind: string, 
/**
 * unconfigured | disabled | connecting | ready | resuming | disconnected | failed
 */
state: string, 
/**
 * Why it is in that state, when that is not obvious (a missing file, a close code).
 */
detail?: string, bot_user?: string, guild_id?: string, bindings_file?: string, 
/**
 * First 12 hex of the bindings file's SHA-256: the binding revision.
 */
revision?: string, places: Array<PlaceStatus>, connected_at_ms: number, 
/**
 * Gateway heartbeat round trip.
 */
latency_ms?: number, messages_in: number, messages_out: number, edits: number, interactions: number, ignored: number, errors: number, last_error?: string, 
/**
 * The developer portal has the Server Members intent on for this bot
 * (the application's flags): who can view a guild channel can then be
 * checked. None until the binding has asked.
 */
members_intent?: boolean, 
/**
 * Its outbox (theseus-q4v): the posts waiting for it, and how delivery
 * goes. The core fills it in for health.
 */
outbox?: OutboxStatus, };
