// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A binary's build (theseus-9o5n): constants taken when it was compiled,
 * never computed at a start. Health and each `server.started` row name it,
 * so a start whose build differs from the one before it was an install,
 * not a restart of the same binary.
 */
export type Build = { 
/**
 * The workspace's version (`CARGO_PKG_VERSION`).
 */
version: string, 
/**
 * The git commit it was built from, in full; absent from a build made
 * outside a git checkout without `THESEUS_COMMIT` set.
 */
commit?: string, };
