// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health's count of one backend's cancels in one state, since the daemon
 * started (`theseus.cancel{backend,state}`).
 */
export type CancelCount = { 
/**
 * `l0`, `l1`, `async`, or `inproc`; `job` for a job whose class its
 * verdict cannot tell.
 */
backend: string, 
/**
 * `verified`, `uncertain`, or `unsupported`.
 */
state: string, n: number, };
