// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one call a cancel or a stop reached ended.
 */
export type CancelVerdict = { correlation_id: string, tool: string, 
/**
 * The cancel's last state: `termination_verified`, `outcome_uncertain`,
 * or `unsupported`.
 */
state: string, 
/**
 * How it is known: `pidns` (an L1 job's pid namespace), `cgroup` (an
 * L1 job's, in records from before theseus-gyin), `tree`
 * (an L0 job's process tree, its wrapper's descendants), `group` (a
 * wrapper from before 18a: its process group), `task` (an async tool's),
 * or `none` (a call that cannot be stopped). For one not verified, what
 * was tried.
 */
verified_by: string, 
/**
 * The processes the stop ended (a job's).
 */
killed?: number, 
/**
 * The processes still alive after it: 0 when verified.
 */
survivors?: number, 
/**
 * What the stop could see: `descendants` at L0, `namespace`, `cgroup`
 * (before theseus-gyin), `group`.
 */
scope?: string, 
/**
 * From the stop's signal to its verdict.
 */
ms: number, 
/**
 * Why it is not verified, when it is not.
 */
why?: string, };
