// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModel } from "./CatalogModel";

export type CatalogListResult = { version: string, models: Array<CatalogModel>, };
