// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogModel = { model: string, 
/**
 * The catalog row as configured (provider, window, prices, capabilities, source).
 */
entry: Record<string, unknown>, 
/**
 * Profiles that use this model.
 */
profiles: Array<string>, 
/**
 * The config's `[catalog."<model>"]` table, as written, when it has one
 * (theseus-vwar): `entry` holds what it changes, and one that copies the
 * code's row changes nothing.
 */
config?: Record<string, unknown>, 
/**
 * The code's own row for the model, when the config's table is over a
 * model the code has: what the table changes is where the two differ.
 */
code?: Record<string, unknown>, };
