// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A request's bytes by how densely a tokenizer reads them (theseus-f5hf).
 */
export type CensusSummary = { 
/**
 * Tool schemas, tool inputs, and tool results, in bytes.
 */
json: number, 
/**
 * The system's text and the messages' text and thinking, in bytes.
 */
text: number, 
/**
 * Thinking signatures and redacted thinking, in bytes.
 */
opaque: number, 
/**
 * Messages, and the system's blocks.
 */
messages: number, 
/**
 * Content blocks.
 */
blocks: number, 
/**
 * Tool call ids, in `tool_use` and `tool_result` blocks.
 */
ids: number, };
