// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompilationInfo = { compilation_id: string, session_id: string, created_at_ms: number, trigger: string, strategy: string, as_of: number, includes: number, derived_from?: string, 
/**
 * The manifest as stored (model, provider, digests, catalog version, strip_thinking).
 */
manifest: Record<string, unknown>, 
/**
 * This is the session's current compilation.
 */
current: boolean, };
