// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilationInfo } from "./CompilationInfo";

export type CompilationListResult = { compilations: Array<CompilationInfo>, };
