// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmRequest } from "./ConfirmRequest";

/**
 * `confirm.list`: the questions of every session parked on one, the most
 * recently active session first.
 */
export type ConfirmListResult = { confirms: Array<ConfirmRequest>, };
