// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `confirm.resolved`: a question waiting for the operator closed.
 */
export type ConfirmResolved = { session_id: string, correlation_id: string, approved: boolean, 
/**
 * Who answered or closed it; absent when new input superseded a call's
 * question.
 */
by?: string, 
/**
 * An answer to a tool call: whether it trusted the session again
 * (theseus-9bp).
 */
trust?: boolean, 
/**
 * New input came before an answer.
 */
superseded?: boolean, 
/**
 * Its execution was cancelled before an answer (theseus-w98).
 */
cancelled?: boolean, 
/**
 * A `/stop` declined it while it waited (W1).
 */
stopped?: boolean, 
/**
 * A raised spend limit withdrew a budget question (theseus-3pj).
 */
withdrawn?: boolean, };
