// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Audience } from "./Audience";
import type { CacheSummary } from "./CacheSummary";
import type { ContextFileRef } from "./ContextFileRef";
import type { EstimateSummary } from "./EstimateSummary";
import type { Readers } from "./Readers";

/**
 * `context.compiled`: the context a loop's request was compiled from
 * (§3.13). The `context.compiled` ledger row and the trace's compile span
 * carry the same.
 */
export type ContextCompiled = { session_id: string, turn_id: string, loop: number, 
/**
 * `recompile` (a new compilation) or `append`.
 */
decision: string, 
/**
 * What made it recompile (`new_session`, `window`, `manual_fresh`, …);
 * `null` for an append.
 */
trigger: string | null, compilation_id: string, 
/**
 * The compilation's strategy: `fresh` or `transcript`.
 */
strategy: string, prefix_nodes: number, tail_nodes: number, messages: number, est_tokens: number, 
/**
 * How `est_tokens` was reached (theseus-f5hf); absent in rows written
 * before it.
 */
estimate?: EstimateSummary, digest: string, 
/**
 * The tool calls that had no result, given a synthetic one.
 */
repairs: Array<string>, 
/**
 * Tools offered.
 */
tools: number, nodes_scanned: number, context_files?: Array<ContextFileRef>, 
/**
 * The persona in play (theseus-c48).
 */
persona?: string, cache: CacheSummary, 
/**
 * Who sees what the model says, as this compile evaluated it (M4 19a);
 * absent from a daemon before it.
 */
audience?: Audience, 
/**
 * Nodes and context files the request carries as placeholders, since
 * their readers do not cover the audience (M4 19a).
 */
withheld?: number, 
/**
 * Who may read what the model writes from this request (M4 19c): the
 * meet of what it admitted, which labels its answer. In a guild channel
 * the binding streams that answer only when whoever views the channel
 * may read it, whoever that is; otherwise its text waits for the reply's
 * post, which is checked against who can view the channel then.
 */
readers?: Readers, };
