// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Readers } from "./Readers";

/**
 * A context file as the system block carried it (theseus-58a).
 */
export type ContextFileRef = { 
/**
 * The file, `~` expanded.
 */
path: string, 
/**
 * The first 16 hex digits of the SHA-256 of the text included; absent
 * when the file could not be read.
 */
digest?: string, 
/**
 * Bytes of the file the block carries.
 */
bytes: number, 
/**
 * The file was longer than the cap, and the block carries its start.
 */
cut?: boolean, 
/**
 * Why the file could not be read: `not found`, `permission denied`, …
 */
missing?: string, 
/**
 * The persona whose file this is (theseus-c48); absent: the system
 * level, which every session gets (and every file before theseus-c48).
 */
persona?: string, 
/**
 * Who may read it, when the config says (`readers = "public"`); absent:
 * the owner alone (M4 19a).
 */
readers?: Readers, 
/**
 * The block carries its header alone, and why: its readers do not cover
 * the session's audience (M4 19a).
 */
withheld?: string, };
