// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The context files in the config (theseus-c48), as configured: the
 * system level, which every session gets, and the persona in play, whose
 * files follow the system level's. Until Jev chooses a persona, the persona
 * in play is `[context].default_persona`.
 */
export type ContextStatus = { system_files: Array<string>, persona?: string, persona_files: Array<string>, 
/**
 * Every persona the config defines.
 */
personas: Array<string>, };
