// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheSummary } from "./CacheSummary";
import type { ContextFileRef } from "./ContextFileRef";
import type { EstimateSummary } from "./EstimateSummary";

/**
 * `context.compiled`: the context a loop's request was compiled from
 * (§3.13). The `context.compiled` ledger row and the trace's compile span
 * carry the same.
 */
export type ContextCompiled = { session_id: string, turn_id: string, loop: number, 
/**
 * `recompile` (a new compilation) or `append`.
 */
decision: string, 
/**
 * What made it recompile (`new_session`, `window`, `manual_fresh`, …);
 * `null` for an append.
 */
trigger: string | null, compilation_id: string, 
/**
 * The compilation's strategy: `fresh` or `transcript`.
 */
strategy: string, prefix_nodes: number, tail_nodes: number, messages: number, est_tokens: number, 
/**
 * How `est_tokens` was reached (theseus-f5hf); absent in rows written
 * before it.
 */
estimate?: EstimateSummary, digest: string, 
/**
 * The tool calls that had no result, given a synthetic one.
 */
repairs: Array<string>, 
/**
 * Tools offered.
 */
tools: number, nodes_scanned: number, context_files?: Array<ContextFileRef>, 
/**
 * The persona in play (theseus-c48).
 */
persona?: string, cache: CacheSummary, };
