// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health's credential requests since the daemon started (M4 18d): how many
 * were asked, granted, and declined, and how many wait for the operator now.
 */
export type CredRequests = { since_start: number, granted: number, declined: number, waiting: number, };
