// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Discord ids behind an answer, which the Discord binding reads off the
 * button press (theseus-sgh). The core takes them only from the binding's
 * own connection.
 */
export type DiscordOrigin = { user_id: string, channel_id: string, 
/**
 * None in a DM.
 */
guild_id?: string, };
