// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free space on the filesystem that holds the state dir (theseus-102), from
 * `statvfs` at the moment health is asked: the space an unprivileged
 * process may still use. On a full disk every append to the store fails, the
 * rows that would say so among them, so health warns first (`low`, under
 * `[server] disk_warn_mb`), and below `[server] disk_floor_mb` a new job is
 * refused with its reason (`below_floor`).
 *
 * It sees only the filesystem Linux reports. Under WSL that is the virtual
 * disk, itself a file on the Windows drive (C:), and C: can fill first while
 * this still shows room: check the Windows drive there too.
 */
export type DiskStatus = { 
/**
 * The state dir whose filesystem this is.
 */
path: string, 
/**
 * `ok`, `low` (under the warning), `below_floor` (jobs are refused), or
 * `unknown` (the filesystem could not be read: `error` says why).
 */
state: string, free_mb: number, total_mb: number, 
/**
 * `[server] disk_warn_mb`; 0 never warns.
 */
warn_mb: number, 
/**
 * `[server] disk_floor_mb`; 0 refuses no job.
 */
floor_mb: number, error?: string, };
