// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CensusSummary } from "./CensusSummary";

/**
 * How the compiler sized a request (theseus-f5hf): the provider's own count
 * of what the request repeats, and the rest from its bytes at the catalog's
 * figures.
 */
export type EstimateSummary = { 
/**
 * What the provider will count: `counted` + `estimated`.
 */
tokens: number, 
/**
 * `counted` (part of it is the provider's count) or `bytes` (all of it
 * is from bytes).
 */
method: string, 
/**
 * The provider's count of this compilation's last request (its input,
 * cache reads, and cache writes), plus its answer's output tokens.
 */
counted: number, 
/**
 * The rest, from its bytes at the catalog's `bytes_per_token`.
 */
estimated: number, 
/**
 * What the ring checks: `counted`, plus `estimated` and its margin.
 */
upper: number, 
/**
 * The request's bytes as JSON, base64 image data left out: the estimate
 * before theseus-f5hf was a fourth of it.
 */
bytes: number, 
/**
 * The whole request's bytes by class.
 */
census: CensusSummary, };
