// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelVerdict } from "./CancelVerdict";
import type { ExecutionInfo } from "./ExecutionInfo";

export type ExecutionCancelResult = { execution: ExecutionInfo, 
/**
 * Dispatched actions whose backends were asked to stop.
 */
cancelled_actions: Array<string>, 
/**
 * How each of them stopped, and how that is known (M4 18a).
 */
verdicts: Array<CancelVerdict>, };
