// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionInfo } from "./ExecutionInfo";

export type ExecutionStopResult = { execution: ExecutionInfo, 
/**
 * False when the execution had ended already: nothing was stopped.
 */
stopped: boolean, 
/**
 * Running jobs and calls whose backends were asked to stop.
 */
stopped_actions: Array<string>, 
/**
 * Planned calls, approvals, and a budget question that will not run.
 */
declined: Array<string>, 
/**
 * A turn was running: it ends at its next step.
 */
turn_running: boolean, 
/**
 * What goes on, which `/cancel <id>` stops one by one: the session's
 * running tasks and its pending wakes.
 */
tasks_running: number, wakes_pending: number, };
