// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `execution.stop` (W1, theseus-lji; `/stop`): halt a conversation's work
 * and keep the conversation. Its running jobs and calls are told to stop,
 * what waits on the operator is declined, and a running turn plans nothing
 * more; the execution then waits on its next input. A task is refused:
 * `task.cancel` stops one.
 */
export type ExecutionStopParams = { execution_id: string, 
/**
 * Who asked, as a label in the ledger (e.g. `discord:eddie`). Default:
 * the surface.
 */
author?: string, };
