// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `executions.watch`: its snapshot's size. It replaces any earlier watch on
 * the same connection.
 */
export type ExecutionsWatchParams = { 
/**
 * How many of the executions that need no one and do nothing (ready or
 * idle) the snapshot carries, the most recently active first: 200 by
 * default. Every execution that needs you or works is always there.
 */
limit?: number, };
