// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetInfo } from "./BudgetInfo";

/**
 * One execution as the protocol shows it (spec §3.15).
 */
export type ExecutionInfo = { execution_id: string, session_id: string, kind: string, state: string, turns: number, 
/**
 * Times a crash interrupted a running turn (requeued at startup).
 */
interrupted: number, 
/**
 * Dispatched actions not yet settled.
 */
outstanding: number, 
/**
 * Settled results the next turn will consume.
 */
queued_results: number, budget: BudgetInfo, wake?: unknown, reports_to?: string, ended_reason?: string, created_at_ms: number, updated_at_ms: number, };
