// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionInfo } from "./ExecutionInfo";

export type ExecutionListResult = { executions: Array<ExecutionInfo>, };
