// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attention } from "./Attention";
import type { PendingConfirm } from "./PendingConfirm";
import type { SessionKind } from "./SessionKind";
import type { WaitingOn } from "./WaitingOn";

/**
 * One execution as every surface shows it: `execution.changed`'s params, and
 * a row of `executions.watch`'s snapshot.
 */
export type ExecutionView = { 
/**
 * The WAL position of the last record of the frame this view comes from:
 * it only grows, per execution. A client applies a view only if its
 * position is greater than the last it applied.
 */
position: number, 
/**
 * When that frame was committed.
 */
at_ms: number, execution_id: string, session_id: string, kind: SessionKind, 
/**
 * A task's parent session: the tree.
 */
parent_session_id?: string, 
/**
 * `queued`, `running`, `waiting`, `blocked`, `cancelled`, `failed`,
 * `budget_exhausted`, or `complete`; a newer daemon may add one.
 */
state: string, 
/**
 * The state before this frame; absent for an execution first seen.
 */
previous?: string, 
/**
 * What it waits on, while it waits.
 */
waiting_on?: WaitingOn, 
/**
 * Its questions for the operator: a budget question first.
 */
pending: Array<PendingConfirm>, 
/**
 * Turns taken.
 */
turns: number, 
/**
 * Its spend since the last reset, and its limit, in US dollars.
 */
spent_usd: number, limit_usd: number, 
/**
 * Why it ended, failed, or is blocked.
 */
ended_reason?: string, 
/**
 * Why it was queued, when the frame says (`wake`, `report`, `task`,
 * `input`, …).
 */
why?: string, 
/**
 * Its soonest pending wake (`wake.at`), while it has one.
 */
wake_at_ms?: number, attention: Attention, };
