// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalText } from "./ExternalText";
import type { Notice } from "./Notice";

/**
 * The policy's verdict on a call, as the gate records it.
 */
export type GateDecision = { 
/**
 * `open`, `notify`, or `approve`. A record from before postures has
 * `mode` instead.
 */
posture?: string, 
/**
 * A record from before postures: its band (`auto`, `confirm`, …).
 */
mode?: string, reason: string, 
/**
 * The notice a `notify` posture posts.
 */
notify?: Notice, 
/**
 * The floor asked: the call touches Theseus's own binary or state, or the
 * 1Password CLI or token. No setting makes it run unasked.
 */
floor?: boolean, 
/**
 * What the secret broker gives the call, by name: `gh got GH_TOKEN`
 * (theseus-dcy).
 */
granted?: string, 
/**
 * The call waits (or is notified) because its session read external
 * text (theseus-9bp): what it read.
 */
external?: ExternalText, };
