// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the gate did with the call.
 */
export type GateResult = { 
/**
 * `allow` (it runs), `needs_confirm` (it waits for `by`), or `deny`
 * (its input failed validation, and `reason` says how; it never runs).
 */
gate: string, reason?: string, by?: string, };
