// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Audience } from "./Audience";
import type { Readers } from "./Readers";
import type { Warrant } from "./Warrant";

/**
 * What a graduation wrote: `label.graduate`'s result.
 */
export type GraduateResult = { 
/**
 * The graduated node, new in the session's tail.
 */
node_id: string, session_id: string, readers: Readers, warrant: Warrant, 
/**
 * The session's audience now, and whether the new readers cover it: when
 * they do, its next compile admits the node.
 */
audience: Audience, covers: boolean, };
