// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One grant of the secret broker (theseus-dcy): who gets which secret, how,
 * and how often since the daemon started. Never a value.
 */
export type GrantStatus = { 
/**
 * `program`, for a job's program by its argv, or `tool`, for a toollet.
 */
kind: string, 
/**
 * The program (`gh`) or the toollet (`web.search`).
 */
to: string, 
/**
 * The environment variable a program gets it in.
 */
variable?: string, 
/**
 * The `[secrets]` name.
 */
secret: string, 
/**
 * The secret's posture: a call given it runs at no looser one.
 */
posture: string, 
/**
 * Times handed out since the daemon started.
 */
uses: number, };
