// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a job may be handed, and what stays the harness's own (theseus-gh7):
 * the secrets the operator's `[broker]` names, which a job may get (a
 * program's grant at its start), and the AWS keys and the providers' keys,
 * which only Theseus's own tools read. Names only, never a value.
 */
export type HarnessOnly = { 
/**
 * Each secret a job may be handed: every one `[broker]` names.
 */
handed: Array<string>, 
/**
 * The AWS keys' `[secrets]` names.
 */
aws: Array<string>, 
/**
 * The providers' keys' `[secrets]` names.
 */
providers: Array<string>, 
/**
 * Those of `aws` and `providers` that `[broker]` names after all, so a
 * job may be handed them: the operator's own choice, said aloud.
 */
exposed: Array<string>, };
