// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";
import type { BindingStatus } from "./BindingStatus";
import type { ChildrenStatus } from "./ChildrenStatus";
import type { ConfigStatus } from "./ConfigStatus";
import type { ContextStatus } from "./ContextStatus";
import type { DiskStatus } from "./DiskStatus";
import type { ExternalTextInfo } from "./ExternalTextInfo";
import type { GrantStatus } from "./GrantStatus";
import type { KernelStatus } from "./KernelStatus";
import type { SecretsStatus } from "./SecretsStatus";
import type { SpoolStatus } from "./SpoolStatus";
import type { StartupPhase } from "./StartupPhase";
import type { TelemetryStatus } from "./TelemetryStatus";
import type { Tightening } from "./Tightening";
import type { Usage } from "./Usage";
import type { WakeInfo } from "./WakeInfo";
import type { WebStatus } from "./WebStatus";

export type HealthResult = { name: string, version: string, protocol: string, uptime_secs: number, sessions: number, turns: number, model: string, 
/**
 * The live profile name.
 */
profile: string, 
/**
 * Default provider name and every configured provider.
 */
provider: string, providers: Array<string>, 
/**
 * The secrets whose values are ready (names only).
 */
secrets_resolved: Array<string>, 
/**
 * Where every secret stands: the daemon serves before they resolve
 * (theseus-qa0), and each consumer waits for its own.
 */
secrets: SecretsStatus, 
/**
 * Where the config came from, and whether the vault has confirmed the
 * copy this start served from (theseus-2fo).
 */
config: ConfigStatus, 
/**
 * The last start's phases, timed from process start: those on the path
 * to answering the socket, then those after it.
 */
startup: Array<StartupPhase>, 
/**
 * Tokens across every session, summed from session records.
 */
usage_total: Usage, provider_errors: number, ledger_rows: number, telemetry: TelemetryStatus, 
/**
 * The durable kernel (M2): executions, actions, admission.
 */
kernel: KernelStatus, 
/**
 * The daemon's own children: its job wrappers, the orphans it adopted,
 * and what waits to be reaped (theseus-z4b).
 */
children: ChildrenStatus, 
/**
 * The secret broker's grants, each with its uses (theseus-dcy). Names
 * only, never a value.
 */
broker: Array<GrantStatus>, 
/**
 * Dollars across every session, from the model catalog.
 */
cost_usd_total: number, catalog_version: string, 
/**
 * Channel bindings (M3: Discord) and what each is doing.
 */
bindings: Array<BindingStatus>, 
/**
 * `narrative = true` in the config: the narrative runs, and the web UI
 * shows its tab.
 */
narrative: boolean, 
/**
 * The context files every session's system block carries, and the
 * persona in play with its own (theseus-c48).
 */
context: ContextStatus, 
/**
 * Who may answer a waiting call, and through which channels (theseus-sgh).
 */
approval: ApprovalStatus, 
/**
 * The tools that ask first because someone pressed "should have asked"
 * (theseus-sgh), oldest first. They are stored, not configured.
 */
tightenings: Array<Tightening>, 
/**
 * The wakes conversations set with `wake.at` that have not run yet,
 * soonest first (DD8).
 */
wakes: Array<WakeInfo>, 
/**
 * The sessions that hold external text (theseus-9bp), the longest-held
 * first: in each, a call that acts waits for approval until the operator
 * trusts it again.
 */
external_text: Array<ExternalTextInfo>, 
/**
 * The web UI's refusals since the daemon's image started (theseus-70f).
 */
web: WebStatus, 
/**
 * Free space under the state dir, read when health is asked
 * (theseus-102).
 */
disk: DiskStatus, 
/**
 * The spool's sweeps of raw job output (theseus-2ij).
 */
spool: SpoolStatus, };
