// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health's count of held posts (M4 19c).
 */
export type HeldPosts = { 
/**
 * Held now: waiting for the owner's answer, or answered and not yet
 * delivered.
 */
now: number, 
/**
 * Held since the daemon started.
 */
since_start: number, };
