// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexRebuildResult = { 
/**
 * The rebuild was queued: the tender drops the index and backfills.
 */
accepted: boolean, };
