// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One source's rank (from 1) and raw score for a hit.
 */
export type IndexSourceRank = { rank: number, score: number, };
