// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexEmbedTask } from "./IndexEmbedTask";

export type IndexEmbedParams = { 
/**
 * At most 64, each cut at 512 tokens.
 */
texts: Array<string>, task: IndexEmbedTask, 
/**
 * 768 (the default) or 256 (the Matryoshka cut, as scanned).
 */
dims?: number, 
/**
 * How long to wait for the model to load.
 */
wait_ms: number, };
