// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexStatus } from "./IndexStatus";
import type { TenderStatus } from "./TenderStatus";

/**
 * Health's `index` block, and the core's answer to `index.status` (roadmap
 * row 51): the tender as the core supervises it, and the tender's own status
 * when it answers.
 */
export type IndexHealth = { 
/**
 * In a word: `off` (`[index] enabled = false`), `down` (no tender
 * answers: `why` says why, and `tender` when it starts again), or the
 * tender's own state (`starting`, `backfilling`, `ready`, `stalled`).
 */
state: string, why?: string, 
/**
 * The tender process, as the core supervises it: also in `children`.
 */
tender?: TenderStatus, 
/**
 * The tender's own `index.status`, when it answered.
 */
status?: IndexStatus, };
