// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `index.forget` (theseus-64x): what must leave the index now. The core's
 * removal paths call it: an operator's forget (a `Suppression`) and a
 * redaction (§5.6) name nodes; a text found copied where the lineage walk
 * did not reach can be named as a hit gave it.
 */
export type IndexForgetParams = { 
/**
 * Nodes that leave the index whole.
 */
nodes?: Array<string>, 
/**
 * Chunk texts, exactly as a hit's `text` gives them: every chunk that
 * holds one leaves the index.
 */
texts?: Array<string>, };
