// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the embedding thread has done since the tender started.
 */
export type IndexEmbedStats = { 
/**
 * Distinct texts embedded, in batches.
 */
texts: number, batches: number, 
/**
 * Tokens embedded, padding not counted.
 */
tokens: number, 
/**
 * Texts past 512 tokens, embedded in windows.
 */
windowed: number, 
/**
 * Texts cut at the windows' cap (about 4,000 tokens).
 */
truncated: number, 
/**
 * The embedding thread's wall time and CPU time in batches.
 */
wall_ms: number, cpu_ms: number, 
/**
 * Texts that would not embed (left without a vector).
 */
failed: number, };
