// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexHit } from "./IndexHit";
import type { IndexLag } from "./IndexLag";
import type { IndexTimings } from "./IndexTimings";

export type IndexQueryResult = { hits: Array<IndexHit>, 
/**
 * The position the index holds every node through.
 */
indexed_through: number, lag: IndexLag, timings: IndexTimings, 
/**
 * Sources asked for (or defaulted to) that did not answer, and why: the
 * model loading, or no weights.
 */
skipped?: { [key in string]: string }, 
/**
 * Each fused source's weight: the query's, or the tender's default.
 */
weights?: { [key in string]: number }, };
