// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Each stage's time, in milliseconds.
 */
export type IndexTimings = { bm25_ms: number, entity_ms: number, 
/**
 * Embedding the query (the vector source's first stage).
 */
embed_ms: number, 
/**
 * The int8 scan and the 768-d re-score.
 */
vector_ms: number, fuse_ms: number, load_ms: number, total_ms: number, };
