// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What every vector carries: the model and its files, the code that made
 * it, and the precision. A vector answers a query embedded under the same
 * space (model, files, dimensions); a changed stamp re-embeds.
 */
export type IndexStamp = { 
/**
 * `<name>@<revision>`.
 */
model: string, 
/**
 * `model.safetensors`' SHA-256.
 */
weights: string, 
/**
 * `tokenizer.json`'s SHA-256.
 */
tokenizer: string, 
/**
 * The engine and the tender's embedding code: `candle-0.11.0+embed.1`.
 */
engine: string, precision: string, 
/**
 * The scanned cut and the full vector: `[256, 768]`.
 */
dims: [number, number], };
