// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far the index is behind the WAL: the bytes after its cursor, and how
 * long it has been behind (0 when caught up).
 */
export type IndexLag = { bytes: number, ms: number, };
