// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexChunkRef } from "./IndexChunkRef";

export type IndexForgetResult = { 
/**
 * Nodes that left the index whole (those it held).
 */
nodes: number, 
/**
 * Chunks that left it: the nodes' and the texts'.
 */
chunks: number, 
/**
 * Records dropped from the vector files: the texts that left, and
 * every other dead record.
 */
vectors_dropped: number, 
/**
 * Chunks not forgotten that hold the same text as one that left, so its
 * vector stays: name them too if the text must go.
 */
still_held?: Array<IndexChunkRef>, 
/**
 * The vector files rewritten, and their bytes before and after.
 */
files: number, bytes_before: number, bytes_after: number, ms: number, };
