// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexNeighbour } from "./IndexNeighbour";

export type IndexNeighboursResult = { node_id: string, neighbours: Array<IndexNeighbour>, vector_ms: number, };
