// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Integrity in play (the manifest's `integrity`): the session holds
 * external text (T1's latch), and how many admitted nodes are untrusted.
 */
export type InPlay = { latched: boolean, untrusted: number, };
