// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a node's text came from outside Theseus. `untrusted` wins when
 * two meet. `Quarantined` comes with the Advisory (the reader rule).
 */
export type Integrity = "trusted" | "untrusted";
