// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One L1 job's cgroup.
 */
export type JobUsage = { correlation_id: string, 
/**
 * `memory.current`, in bytes.
 */
memory_bytes: number, 
/**
 * `memory.max`, in bytes; absent for `max` (no limit).
 */
memory_max?: number, 
/**
 * `memory.peak`, where the kernel keeps one.
 */
memory_peak?: number, 
/**
 * `pids.current`: its processes and threads now.
 */
pids: number, 
/**
 * `pids.max`; absent for `max`.
 */
pids_max?: number, 
/**
 * Forks `pids.max` refused (`pids.events`).
 */
pids_refused: number, 
/**
 * A process is still in it (`cgroup.events`).
 */
populated: boolean, };
