// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalText } from "./ExternalText";
import type { Integrity } from "./Integrity";
import type { Readers } from "./Readers";
import type { Warrant } from "./Warrant";

/**
 * A node's label (§2.5).
 */
export type Label = { integrity: Integrity, 
/**
 * Why it is untrusted: where its text came from, in T1's shape (the
 * tool, the URL, the node). Absent on a trusted node.
 */
source?: ExternalText, readers: Readers, 
/**
 * Why its readers are wider than its source's (M4 19c): the operator
 * graduated it. Absent on every node that was not graduated.
 */
warrant?: Warrant, };
