// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeldPosts } from "./HeldPosts";
import type { PlaceAudience } from "./PlaceAudience";

/**
 * Health's `labels` block (M4 19a): who the owner is on Discord, and each
 * guild channel's audience as the binding last read it.
 */
export type LabelsHealth = { 
/**
 * The owner's Discord ids (`[labels] owner`, else `[approval]
 * trusted_users`), counted; the CLI and the web UI are the owner's too.
 */
owners: number, 
/**
 * Each guild channel whose viewers the binding has read.
 */
places: Array<PlaceAudience>, 
/**
 * Replies the outbox held for the owner (M4 19c), when any was held
 * since the daemon started.
 */
held?: HeldPosts, };
