// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `label.graduate` (M4 19c): widen who may read a node, by a new node that
 * carries its content with the operator's warrant. The node keeps its own
 * label, and its placeholder stays where it was.
 */
export type LabelGraduateParams = { node_id: string, 
/**
 * `public`, `place` (whoever can view the session's place), or
 * `people:<id>[,<id>…]`.
 */
to: string, 
/**
 * Why, in the operator's words: the warrant's reason.
 */
why: string, 
/**
 * Who graduated it, as a label. Default: the connection. It names and
 * proves nothing; the connection's surface decides.
 */
author?: string, discord?: DiscordOrigin, };
