// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LedgerTailParams = { n: number | null, 
/**
 * Only rows of this kind (e.g. "turn.ended", "provider.error"). A renamed
 * kind also reads the rows stored under its old name.
 */
kind: string | null, session_id: string | null, };
