// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ledger.tail`'s params: the newest `n` rows, or the first `n` after a position.
 */
export type LedgerTailParams = { n: number | null, 
/**
 * Only rows of this kind (e.g. "turn.ended", "provider.error"). A renamed
 * kind also reads the rows stored under its old name.
 */
kind: string | null, session_id: string | null, 
/**
 * Only rows after this WAL position, and the first `n` of them, where
 * without it the read is the newest `n` (theseus-xo0m). A walk over the
 * whole ledger passes 0, then each answer's `next`; a poll passes the
 * last position it has. A read, as the rest of `ledger.tail` is.
 */
after?: number, };
