// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerEntry } from "./LedgerEntry";

export type LedgerTailResult = { rows: Array<LedgerEntry>, total: number, };
