// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much an execution needs people, the most first: a question or a
 * failure (`needs_you`), work under way (`working`), a conversation between
 * exchanges (`ready`), or nothing more to do (`idle`). A client's own "done
 * until seen" sits between `needs_you` and `working` in its order.
 */
export type Level = "needs_you" | "working" | "ready" | "idle";
