// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpRestartResult = { name: string, 
/**
 * The state it was in when asked.
 */
was: string, };
