// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configured MCP server, as the board has it now: health's `mcp[]`.
 */
export type McpServerStatus = { name: string, 
/**
 * `stdio` or `http`.
 */
transport: string, 
/**
 * `stopped` (not started yet), `starting`, `ready`, `exited`,
 * `restarting`, `failed`, or `disabled`.
 */
state: string, 
/**
 * A stdio server's process (and process group).
 */
pid?: number, 
/**
 * The tools offered now: the live list, or the stored one until the
 * server lists them.
 */
tools: number, prompts: number, 
/**
 * Whether the tools offered are the stored list (`mcp.tools.<server>`),
 * the server not having listed them since the start.
 */
stored: boolean, 
/**
 * Calls and failed calls since the daemon started.
 */
calls: number, errors: number, 
/**
 * Crashes since the last start that stayed up, or the last restart.
 */
crashes: number, last_error?: string, 
/**
 * When it last became ready, in ms since the epoch.
 */
started_at_ms?: number, 
/**
 * The negotiated protocol revision.
 */
protocol?: string, 
/**
 * The digest of the tool list offered.
 */
digest: string, 
/**
 * `read` entries the server does not list.
 */
unknown_read?: Array<string>, };
