// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerRefusals } from "./McpServerRefusals";

/**
 * The MCP server (`[mcp_server]`): whether it listens, where, and what it
 * has served and refused since the daemon's image started. Absent while
 * `[mcp_server]` is off.
 */
export type McpServerHealth = { 
/**
 * `starting` (its key's secret is resolving), `listening`, `stopped`,
 * or `failed`.
 */
state: string, 
/**
 * The port it listens on, once it does.
 */
port: number, 
/**
 * MCP sessions open now, and their clients' names, sorted, once each.
 */
sessions: number, clients: Array<string>, 
/**
 * Conversations opened through it since the start, and the last client
 * to open one.
 */
opened: number, last_client?: string, 
/**
 * Tool calls answered, and those whose answer was an error.
 */
calls: number, errors: number, 
/**
 * Requests refused, by why.
 */
refused: McpServerRefusals, 
/**
 * Why it is not listening, when it failed.
 */
error?: string, };
