// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecallManifest } from "./RecallManifest";

export type MemoryRecallsResult = { session_id: string, 
/**
 * The session's recalls in all.
 */
total: number, recalls: Array<RecallManifest>, };
