// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notification } from "./Notification";
import type { Request } from "./Request";
import type { Response } from "./Response";

/**
 * Any line on the wire.
 */
export type Message = Request | Response | Notification;
