// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which architectural part of the session/turn/loop structure a narrative
 * line comes from.
 */
export type NarrativePart = "session" | "turn" | "loop" | "context" | "model" | "tool" | "approval" | "job" | "config";
