// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfo } from "./NodeInfo";

export type NodeListResult = { nodes: Array<NodeInfo>, total: number, };
