// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Label } from "./Label";

/**
 * One node as clients render it (a message, a tool call, a tool result).
 */
export type NodeInfo = { node_id: string, 
/**
 * `user_message`, `assistant_message`, `tool_call`, `tool_result`.
 */
kind: string, session_id: string, position: number, at_unix_ms: number, turn_id?: string, loop_index?: number, author?: string, 
/**
 * Text for display (user text; assistant text blocks; tool result content).
 */
text: string, 
/**
 * Thinking summaries (assistant), when the provider returned them.
 */
thinking?: string, 
/**
 * Kind-specific fields: model/usage/cost (assistant), tool/input/gate
 * (tool call), tool/status/is_error/bytes (tool result).
 */
detail: Record<string, unknown> | null, bytes: number, 
/**
 * Its label (M4 19a): its integrity and its readers. Absent on a node
 * written before 19a, which is disclosable only within its own session.
 */
label?: Label, 
/**
 * Its readers in words when its session's audience now withholds it
 * (M4 19c): what `label.graduate` could widen. Set by `session.history`.
 */
withheld?: string, };
