// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session's membership in a category.
 */
export type OntologyMembership = { session_id: string, kind: string, category: string, 
/**
 * `transport` (given, read from the session's place, never stored) or
 * `operator`.
 */
origin: string, confidence?: number, as_of_ms: number, };
