// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A category's guidance.
 */
export type OntologyGuidance = { category: string, 
/**
 * Empty: no guidance.
 */
text: string, 
/**
 * 1 when first written, and one more at each change.
 */
version: number, 
/**
 * The first 16 hex digits of the SHA-256 of `text`, as a compile's
 * manifest records it.
 */
digest: string, added_by: string, };
