// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyGuidance } from "./OntologyGuidance";

/**
 * A category, with its guidance.
 */
export type OntologyCategory = { 
/**
 * `<kind>:<local>`: `topic:theseus`, `channel:<id>`.
 */
id: string, kind: string, name: string, parent?: string, 
/**
 * How deep it nests: a root is 1.
 */
depth: number, description: string, added_by: string, 
/**
 * Absent when it has none, or its guidance was taken away (empty text).
 */
guidance?: OntologyGuidance, };
