// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.membership.set`: add a session to categories of interpreted
 * kinds, or take it out. Given kinds' memberships are the session's place,
 * and are refused here. The change waits for the session's next recompile.
 */
export type OntologyMembershipSetParams = { session_id: string, 
/**
 * Categories, each by id or by its name among the topics.
 */
add: Array<string>, remove: Array<string>, author?: string, discord?: DiscordOrigin, };
