// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyMembership } from "./OntologyMembership";

/**
 * What `ontology.membership.set` left: the session's interpreted
 * memberships, every kind's.
 */
export type OntologyMembershipResult = { session_id: string, memberships: Array<OntologyMembership>, 
/**
 * The lists it wrote: none when nothing changed.
 */
changed: Array<string>, };
