// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ontology.list`: the kinds table, every category with its guidance, and
 * memberships: one session's (given ones from its place, and interpreted
 * ones), or, without a session, every interpreted one stored.
 */
export type OntologyListParams = { session_id?: string, };
