// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyCategory } from "./OntologyCategory";
import type { OntologyKind } from "./OntologyKind";
import type { OntologyMembership } from "./OntologyMembership";

export type OntologyListResult = { 
/**
 * By precedence, lowest first: the order the compile walk admits them.
 */
kinds: Array<OntologyKind>, 
/**
 * The category tree, depth first: the roots by name, each followed by
 * its children.
 */
categories: Array<OntologyCategory>, memberships: Array<OntologyMembership>, };
