// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A place Theseus lives in: a text channel or a DM, and the session behind it.
 */
export type PlaceStatus = { 
/**
 * "channel" | "dm".
 */
kind: string, label: string, 
/**
 * The Discord channel id (for a DM, known after the DM channel opens).
 */
channel_id?: string, session_id?: string, 
/**
 * Discord user ids that may drive turns here.
 */
users: Array<string>, 
/**
 * Only messages that @mention the bot or reply to it start turns.
 */
mention_only: boolean, last_activity_ms: number, };
