// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A guild channel's audience, for health.
 */
export type PlaceAudience = { 
/**
 * `discord:<channel id>`.
 */
place: string, name?: string, 
/**
 * How many can view it; absent when that cannot be read (public).
 */
viewers?: number, 
/**
 * How many of them are not the owner: owner-only material is withheld
 * from its session while any is.
 */
others?: number, };
