// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

/**
 * What a call will do, before it does it: the gate reads this.
 */
export type Plan = { resources: Array<Resource>, 
/**
 * For `proc.run`: the exact argv.
 */
argv?: Array<string>, 
/**
 * For a network tool: the URL it asks for (`http.fetch`'s, or the
 * request `web.search` makes). The gate judges its host (DD5).
 */
url?: string, 
/**
 * One line for humans ("edit src/main.rs (1 occurrence)").
 */
summary: string, };
