// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwsPlan } from "./AwsPlan";
import type { Resource } from "./Resource";
import type { ToolClass } from "./ToolClass";

/**
 * What a call will do, before it does it: the gate reads this.
 */
export type Plan = { resources: Array<Resource>, 
/**
 * For `proc.run`: the exact argv.
 */
argv?: Array<string>, 
/**
 * For a network tool: the URL it asks for (`http.fetch`'s, or the
 * request `web.search` makes). The gate judges its host (DD5).
 */
url?: string, 
/**
 * One line for humans ("edit src/main.rs (1 occurrence)").
 */
summary: string, 
/**
 * This call's class, when it is the call's and not the tool's (an
 * `aws.call` is a read or a write by its operation): the gate, the
 * external-text hold, and the reads that run together read it.
 */
class?: ToolClass, 
/**
 * For an AWS call (AWS design §3.9): its account, region, and operation.
 */
aws?: AwsPlan, };
