// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `policy.tighten`: make a tool ask first from now on.
 */
export type PolicyTightenParams = { tool: string, 
/**
 * The call whose notice was pressed, when there is one.
 */
correlation_id?: string, 
/**
 * Who pressed, as a label. Default: the connection. It names and
 * proves nothing; the connection's surface decides.
 */
author?: string, 
/**
 * Set by the Discord binding: the channel and user the press came from.
 */
discord?: DiscordOrigin, };
