// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `policy.notified`: a call ran at a `notify` posture, with its notice.
 */
export type PolicyNotified = { session_id: string, turn_id: string, tool_use_id: string, correlation_id: string, tool: string, input: unknown, 
/**
 * The plan's summary.
 */
summary: string, 
/**
 * What the secret broker gives the call, by name; `null` for nothing.
 */
granted: string | null, 
/**
 * The task that made the call, by its short id (DD7).
 */
task?: string, 
/**
 * `notify`.
 */
kind: string, 
/**
 * The setting that chose the posture, e.g. `enforcement = notify`.
 */
setting: string, 
/**
 * The gate's reason, e.g. `proc.run — notify (enforcement = notify)`.
 */
rule: string, };
