// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `policy.untighten`: the tool goes back to what the config says.
 */
export type PolicyUntightenParams = { tool: string, author?: string, discord?: DiscordOrigin, };
