// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileInfo = { name: string, provider: string, model: string, 
/**
 * Output cap per call (the API's `max_tokens`), not an input limit.
 */
max_output_tokens: number, has_system: boolean, live: boolean, };
