// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A proposed tool call as the model (or a test) states it: what a
 * confirmation binds, by its digest (`theseus_kernel::gate`).
 */
export type Proposal = { tool: string, args: unknown, resource?: string, 
/**
 * Policy context the confirm is bound to (binding revision, role, channel).
 */
policy_context: unknown, };
