// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceClass } from "./PlaceClass";

/**
 * What `place.publish` wrote.
 */
export type PublishResult = { 
/**
 * `discord:channel:<id>`.
 */
place: string, 
/**
 * `#openclaw`.
 */
name: string, class: PlaceClass, 
/**
 * The place's session, and the node written there.
 */
session_id: string, node_id: string, 
/**
 * What it was, in words: `the file /w/notes.md`, `fs.read's result trs_…`.
 */
what: string, bytes: number, 
/**
 * The first 16 hex digits of the SHA-256 of what was published.
 */
digest: string, };
