// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReachTotals = { 
/**
 * Every compilation and loop, the node's and its copies'.
 */
contexts: number, 
/**
 * The sessions the node and its copies are in.
 */
sessions: number, };
