// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compilation whose prefix (`includes`) holds a node.
 */
export type ReachCompilation = { compilation_id: string, 
/**
 * `transcript`, `fresh`, or `ring`.
 */
strategy: string, created_at_ms: number, };
