// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who may see a node; the owner always may. A place is a guild channel,
 * `discord:<channel id>`, and a person `discord:<user id>`.
 */
export type Readers = "public" | { "place": string } | { "people": Array<string> } | "owner";
