// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexTimings } from "./IndexTimings";

/**
 * Each stage's time, in milliseconds.
 */
export type RecallTimings = { 
/**
 * From the ask to the index's answer (or the deadline).
 */
index_ms: number, 
/**
 * The places, the filters, the rank, and the pack.
 */
pack_ms: number, total_ms: number, 
/**
 * The deadline the index had.
 */
deadline_ms: number, 
/**
 * The index's own stages, as it answered.
 */
index?: IndexTimings, };
