// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

export type Request = { jsonrpc: string, id: Id, method: string, params?: unknown, };
