// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { RpcError } from "./RpcError";

export type Response = { jsonrpc: string, id: Id, result?: unknown, error?: RpcError, };
