// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxProbe } from "./SandboxProbe";

/**
 * Health's `sandbox` block.
 */
export type SandboxHealth = { 
/**
 * `[sandbox] default`: `l0` or `l1`.
 */
default: string, 
/**
 * `[sandbox] l1_argv`: the programs that always run in L1.
 */
l1_argv: Array<string>, 
/**
 * What an L1 job is given: `[sandbox]`'s limits, in MB and processes.
 */
memory_mb: number, pids: number, scratch_mb: number, output_mb: number, 
/**
 * The probe after serving: absent until it has run.
 */
probe?: SandboxProbe, 
/**
 * Where a job's memory and pids limits come from: `delegated` (the
 * daemon's own systemd unit, with `Delegate=yes`), or why there is no
 * cgroup for jobs. Absent until it has been asked.
 */
cgroup?: string, 
/**
 * Jobs started since the daemon started, by class.
 */
jobs_l0: number, jobs_l1: number, };
