// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobUsage } from "./JobUsage";
import type { RunningJob } from "./RunningJob";

/**
 * `sandbox.usage`: each L1 job's cgroup (`<daemon's cgroup>/jobs/<corr>`) as
 * it stands, read when asked. Without a delegated cgroup there is none to
 * read: the namespaces and `RLIMIT_NPROC` still hold, and `why` says so.
 */
export type SandboxUsage = { 
/**
 * The jobs' cgroup directory, once the first L1 job readied it.
 */
jobs_dir?: string, 
/**
 * Why there is no directory to read, when there is none.
 */
why?: string, 
/**
 * When it was read (unix ms).
 */
at_ms: number, 
/**
 * The jobs whose cgroups are there now, by correlation id.
 */
jobs: Array<JobUsage>, 
/**
 * The L1 jobs running now whose `tool.job_started` row is not written
 * yet (theseus-kpz1): it rides the turn's next frame, after the job ends
 * or its turn stops waiting for it, so until then their commands are
 * here, from the daemon's memory. Listed with or without a cgroup.
 */
running?: Array<RunningJob>, };
