// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobUsage } from "./JobUsage";

/**
 * `sandbox.usage`: each L1 job's cgroup (`<daemon's cgroup>/jobs/<corr>`) as
 * it stands, read when asked. Without a delegated cgroup there is none to
 * read: the namespaces and `RLIMIT_NPROC` still hold, and `why` says so.
 */
export type SandboxUsage = { 
/**
 * The jobs' cgroup directory, once the first L1 job readied it.
 */
jobs_dir?: string, 
/**
 * Why there is no directory to read, when there is none.
 */
why?: string, 
/**
 * When it was read (unix ms).
 */
at_ms: number, 
/**
 * The jobs whose cgroups are there now, by correlation id.
 */
jobs: Array<JobUsage>, };
