// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxProbe } from "./SandboxProbe";

/**
 * Health's `sandbox` block.
 */
export type SandboxHealth = { 
/**
 * `[sandbox] default`: `l0` or `l1`.
 */
default: string, 
/**
 * `[sandbox] l1_argv`: the programs that always run in L1.
 */
l1_argv: Array<string>, 
/**
 * What an L1 job is given: `[sandbox]`'s limits, in MB and processes.
 */
memory_mb: number, pids: number, scratch_mb: number, output_mb: number, 
/**
 * The probe after serving: absent until it has run.
 */
probe?: SandboxProbe, 
/**
 * Where a job's memory and pids limits come from: `delegated` (the
 * daemon's own systemd unit, with `Delegate=yes`), or why there is no
 * cgroup for jobs. Absent until it has been asked.
 */
cgroup?: string, 
/**
 * Jobs started since the daemon started, by class.
 */
jobs_l0: number, jobs_l1: number, 
/**
 * `[sandbox] egress` (M4 18c): the hosts every L1 job may reach through
 * its proxy. Empty: an L1 job has no network unless its call names
 * hosts, and is approved.
 */
egress?: Array<string>, 
/**
 * Since the daemon started: L1 jobs' connections out through their
 * proxies, the bytes they carried each way, and the `CONNECT`s refused.
 */
egress_connections?: number, egress_up?: number, egress_down?: number, egress_refused?: number, 
/**
 * The latest refusal's words, `pypi.org:443 is not on this job's egress
 * list`. Absent until one.
 */
egress_last_refused?: string, };
