// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxLaunch } from "./SandboxLaunch";

/**
 * Health's `sandbox` block.
 */
export type SandboxHealth = { 
/**
 * `[sandbox] default`: `l0` or `l1`.
 */
default: string, 
/**
 * `[sandbox] l1_argv`: the programs that always run in L1.
 */
l1_argv: Array<string>, 
/**
 * What an L1 job is given: `[sandbox]`'s limits, in processes and MB.
 */
pids: number, scratch_mb: number, output_mb: number, 
/**
 * The last real L1 launch since the daemon started (theseus-gyin):
 * absent until the first L1 job has reported.
 */
last_launch?: SandboxLaunch, 
/**
 * Why L1 refuses every job here, when it does (theseus-pv6i): the
 * daemon runs as root, whom Linux exempts from `RLIMIT_NPROC`.
 */
refuses?: string, 
/**
 * Jobs started since the daemon started, by class.
 */
jobs_l0: number, jobs_l1: number, 
/**
 * `[sandbox] egress` (M4 18c): the hosts every L1 job may reach through
 * its proxy. Empty: an L1 job has no network unless its call names
 * hosts, and is approved.
 */
egress?: Array<string>, 
/**
 * Since the daemon started: L1 jobs' connections out through their
 * proxies, the bytes they carried each way, and the `CONNECT`s refused.
 */
egress_connections?: number, egress_up?: number, egress_down?: number, egress_refused?: number, 
/**
 * The latest refusal's words, `pypi.org:443 is not on this job's egress
 * list`. Absent until one.
 */
egress_last_refused?: string, };
