// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The probe's answer: `/bin/true` in L1, started as a job starts, once
 * after serving and again after a restart in place.
 */
export type SandboxProbe = { 
/**
 * L1 runs here.
 */
ok: boolean, 
/**
 * When it ran (unix ms).
 */
at_ms: number, 
/**
 * Why not, when it does not: the stage, and the error.
 */
why?: string, 
/**
 * The start, from the spawn to the command's exec, in ms.
 */
start_ms?: number, 
/**
 * A fresh sysfs was mounted (the kernel may refuse it).
 */
sys?: boolean, 
/**
 * `lo` came up in the job's network namespace.
 */
lo?: boolean, 
/**
 * `[sandbox] ro_paths` that do not exist, so a job is given none of
 * them.
 */
skipped?: Array<string>, };
