// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `secret.requested`: an L1 job asked for a secret through its socket
 * (M4 18d), and what decision 15 made of it then: granted (open, notify),
 * waiting on its card (approve), or declined (a name the broker may not
 * hand out). A waiting one's answer is `confirm.resolved`.
 */
export type SecretRequested = { session_id: string, 
/**
 * The request's own action; empty for one declined at once.
 */
correlation_id: string, 
/**
 * The job that asked: its call's correlation id, and its short form.
 */
job: string, short: string, 
/**
 * The job's command, as its notice names it (`cargo publish`).
 */
command: string, 
/**
 * `secret` (`aws` later).
 */
kind: string, secret: string, 
/**
 * The posture it was judged at: the stricter of the one the job's call
 * ran at and the secret's own (decision 15). Empty when it was declined
 * before any.
 */
posture: string, 
/**
 * What chose the posture, in words: "proc.run ran at notify", or the
 * secret's `[broker.secrets.<name>]` line.
 */
setting: string, 
/**
 * `granted`, `waiting`, or `declined`.
 */
outcome: string, 
/**
 * Why it was declined.
 */
why?: string, };
