// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A secret that comes from outside the vault, and from where (theseus-n88g.1):
 * `kind` is `env` (the daemon's environment) or `file` (a private file).
 * Never the value, the variable, or the path.
 */
export type SecretSource = { name: string, kind: string, };
