// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

export type SessionOpenParams = { kind: SessionKind | null, label: string | null, 
/**
 * The session whose job opened this one (theseus-b5cl): the CLI sends
 * the `THESEUS_SESSION` its job's environment carries (`JOB_SESSION_ENV`).
 * A session opened from one that holds external text holds it too.
 */
opened_from?: string, };
