// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaitUntil } from "./WaitUntil";

/**
 * `session.wait`: until the session's execution is `until`. Owned by the
 * daemon: a parked task that costs nothing while it waits, and ends with its
 * connection.
 */
export type SessionWaitParams = { session_id: string, until: WaitUntil, 
/**
 * Only a view after this position counts; without it the current view
 * does, and a wait already satisfied answers at once (`already`).
 */
after_position?: number, 
/**
 * How long to wait: 10 minutes by default, 24 hours at most.
 */
timeout_ms?: number, };
