// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmRequest } from "./ConfirmRequest";
import type { NodeInfo } from "./NodeInfo";
import type { SessionInfo } from "./SessionInfo";

export type SessionHistoryResult = { session: SessionInfo, nodes: Array<NodeInfo>, 
/**
 * Actions waiting for the operator's confirmation in this session.
 */
pending_confirms: Array<ConfirmRequest>, };
