// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionRecompileParams = { session_id: string, 
/**
 * `fresh` (start over) or `transcript` (keep everything, thinking stripped).
 */
strategy: string, };
