// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Also the kernel's: an execution stores it (`theseus_kernel::SessionKind`).
 */
export type SessionKind = "conversation" | "task";
