// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionHistoryParams = { session_id: string, 
/**
 * Newest `n` nodes (default all).
 */
n: number | null, };
