// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmRequest } from "./ConfirmRequest";
import type { ExecutionView } from "./ExecutionView";

/**
 * `session.wait`'s answer.
 */
export type SessionWaitResult = { 
/**
 * `blocked`, `settled`, `terminal`, or `timeout`.
 */
reached: string, 
/**
 * The wait was satisfied when it began: it never parked.
 */
already: boolean, 
/**
 * The session's execution as the wait ended.
 */
execution?: ExecutionView, 
/**
 * The session's questions for the operator, whole.
 */
confirms: Array<ConfirmRequest>, };
