// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session.list`: every session, or only these (theseus-in3): a client that
 * meets a new session in `execution.changed` asks for its title.
 */
export type SessionListParams = { ids?: Array<string>, };
