// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

export type SessionOpenParams = { kind: SessionKind | null, label: string | null, };
