// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sweep of `spool/results`: counts and bytes, never content. Its
 * `spool.swept` row carries the same.
 */
export type SpoolSweep = { at_unix_ms: number, took_ms: number, removed: number, removed_bytes: number, kept: number, kept_bytes: number, 
/**
 * The files removed, by why: `absorbed` (its result was written),
 * `ended` (its execution ended before a turn read it), `unknown` (no job
 * in the store, and a day old).
 */
removed_by: { [key in string]: number }, 
/**
 * The files kept, by why: `running`, `pending` (its result may still be
 * absorbed), `young` (no job in the store, under a day old), `unread`
 * (the store could not be read for it), `failed` (its delete failed).
 */
kept_by: { [key in string]: number }, };
