// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpoolSweep } from "./SpoolSweep";

/**
 * The spool's sweeps (theseus-2ij): a job's raw output, what it printed
 * before the scrubber saw it, removed once no result will absorb it. A
 * sweep runs after serving, as the daemon starts, then every hour.
 */
export type SpoolStatus = { 
/**
 * The last sweep since the daemon started; none before the first.
 */
last_sweep?: SpoolSweep, };
