// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One phase of the last start (theseus-qa0), timed from process start.
 */
export type StartupPhase = { 
/**
 * `config`, `store`, `providers`, `kernel`, `core`, `socket` on the path
 * to serving, one after another; `secrets`, `provider.<name>` (a turn's
 * first wait for its key), `discord.token`, `github.check`, and
 * `telemetry.headers` after it.
 */
name: string, 
/**
 * After the socket answers: nothing on the path to serving waits for it.
 */
background: boolean, start_us: number, 
/**
 * `None` while it runs.
 */
end_us: number | null, detail: Record<string, unknown> | null, };
