// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `task.list`: every task, the newest first, or only one session's, or
 * only those that report to one place.
 */
export type TaskListParams = { 
/**
 * Only the tasks this session started.
 */
session_id?: string, 
/**
 * Only the tasks that report to this place (`discord:dm:<user>`).
 */
target?: string, };
