// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskInfo } from "./TaskInfo";

export type TaskCancelResult = { task: TaskInfo, 
/**
 * Dispatched actions whose backends were asked to stop.
 */
cancelled_actions: Array<string>, };
