// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task (DD7, theseus-qn2): a child session a conversation opened with
 * `task.create`, which works on its own and reports back to the place.
 */
export type TaskInfo = { 
/**
 * Its session's id (`ses_…`).
 */
task_id: string, 
/**
 * The last six characters of its id, which is how people name it
 * (`/cancel a1b2c3`).
 */
short: string, execution_id: string, parent_session_id: string, parent_execution_id: string, 
/**
 * The brief's first line.
 */
title?: string, 
/**
 * Its execution's state: `queued`, `running`, `waiting`, `complete`, …
 */
state: string, 
/**
 * What it waits on, while it waits: `actions` (a job), `confirm`,
 * `budget`, or `input`.
 */
waiting_on?: string, 
/**
 * Its spend under its carved limit (since any reset), and that limit.
 */
spent_usd: number, limit_usd: number, 
/**
 * What its session has cost in all, resets included.
 */
cost_usd: number, turns: number, 
/**
 * Questions it asks the operator now.
 */
pending_confirms: number, 
/**
 * Where its cards and report go (`discord:dm:<user>`), if anywhere.
 */
target?: string, ended_reason?: string, created_at_ms: number, updated_at_ms: number, 
/**
 * Its report starts its parent's next turn (W1, `wake_parent`).
 */
wake_parent?: boolean, };
