// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `task.cancel`: stop a task and its jobs, as `execution.cancel` does; the
 * place hears that it was cancelled, once.
 */
export type TaskCancelParams = { 
/**
 * Its id, its execution's id, or the end of either (`a1b2c3`), as long
 * as one task matches.
 */
task: string, 
/**
 * Who asked, as the ledger names them. Default: the surface (`the CLI`,
 * `the web UI`; DD8), or the connection's label on a surface no
 * listener named.
 */
author?: string, };
