// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The OTLP exporter (theseus-hee, spec §3.20): what it sent and dropped.
 */
export type TelemetryStatus = { enabled: boolean, otlp_endpoint: string | null, 
/**
 * `off` (no endpoint), `waiting` (for the vault's confirmation of the
 * config, or for the headers secret), `exporting`, or `failed` (the
 * exporter could not be built). Empty from a daemon older than that.
 */
state: string, 
/**
 * Why it waits, or why it failed.
 */
detail?: string, 
/**
 * Batches the receiver took: one per turn's trace, one per metrics export.
 */
traces_sent: number, metrics_sent: number, spans_sent: number, 
/**
 * Batches dropped: after a failed retry, or the oldest trace when the
 * queue was full.
 */
dropped: number, 
/**
 * Traces waiting for the sender.
 */
queued: number, last_error?: string, last_error_at_ms?: number, };
