// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateRecord } from "./GateRecord";

/**
 * `tool.proposed`: the model asked for a call, and what the gate made of it.
 */
export type ToolProposed = { session_id: string, turn_id: string, tool_use_id: string, tool: string, input: unknown, gate: GateRecord, };
