// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolInfo } from "./ToolInfo";

export type ToolListResult = { tools: Array<ToolInfo>, 
/**
 * Workspace roots tools may touch.
 */
roots: Array<string>, 
/**
 * `proc.run` calls over all tool calls (spec §3.23 shell-fallback ratio).
 */
shell_fallback_ratio: number, 
/**
 * Calls since the daemon started.
 */
calls_total: number, };
