// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tool.ended`: a call's result was written.
 */
export type ToolEnded = { session_id: string, turn_id: string, tool_use_id: string, tool: string, 
/**
 * The result's status: `ok`, `error`, `declined`, `cancelled`,
 * `background`, … (`denied` from a daemon before theseus-8az).
 */
status: string, duration_ms: number | null, correlation_id: string | null, 
/**
 * A background job's real result, after its placeholder.
 */
late: boolean, truncated: boolean, 
/**
 * The whole output's size, before any cap.
 */
bytes: number, node_id: string, 
/**
 * A job's exit code.
 */
exit_code: number | null, 
/**
 * Who stopped it, when a `/stop` ended it (theseus-4uw).
 */
stopped_by: string | null, 
/**
 * The result's first 2,000 characters.
 */
preview: string, 
/**
 * An L1 job's scratch (M4 17b): what it wrote there, which was
 * discarded (`wrote 3 files, 41 KB, to scratch: target/…; discarded`).
 */
scratch?: string, };
