// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";

export type TurnSubmitParams = { 
/**
 * Omit to open a fresh conversation session for this turn.
 */
session_id: string | null, input: string, 
/**
 * Profile for this turn (a configured profile name); default is the live profile.
 */
profile: string | null, 
/**
 * Raw override of the profile's provider for this turn.
 */
provider: string | null, 
/**
 * Raw override of the profile's model for this turn.
 */
model: string | null, 
/**
 * Who wrote the input, as a label on the message node (e.g. `discord:eddie`).
 * Default: the connection's own label. A label, not an authority: every
 * local protocol client acts as the operator.
 */
author?: string, 
/**
 * Files that came with the input, in order (theseus-9g2). With any, the
 * input may be empty.
 */
attachments?: Array<Attachment>, 
/**
 * The surface's message this turn answers (a Discord message id): the
 * reply's first message is posted as a reply to it (theseus-q4v).
 */
reply_to?: string, 
/**
 * The session whose job sent this turn (theseus-b5cl), as
 * `SessionOpenParams::opened_from` says: the turn's session, the one it
 * opens or the one it names, takes that session's hold of external
 * text.
 */
opened_from?: string, };
