// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A notification's params: a field it lacks reads as its default, as the
 * renderers always read them (theseus-0g4).
 */
export type TurnFailed = { session_id: string, turn_id: string | null, execution_id: string | null, continuation: boolean, 
/**
 * Error class when known (rate_limited, overloaded, auth, ...).
 */
class: string | null, error: string, 
/**
 * What the execution does next (theseus-ljr): `backoff` (the driver
 * retries while the class lasts), `retry` (once), or `park` (it waits
 * on input, and the next message retries). Absent for a task's turn and
 * a stopped one.
 */
then?: string, };
