// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a waiting execution waits on: the kernel's wake, typed (spec §3.15).
 * The tag is `on`, as the kernel stores it.
 */
export type WaitingOn = { "on": "due_at", at_ms: number, } | { "on": "actions", correlation_ids: Array<string>, } | { "on": "execution", execution_id: string, } | { "on": "confirm", confirm_id: string, } | { "on": "input" } | { "on": "budget", correlation_id: string, } | { "on": "unknown" };
