// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pending wake (DD8, theseus-cff): a conversation asked, with `wake.at`,
 * for a turn at a time, whose input is its note. It has not run yet.
 */
export type WakeInfo = { 
/**
 * `wak_…`.
 */
wake_id: string, 
/**
 * The last six characters of its id, which is how people name it
 * (`/cancel a1b2c3`).
 */
short: string, session_id: string, execution_id: string, 
/**
 * The session's title, when it has one.
 */
session_title?: string, 
/**
 * The task that set it, by its short id (`a1b2c3`), when its session is a task (37b).
 */
task?: string, due_at_ms: number, 
/**
 * The due time on the daemon's clock, as people read it
 * (`2026-09-30 13:15:00 -07:00`).
 */
due_local: string, note: string, set_at_ms: number, 
/**
 * The place it was set from (`discord:dm:<user>`), where its turn's
 * reply goes, if anywhere.
 */
target?: string, 
/**
 * Its session's execution state now: a wake waits for a busy session.
 */
state: string, 
/**
 * A repeating wake's span (`1d`, `30m`; 37a); none for a one-shot wake.
 */
every?: string, 
/**
 * Which occurrence of its series is due next, from 1.
 */
occurrence?: number, 
/**
 * When a series' next occurrence is due, as people read it on the
 * daemon's clock (`21:00 Thu`).
 */
next?: string, };
