// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operator's warrant for a graduated node (M4 19c, §2.7): graduation is
 * the only way an audience widens, and it is a new node, never a relabel.
 * The node keeps its source's integrity; only its readers are wider.
 */
export type Warrant = { 
/**
 * The node it was graduated from, which keeps its own label.
 */
graduated_from: string, 
/**
 * Who graduated it: a label, or a Discord user by id.
 */
who: string, 
/**
 * The surface it came through: `cli`, `web`, `discord:dm`.
 */
how: string, 
/**
 * Why, in the operator's words.
 */
why: string, at_ms: number, };
