// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node a compile left out, and why (the manifest's `withheld`).
 */
export type Withheld = { node_id: string, 
/**
 * The node's readers, in words (`owner-only`).
 */
reason: string, };
