//! The tables that settle what the models do not say (AWS design §3.1 and
//! appendix E: botocore has `readonly` on only some services, so the HTTP
//! method and the name carry most of the reads, and these tables are the
//! authority for the rest).
//!
//! Services are botocore's names. Operation names may hold `*` globs. A test
//! checks every row against the embedded catalog: the service exists, and
//! each pattern matches at least one operation.

use crate::classify::{Class, RetryClass, SecretBearing};

pub(crate) struct Ops {
    pub(crate) service: &'static str,
    pub(crate) ops: &'static [&'static str],
}

const fn ops(service: &'static str, ops: &'static [&'static str]) -> Ops {
    Ops { service, ops }
}

/// An override of what the rules would say.
pub(crate) struct ClassRow {
    pub(crate) service: &'static str,
    pub(crate) op: &'static str,
    pub(crate) class: Option<Class>,
    pub(crate) cost: Option<bool>,
    pub(crate) inert: bool,
    pub(crate) note: &'static str,
}

const fn class(
    service: &'static str,
    op: &'static str,
    class: Class,
    note: &'static str,
) -> ClassRow {
    ClassRow {
        service,
        op,
        class: Some(class),
        cost: None,
        inert: false,
        note,
    }
}

const fn paid(
    service: &'static str,
    op: &'static str,
    class: Class,
    note: &'static str,
) -> ClassRow {
    ClassRow {
        service,
        op,
        class: Some(class),
        cost: Some(true),
        inert: false,
        note,
    }
}

const MINT: &str = "mints a credential, whatever its name says";
const CRYPTO: &str = "a cryptographic operation with a key; it changes nothing";
const ANALYSIS: &str = "an analysis of the input; it changes nothing, and is charged per call";

/// Read verbs (§3.1). A name that starts with one, as a whole word, is a read.
pub(crate) static READ_PREFIXES: &[&str] = &[
    "Describe", "List", "Get", "Head", "Lookup", "Search", "Query", "Scan", "BatchGet", "Simulate",
    "Validate", "Estimate",
];

pub(crate) static CLASS: &[ClassRow] = &[
    class(
        "sqs",
        "ReceiveMessage",
        Class::Write,
        "hides the messages it returns from other consumers",
    ),
    class("sts", "AssumeRole*", Class::Write, MINT),
    class("sts", "AssumeRoot", Class::Write, MINT),
    class("sts", "GetSessionToken", Class::Write, MINT),
    class("sts", "GetFederationToken", Class::Write, MINT),
    class(
        "sts",
        "DecodeAuthorizationMessage",
        Class::Read,
        "decodes a denial's message; it changes nothing",
    ),
    class("sso", "GetRoleCredentials", Class::Write, MINT),
    class(
        "cognito-identity",
        "GetId",
        Class::Write,
        "creates an identity",
    ),
    class(
        "cognito-identity",
        "GetCredentialsForIdentity",
        Class::Write,
        MINT,
    ),
    class("cognito-identity", "GetOpenIdToken*", Class::Write, MINT),
    class("redshift", "GetClusterCredentials*", Class::Write, MINT),
    class("redshift-serverless", "GetCredentials", Class::Write, MINT),
    class(
        "lakeformation",
        "GetTemporaryGlue*Credentials",
        Class::Write,
        MINT,
    ),
    class("ecr", "GetAuthorizationToken", Class::Write, MINT),
    class("ecr-public", "GetAuthorizationToken", Class::Write, MINT),
    class("codeartifact", "GetAuthorizationToken", Class::Write, MINT),
    paid(
        "athena",
        "StartQueryExecution",
        Class::Write,
        "writes its results to S3, and is charged per TB scanned",
    ),
    ClassRow {
        service: "cloudformation",
        op: "CreateChangeSet",
        class: Some(Class::Write),
        cost: None,
        inert: true,
        note: "changes nothing until it is executed",
    },
    class("kms", "Decrypt", Class::Read, CRYPTO),
    class("kms", "Encrypt", Class::Read, CRYPTO),
    class("kms", "ReEncrypt", Class::Read, CRYPTO),
    class("kms", "GenerateDataKey*", Class::Read, CRYPTO),
    class("kms", "GenerateRandom", Class::Read, CRYPTO),
    class("kms", "GenerateMac", Class::Read, CRYPTO),
    class("kms", "VerifyMac", Class::Read, CRYPTO),
    class("kms", "Sign", Class::Read, CRYPTO),
    class("kms", "Verify", Class::Read, CRYPTO),
    class("kms", "DeriveSharedSecret", Class::Read, CRYPTO),
    class("logs", "FilterLogEvents", Class::Read, "reads log events"),
    paid(
        "logs",
        "StartQuery",
        Class::Read,
        "a Logs Insights query; charged per GB scanned",
    ),
    paid(
        "s3",
        "SelectObjectContent",
        Class::Read,
        "S3 Select; charged per GB scanned",
    ),
    class("dynamodb", "TransactGetItems", Class::Read, "reads items"),
    paid("rekognition", "Detect*", Class::Read, ANALYSIS),
    paid("rekognition", "RecognizeCelebrities", Class::Read, ANALYSIS),
    paid("rekognition", "CompareFaces", Class::Read, ANALYSIS),
    paid("textract", "Analyze*", Class::Read, ANALYSIS),
    paid("textract", "DetectDocumentText", Class::Read, ANALYSIS),
    paid("comprehend", "Detect*", Class::Read, ANALYSIS),
    paid("comprehend", "BatchDetect*", Class::Read, ANALYSIS),
    paid("comprehend", "ClassifyDocument", Class::Read, ANALYSIS),
    paid("comprehend", "ContainsPiiEntities", Class::Read, ANALYSIS),
    paid("translate", "TranslateText", Class::Read, ANALYSIS),
    paid("translate", "TranslateDocument", Class::Read, ANALYSIS),
    paid("polly", "SynthesizeSpeech", Class::Read, ANALYSIS),
];

/// Operations that start code of the caller's choosing (§3.1's short list).
pub(crate) static RUN: &[Ops] = &[
    ops(
        "lambda",
        &["Invoke", "InvokeAsync", "InvokeWithResponseStream"],
    ),
    ops("ecs", &["RunTask", "StartTask", "ExecuteCommand"]),
    ops("batch", &["SubmitJob"]),
    ops(
        "ssm",
        &[
            "SendCommand",
            "StartAutomationExecution",
            "StartSession",
            "StartChangeRequestExecution",
        ],
    ),
    ops(
        "codebuild",
        &[
            "StartBuild",
            "StartBuildBatch",
            "RetryBuild",
            "RetryBuildBatch",
        ],
    ),
    ops(
        "stepfunctions",
        &["StartExecution", "StartSyncExecution", "RedriveExecution"],
    ),
    ops(
        "sagemaker",
        &[
            "CreateTrainingJob",
            "CreateProcessingJob",
            "CreateTransformJob",
            "CreateHyperParameterTuningJob",
            "CreateAutoMLJob",
            "CreateAutoMLJobV2",
            "CreateCompilationJob",
            "CreateEdgePackagingJob",
            "CreateInferenceRecommendationsJob",
            "CreateLabelingJob",
            "CreateOptimizationJob",
            "StartPipelineExecution",
        ],
    ),
    ops(
        "sagemaker-runtime",
        &[
            "InvokeEndpoint",
            "InvokeEndpointAsync",
            "InvokeEndpointWithResponseStream",
        ],
    ),
    ops(
        "bedrock-runtime",
        &[
            "InvokeModel",
            "InvokeModelWithResponseStream",
            "Converse",
            "ConverseStream",
            "StartAsyncInvoke",
        ],
    ),
    ops(
        "bedrock-agent-runtime",
        &[
            "InvokeAgent",
            "InvokeFlow",
            "InvokeInlineAgent",
            "RetrieveAndGenerate",
            "RetrieveAndGenerateStream",
        ],
    ),
    ops(
        "bedrock",
        &[
            "CreateModelCustomizationJob",
            "CreateModelInvocationJob",
            "CreateEvaluationJob",
        ],
    ),
    ops("glue", &["StartJobRun", "StartWorkflowRun"]),
    ops("emr", &["RunJobFlow", "AddJobFlowSteps"]),
    ops("emr-serverless", &["StartJobRun"]),
    ops("emr-containers", &["StartJobRun"]),
    ops("codepipeline", &["StartPipelineExecution"]),
    ops("apigateway", &["TestInvokeMethod", "TestInvokeAuthorizer"]),
    ops("kinesisanalyticsv2", &["StartApplication"]),
    ops("amplify", &["StartJob"]),
    ops("cloudfront", &["TestFunction"]),
];

/// Runs that cost nothing in themselves (SSM's commands run on hosts that
/// are already paid for; §4's table has `SendCommand` as Run without `$`).
pub(crate) static FREE_RUN: &[Ops] = &[
    ops(
        "ssm",
        &[
            "SendCommand",
            "StartAutomationExecution",
            "StartSession",
            "StartChangeRequestExecution",
        ],
    ),
    ops("cloudfront", &["TestFunction"]),
];

/// Cost-bearing beyond the Run operations: creations and starts of metered
/// resources, and operations charged per request or per byte scanned.
pub(crate) static COST: &[Ops] = &[
    ops("ce", &["*"]),
    ops(
        "athena",
        &[
            "StartQueryExecution",
            "StartSession",
            "StartCalculationExecution",
        ],
    ),
    ops("logs", &["StartQuery"]),
    ops("s3", &["SelectObjectContent", "RestoreObject"]),
    ops("glacier", &["InitiateJob"]),
    ops(
        "ec2",
        &[
            "RunInstances",
            "StartInstances",
            "CreateNatGateway",
            "AllocateAddress",
            "CreateVolume",
            "CreateVpcEndpoint",
            "CreateTransitGateway",
            "CreateTransitGatewayVpcAttachment",
            "CreateVpnConnection",
            "CreateClientVpnEndpoint",
            "RequestSpotInstances",
            "RequestSpotFleet",
            "CreateFleet",
            "PurchaseReservedInstancesOffering",
            "PurchaseScheduledInstances",
            "PurchaseHostReservation",
            "PurchaseCapacityBlock",
            "CreateCapacityReservation",
            "CreateCapacityReservationFleet",
            "AllocateHosts",
            "CreateSnapshot",
            "CreateSnapshots",
            "CopySnapshot",
            "CreateImage",
            "CopyImage",
            "CreateTrafficMirrorSession",
            "CreateVerifiedAccessEndpoint",
        ],
    ),
    ops(
        "rds",
        &[
            "CreateDBInstance",
            "CreateDBCluster",
            "CreateDBInstanceReadReplica",
            "StartDBInstance",
            "StartDBCluster",
            "RestoreDB*",
            "CreateDBProxy",
            "CreateDBSnapshot",
            "CreateDBClusterSnapshot",
            "CopyDBSnapshot",
            "CopyDBClusterSnapshot",
            "CreateBlueGreenDeployment",
            "PurchaseReservedDBInstancesOffering",
        ],
    ),
    ops(
        "elasticache",
        &[
            "CreateCacheCluster",
            "CreateReplicationGroup",
            "CreateServerlessCache",
            "PurchaseReservedCacheNodesOffering",
        ],
    ),
    ops(
        "redshift",
        &[
            "CreateCluster",
            "ResumeCluster",
            "RestoreFromClusterSnapshot",
            "PurchaseReservedNodeOffering",
        ],
    ),
    ops("redshift-serverless", &["CreateWorkgroup"]),
    ops("opensearch", &["CreateDomain"]),
    ops("es", &["CreateElasticsearchDomain"]),
    ops(
        "sagemaker",
        &[
            "CreateEndpoint",
            "UpdateEndpoint",
            "CreateNotebookInstance",
            "StartNotebookInstance",
            "CreateApp",
            "CreateInferenceComponent",
            "CreateCluster",
        ],
    ),
    ops("elbv2", &["CreateLoadBalancer"]),
    ops("elb", &["CreateLoadBalancer"]),
    ops(
        "eks",
        &["CreateCluster", "CreateNodegroup", "CreateFargateProfile"],
    ),
    ops("ecs", &["CreateService"]),
    ops(
        "dynamodb",
        &[
            "CreateTable",
            "RestoreTableFromBackup",
            "RestoreTableToPointInTime",
            "ImportTable",
            "ExportTableToPointInTime",
            "CreateBackup",
        ],
    ),
    ops("kinesis", &["CreateStream"]),
    ops("kafka", &["CreateCluster", "CreateClusterV2"]),
    ops("mq", &["CreateBroker"]),
    ops("efs", &["CreateFileSystem"]),
    ops("fsx", &["CreateFileSystem", "CreateFileSystemFromBackup"]),
    ops("kms", &["CreateKey", "ReplicateKey"]),
    ops("secretsmanager", &["CreateSecret"]),
    ops("route53", &["CreateHostedZone", "CreateHealthCheck"]),
    ops(
        "route53domains",
        &["RegisterDomain", "TransferDomain", "RenewDomain"],
    ),
    ops(
        "cloudwatch",
        &["PutMetricAlarm", "PutCompositeAlarm", "PutDashboard"],
    ),
    ops("globalaccelerator", &["CreateAccelerator"]),
    ops(
        "lightsail",
        &[
            "CreateInstances",
            "CreateRelationalDatabase",
            "CreateLoadBalancer",
            "CreateDistribution",
        ],
    ),
    ops("apprunner", &["CreateService"]),
    ops("memorydb", &["CreateCluster"]),
    ops("neptune", &["CreateDBInstance", "CreateDBCluster"]),
    ops("docdb", &["CreateDBInstance", "CreateDBCluster"]),
    ops("lambda", &["PutProvisionedConcurrencyConfig"]),
    ops("bedrock", &["CreateProvisionedModelThroughput"]),
    ops("workspaces", &["CreateWorkspaces"]),
    ops("appstream", &["CreateFleet", "StartFleet"]),
    ops("glue", &["CreateDevEndpoint", "StartCrawler"]),
    ops(
        "cloudfront",
        &["CreateDistribution", "CreateDistributionWithTags"],
    ),
    ops("transfer", &["CreateServer"]),
    ops("directconnect", &["CreateConnection"]),
    ops(
        "dms",
        &["CreateReplicationInstance", "StartReplicationTask"],
    ),
    ops("datasync", &["StartTaskExecution"]),
    ops(
        "backup",
        &["StartBackupJob", "StartRestoreJob", "StartCopyJob"],
    ),
    ops(
        "rekognition",
        &[
            "Detect*",
            "RecognizeCelebrities",
            "CompareFaces",
            "SearchFaces",
            "SearchFacesByImage",
            "IndexFaces",
            "Start*",
        ],
    ),
    ops("textract", &["Analyze*", "DetectDocumentText", "Start*"]),
    ops(
        "comprehend",
        &[
            "Detect*",
            "BatchDetect*",
            "ClassifyDocument",
            "ContainsPiiEntities",
            "Start*Job",
        ],
    ),
    ops(
        "translate",
        &[
            "TranslateText",
            "TranslateDocument",
            "StartTextTranslationJob",
        ],
    ),
    ops("polly", &["SynthesizeSpeech", "StartSpeechSynthesisTask"]),
    ops(
        "transcribe",
        &[
            "StartTranscriptionJob",
            "StartMedicalTranscriptionJob",
            "StartCallAnalyticsJob",
        ],
    ),
];

pub(crate) struct SecretRow {
    pub(crate) service: &'static str,
    pub(crate) op: &'static str,
    pub(crate) secret: SecretBearing,
}

const fn secret(service: &'static str, op: &'static str) -> SecretRow {
    SecretRow {
        service,
        op,
        secret: SecretBearing::Always,
    }
}

const fn secret_when(service: &'static str, op: &'static str, member: &'static str) -> SecretRow {
    SecretRow {
        service,
        op,
        secret: SecretBearing::WhenInputTrue(member),
    }
}

/// Results that hold credentials or secret values (§3.1, §3.5): the value
/// goes onto the secrets board, and the model sees a handle.
pub(crate) static SECRET: &[SecretRow] = &[
    secret("secretsmanager", "GetSecretValue"),
    secret("secretsmanager", "BatchGetSecretValue"),
    secret("secretsmanager", "GetRandomPassword"),
    secret_when("ssm", "GetParameter", "WithDecryption"),
    secret_when("ssm", "GetParameters", "WithDecryption"),
    secret_when("ssm", "GetParametersByPath", "WithDecryption"),
    secret_when("ssm", "GetParameterHistory", "WithDecryption"),
    secret("kms", "Decrypt"),
    secret("kms", "GenerateDataKey"),
    secret("kms", "GenerateDataKeyPair"),
    secret("kms", "GenerateRandom"),
    secret("kms", "DeriveSharedSecret"),
    secret("sts", "AssumeRole*"),
    secret("sts", "AssumeRoot"),
    secret("sts", "GetSessionToken"),
    secret("sts", "GetFederationToken"),
    secret("ecr", "GetAuthorizationToken"),
    secret("ecr-public", "GetAuthorizationToken"),
    secret("codeartifact", "GetAuthorizationToken"),
    secret("iam", "CreateAccessKey"),
    secret("iam", "CreateServiceSpecificCredential"),
    secret("iam", "ResetServiceSpecificCredential"),
    secret("sso", "GetRoleCredentials"),
    secret("sso-oidc", "CreateToken*"),
    secret("cognito-identity", "GetCredentialsForIdentity"),
    secret("cognito-identity", "GetOpenIdToken*"),
    secret("cognito-idp", "InitiateAuth"),
    secret("cognito-idp", "AdminInitiateAuth"),
    secret("cognito-idp", "RespondToAuthChallenge"),
    secret("cognito-idp", "AdminRespondToAuthChallenge"),
    secret("cognito-idp", "GetTokensFromRefreshToken"),
    secret("redshift", "GetClusterCredentials*"),
    secret("redshift-serverless", "GetCredentials"),
    secret("lakeformation", "GetTemporaryGlue*Credentials"),
    secret("lightsail", "GetInstanceAccessDetails"),
    secret("lightsail", "DownloadDefaultKeyPair"),
    secret("lightsail", "CreateKeyPair"),
    secret("lightsail", "GetRelationalDatabaseMasterUserPassword"),
    secret("lightsail", "CreateBucketAccessKey"),
    secret("ec2", "CreateKeyPair"),
    secret("ec2", "GetPasswordData"),
    secret("iot", "CreateKeysAndCertificate"),
    secret("iot", "CreateProvisioningClaim"),
    secret("acm", "ExportCertificate"),
    secret("apigateway", "CreateApiKey"),
    secret_when("apigateway", "GetApiKey", "includeValue"),
    secret_when("apigateway", "GetApiKeys", "includeValues"),
    secret("appsync", "CreateApiKey"),
    secret("appsync", "ListApiKeys"),
];

/// Tagging is direct (§3.4), so it is never IaC-only.
pub(crate) static TAGGING: &[&str] = &[
    "Tag*",
    "Untag*",
    "*Tags",
    "*Tagging",
    "AddTags*",
    "RemoveTags*",
    "*TagResource",
    "*TagsToResource",
    "*TagsFromResource",
];

/// Operations on what exists are direct (§3.4: start, stop, scale, redeploy,
/// invalidate, rotate), whatever their noun.
pub(crate) static NOT_IAC_PREFIXES: &[&str] = &[
    "Start",
    "Stop",
    "Reboot",
    "Test",
    "Failover",
    "Copy",
    "Cancel",
    "Pause",
    "Resume",
    "Rotate",
    "Invalidate",
];

/// Exceptions to [`IAC`] by name.
pub(crate) static NOT_IAC: &[Ops] = &[
    ops("cloudfront", &["*Invalidation*"]),
    ops("budgets", &["ExecuteBudgetAction"]),
];

/// Durable infrastructure, made and changed only through a stack (§3.4's
/// table): networks, buckets, tables, queues, topics, streams, log groups,
/// functions, clusters, services, instances, IAM, KMS keys, load balancers,
/// APIs, distributions, DNS, certificates, alarms, rules, schedules, and
/// budgets. Only writes are IaC-only; a pattern that also matches a read or
/// a run is harmless.
pub(crate) static IAC: &[Ops] = &[
    ops(
        "ec2",
        &[
            "RunInstances",
            "RequestSpotInstances",
            "RequestSpotFleet",
            "ModifySpotFleetRequest",
            "CreateFleet",
            "DeleteFleets",
            "ModifyFleet",
            "ModifyInstanceAttribute",
            "ModifyInstancePlacement",
            "ModifyInstanceMetadataOptions",
            "*Vpc*",
            "*Subnet*",
            "*InternetGateway*",
            "*NatGateway*",
            "*CarrierGateway*",
            "*SecurityGroup*",
            "*Route*",
            "*NetworkAcl*",
            "*TransitGateway*",
            "*VpnGateway*",
            "*VpnConnection*",
            "*CustomerGateway*",
            "*DhcpOptions*",
            "*LaunchTemplate*",
            "*PlacementGroup*",
            "*FlowLogs*",
            "*Address*",
            "*NetworkInterface*",
            "*KeyPair*",
            "*ClientVpn*",
            "*ManagedPrefixList*",
            "*Ipam*",
            "*Volume*",
            "*CapacityReservation*",
            "AllocateHosts",
            "ReleaseHosts",
            "ModifyHosts",
            "*VerifiedAccess*",
            "*TrafficMirror*",
            "*InstanceConnectEndpoint*",
        ],
    ),
    ops(
        "s3",
        &[
            "CreateBucket",
            "DeleteBucket",
            "PutBucket*",
            "DeleteBucket*",
            "*PublicAccessBlock",
            "PutObjectLockConfiguration",
        ],
    ),
    ops(
        "s3control",
        &[
            "*PublicAccessBlock",
            "*AccessPoint*",
            "*StorageLensConfiguration",
            "*AccessGrantsInstance",
            "CreateBucket",
            "DeleteBucket",
        ],
    ),
    ops(
        "dynamodb",
        &[
            "CreateTable",
            "DeleteTable",
            "UpdateTable",
            "UpdateTableReplicaAutoScaling",
            "*GlobalTable*",
            "UpdateTimeToLive",
            "UpdateContinuousBackups",
            "*KinesisStreamingDestination",
            "UpdateContributorInsights",
            "*ResourcePolicy",
            "RestoreTableFromBackup",
            "RestoreTableToPointInTime",
            "ImportTable",
        ],
    ),
    ops(
        "sqs",
        &[
            "CreateQueue",
            "DeleteQueue",
            "SetQueueAttributes",
            "AddPermission",
            "RemovePermission",
        ],
    ),
    ops(
        "sns",
        &[
            "CreateTopic",
            "DeleteTopic",
            "SetTopicAttributes",
            "Subscribe",
            "Unsubscribe",
            "SetSubscriptionAttributes",
            "AddPermission",
            "RemovePermission",
            "*PlatformApplication*",
            "PutDataProtectionPolicy",
        ],
    ),
    ops(
        "kinesis",
        &[
            "CreateStream",
            "DeleteStream",
            "*StreamConsumer",
            "*ResourcePolicy",
        ],
    ),
    ops(
        "logs",
        &[
            "CreateLogGroup",
            "DeleteLogGroup",
            "PutRetentionPolicy",
            "DeleteRetentionPolicy",
            "*SubscriptionFilter",
            "*MetricFilter",
            "*ResourcePolicy",
            "PutDestination*",
            "DeleteDestination",
            "*DataProtectionPolicy",
            "*AccountPolicy",
            "AssociateKmsKey",
            "DisassociateKmsKey",
            "*DeliveryDestination*",
            "*DeliverySource",
            "CreateDelivery",
            "DeleteDelivery",
            "*LogAnomalyDetector",
            "*Transformer",
            "*IndexPolicy",
        ],
    ),
    ops(
        "lambda",
        &[
            "CreateFunction",
            "DeleteFunction",
            "UpdateFunctionConfiguration",
            "*FunctionUrlConfig",
            "*EventSourceMapping",
            "AddPermission",
            "RemovePermission",
            "*LayerVersionPermission",
            "*FunctionEventInvokeConfig",
            "*CodeSigningConfig",
            "PutRuntimeManagementConfig",
        ],
    ),
    ops(
        "ecs",
        &[
            "CreateCluster",
            "DeleteCluster",
            "UpdateCluster",
            "UpdateClusterSettings",
            "PutClusterCapacityProviders",
            "CreateService",
            "DeleteService",
            "*CapacityProvider",
        ],
    ),
    ops(
        "eks",
        &[
            "CreateCluster",
            "DeleteCluster",
            "UpdateClusterConfig",
            "UpdateClusterVersion",
            "*Nodegroup*",
            "*FargateProfile",
            "*Addon",
            "*AccessEntry",
            "*AccessPolicy",
            "*IdentityProviderConfig",
            "*PodIdentityAssociation",
            "RegisterCluster",
            "DeregisterCluster",
            "AssociateEncryptionConfig",
        ],
    ),
    ops(
        "rds",
        &[
            "CreateDBInstance",
            "DeleteDBInstance",
            "ModifyDBInstance",
            "CreateDBCluster",
            "DeleteDBCluster",
            "ModifyDBCluster",
            "*DBSubnetGroup",
            "*DBParameterGroup",
            "*DBClusterParameterGroup",
            "*OptionGroup",
            "*DBProxy*",
            "*DBSecurityGroup*",
            "CreateDBInstanceReadReplica",
            "RestoreDB*",
            "*GlobalCluster",
            "*EventSubscription",
            "*DBClusterEndpoint",
            "*CustomDBEngineVersion",
            "*BlueGreenDeployment",
            "*Integration",
            "*DBShardGroup",
            "AddRoleTo*",
            "RemoveRoleFrom*",
        ],
    ),
    ops(
        "docdb",
        &[
            "CreateDBInstance",
            "DeleteDBInstance",
            "ModifyDBInstance",
            "CreateDBCluster",
            "DeleteDBCluster",
            "ModifyDBCluster",
            "*DBSubnetGroup",
            "*DBClusterParameterGroup",
            "RestoreDB*",
            "*GlobalCluster",
        ],
    ),
    ops(
        "neptune",
        &[
            "CreateDBInstance",
            "DeleteDBInstance",
            "ModifyDBInstance",
            "CreateDBCluster",
            "DeleteDBCluster",
            "ModifyDBCluster",
            "*DBSubnetGroup",
            "*DBClusterParameterGroup",
            "*DBParameterGroup",
            "RestoreDB*",
        ],
    ),
    ops(
        "elasticache",
        &[
            "*CacheCluster",
            "*ReplicationGroup*",
            "*CacheSubnetGroup",
            "*CacheParameterGroup",
            "*CacheSecurityGroup*",
            "*ServerlessCache",
            "*GlobalReplicationGroup",
            "CreateUser",
            "DeleteUser",
            "ModifyUser",
            "*UserGroup",
        ],
    ),
    ops(
        "redshift",
        &[
            "CreateCluster",
            "DeleteCluster",
            "ModifyCluster",
            "*ClusterSubnetGroup",
            "*ClusterParameterGroup",
            "*ClusterSecurityGroup*",
            "RestoreFromClusterSnapshot",
            "*EndpointAccess",
            "*UsageLimit",
            "*Integration",
            "*HsmClientCertificate",
            "*HsmConfiguration",
            "*EventSubscription",
            "ModifyClusterIamRoles",
        ],
    ),
    ops(
        "redshift-serverless",
        &["*Namespace", "*Workgroup", "*EndpointAccess", "*UsageLimit"],
    ),
    ops(
        "opensearch",
        &[
            "CreateDomain",
            "DeleteDomain",
            "UpdateDomainConfig",
            "*VpcEndpoint",
            "*OutboundConnection",
        ],
    ),
    ops(
        "es",
        &[
            "CreateElasticsearchDomain",
            "DeleteElasticsearchDomain",
            "UpdateElasticsearchDomainConfig",
        ],
    ),
    ops(
        "elbv2",
        &[
            "CreateLoadBalancer",
            "DeleteLoadBalancer",
            "ModifyLoadBalancerAttributes",
            "*Listener",
            "ModifyListenerAttributes",
            "*TargetGroup",
            "ModifyTargetGroupAttributes",
            "*Rule",
            "SetRulePriorities",
            "SetSecurityGroups",
            "SetSubnets",
            "SetIpAddressType",
            "*TrustStore",
            "AddListenerCertificates",
            "RemoveListenerCertificates",
        ],
    ),
    ops(
        "elb",
        &[
            "CreateLoadBalancer",
            "DeleteLoadBalancer",
            "CreateLoadBalancerListeners",
            "DeleteLoadBalancerListeners",
            "ModifyLoadBalancerAttributes",
            "ApplySecurityGroupsToLoadBalancer",
        ],
    ),
    ops(
        "sagemaker",
        &[
            "CreateEndpoint",
            "DeleteEndpoint",
            "CreateEndpointConfig",
            "DeleteEndpointConfig",
            "CreateNotebookInstance",
            "DeleteNotebookInstance",
            "UpdateNotebookInstance",
            "*NotebookInstanceLifecycleConfig",
            "CreateDomain",
            "DeleteDomain",
            "UpdateDomain",
            "*UserProfile",
            "*Space",
            "CreateModel",
            "DeleteModel",
            "*InferenceComponent",
            "CreateCluster",
            "DeleteCluster",
            "UpdateCluster",
        ],
    ),
    ops(
        "efs",
        &[
            "CreateFileSystem",
            "DeleteFileSystem",
            "UpdateFileSystem",
            "*MountTarget*",
            "*FileSystemPolicy",
            "*AccessPoint",
            "PutLifecycleConfiguration",
            "*ReplicationConfiguration",
            "PutBackupPolicy",
            "UpdateFileSystemProtection",
        ],
    ),
    ops(
        "fsx",
        &[
            "CreateFileSystem*",
            "DeleteFileSystem",
            "UpdateFileSystem",
            "*StorageVirtualMachine",
            "*Volume*",
            "*DataRepositoryAssociation",
            "*FileCache",
        ],
    ),
    ops(
        "autoscaling",
        &[
            "CreateAutoScalingGroup",
            "DeleteAutoScalingGroup",
            "UpdateAutoScalingGroup",
            "*LaunchConfiguration",
            "PutScalingPolicy",
            "DeletePolicy",
            "PutScheduledUpdateGroupAction",
            "BatchPutScheduledUpdateGroupAction",
            "DeleteScheduledAction",
            "BatchDeleteScheduledAction",
            "PutLifecycleHook",
            "DeleteLifecycleHook",
            "PutNotificationConfiguration",
            "DeleteNotificationConfiguration",
            "*WarmPool",
            "AttachLoadBalancer*",
            "DetachLoadBalancer*",
            "AttachTrafficSources",
            "DetachTrafficSources",
        ],
    ),
    ops(
        "application-autoscaling",
        &[
            "RegisterScalableTarget",
            "DeregisterScalableTarget",
            "PutScalingPolicy",
            "DeleteScalingPolicy",
            "PutScheduledAction",
            "DeleteScheduledAction",
        ],
    ),
    ops(
        "stepfunctions",
        &[
            "CreateStateMachine",
            "DeleteStateMachine",
            "UpdateStateMachine",
            "*StateMachineAlias",
            "CreateActivity",
            "DeleteActivity",
        ],
    ),
    ops(
        "codebuild",
        &[
            "CreateProject",
            "DeleteProject",
            "UpdateProject",
            "*Webhook",
            "*ReportGroup",
            "*SourceCredentials",
            "*Fleet",
        ],
    ),
    ops(
        "codepipeline",
        &[
            "CreatePipeline",
            "DeletePipeline",
            "UpdatePipeline",
            "*Webhook",
            "*CustomActionType",
        ],
    ),
    ops(
        "glue",
        &[
            "CreateJob",
            "DeleteJob",
            "UpdateJob",
            "*Crawler",
            "*Trigger",
            "*Connection",
            "*DevEndpoint",
            "CreateWorkflow",
            "DeleteWorkflow",
            "UpdateWorkflow",
            "*SecurityConfiguration",
            "*Registry",
            "*Blueprint",
            "*MLTransform",
        ],
    ),
    ops(
        "athena",
        &["*WorkGroup", "*DataCatalog", "*CapacityReservation"],
    ),
    ops(
        "secretsmanager",
        &[
            "PutResourcePolicy",
            "DeleteResourcePolicy",
            "ReplicateSecretToRegions",
            "RemoveRegionsFromReplication",
        ],
    ),
    ops(
        "ssm",
        &[
            "*MaintenanceWindow*",
            "*Association",
            "CreateAssociationBatch",
            "*PatchBaseline",
            "*ResourceDataSync",
            "*Activation",
        ],
    ),
    ops(
        "ecr",
        &[
            "CreateRepository",
            "DeleteRepository",
            "*RepositoryPolicy",
            "*LifecyclePolicy",
            "PutImageScanningConfiguration",
            "PutImageTagMutability",
            "*RegistryPolicy",
            "PutReplicationConfiguration",
            "*PullThroughCacheRule",
            "PutRegistryScanningConfiguration",
            "*RepositoryCreationTemplate",
        ],
    ),
    ops(
        "iam",
        &[
            "CreateRole",
            "DeleteRole",
            "UpdateRole",
            "UpdateRoleDescription",
            "UpdateAssumeRolePolicy",
            "*RolePolicy",
            "*RolePermissionsBoundary",
            "CreatePolicy",
            "DeletePolicy",
            "*PolicyVersion",
            "CreateUser",
            "DeleteUser",
            "UpdateUser",
            "*UserPolicy",
            "*UserPermissionsBoundary",
            "CreateGroup",
            "DeleteGroup",
            "UpdateGroup",
            "AddUserToGroup",
            "RemoveUserFromGroup",
            "*GroupPolicy",
            "*InstanceProfile",
            "*OpenIDConnectProvider*",
            "*SAMLProvider",
            "*AccessKey",
            "*LoginProfile",
            "*ServiceSpecificCredential",
            "*SSHPublicKey",
            "*ServerCertificate",
            "*SigningCertificate",
            "*VirtualMFADevice",
            "*AccountPasswordPolicy",
            "*AccountAlias",
        ],
    ),
    ops(
        "kms",
        &[
            "CreateKey",
            "ScheduleKeyDeletion",
            "PutKeyPolicy",
            "CreateAlias",
            "DeleteAlias",
            "UpdateAlias",
            "EnableKeyRotation",
            "DisableKeyRotation",
            "UpdateKeyDescription",
            "ReplicateKey",
            "UpdatePrimaryRegion",
            "*CustomKeyStore",
        ],
    ),
    ops(
        "apigateway",
        &[
            "CreateRestApi",
            "DeleteRestApi",
            "UpdateRestApi",
            "ImportRestApi",
            "PutRestApi",
            "*Resource",
            "*Method",
            "*Integration",
            "*IntegrationResponse",
            "*MethodResponse",
            "*Authorizer",
            "*DomainName",
            "*BasePathMapping",
            "*Stage",
            "*UsagePlan*",
            "*VpcLink",
            "*RequestValidator",
            "*Model",
            "*GatewayResponse",
        ],
    ),
    ops(
        "apigatewayv2",
        &[
            "CreateApi",
            "DeleteApi",
            "UpdateApi",
            "ImportApi",
            "ReimportApi",
            "*Route",
            "*RouteResponse",
            "*Integration",
            "*IntegrationResponse",
            "*Authorizer",
            "*DomainName",
            "*ApiMapping",
            "*Stage",
            "*VpcLink",
            "*Model",
            "*RouteSettings",
            "*CorsConfiguration",
            "*AccessLogSettings",
        ],
    ),
    ops(
        "cloudfront",
        &[
            "*Distribution*",
            "*OriginAccessControl",
            "*CloudFrontOriginAccessIdentity",
            "*CachePolicy",
            "*OriginRequestPolicy",
            "*ResponseHeadersPolicy",
            "CreateFunction",
            "UpdateFunction",
            "DeleteFunction",
            "PublishFunction",
            "*KeyGroup",
            "*PublicKey",
            "*FieldLevelEncryption*",
            "*RealtimeLogConfig",
            "*ContinuousDeploymentPolicy",
            "*KeyValueStore",
            "*VpcOrigin",
            "AssociateAlias",
        ],
    ),
    ops(
        "route53",
        &[
            "CreateHostedZone",
            "DeleteHostedZone",
            "UpdateHostedZoneComment",
            "ChangeResourceRecordSets",
            "*VPCWithHostedZone",
            "*HealthCheck",
            "*TrafficPolicy*",
            "*QueryLoggingConfig",
            "*ReusableDelegationSet",
            "*KeySigningKey",
            "*HostedZoneDNSSEC",
            "*VPCAssociationAuthorization",
            "*CidrCollection",
        ],
    ),
    ops(
        "acm",
        &[
            "RequestCertificate",
            "ImportCertificate",
            "DeleteCertificate",
            "UpdateCertificateOptions",
        ],
    ),
    ops(
        "cloudwatch",
        &[
            "PutMetricAlarm",
            "PutCompositeAlarm",
            "DeleteAlarms",
            "PutDashboard",
            "DeleteDashboards",
            "PutAnomalyDetector",
            "DeleteAnomalyDetector",
            "PutMetricStream",
            "DeleteMetricStream",
            "PutInsightRule",
            "DeleteInsightRules",
            "PutManagedInsightRules",
        ],
    ),
    ops(
        "events",
        &[
            "PutRule",
            "DeleteRule",
            "PutTargets",
            "RemoveTargets",
            "*EventBus",
            "PutPermission",
            "RemovePermission",
            "*Connection",
            "*ApiDestination",
            "*Archive",
            "*Endpoint",
        ],
    ),
    ops(
        "scheduler",
        &[
            "CreateSchedule",
            "UpdateSchedule",
            "DeleteSchedule",
            "CreateScheduleGroup",
            "DeleteScheduleGroup",
        ],
    ),
    ops(
        "budgets",
        &[
            "CreateBudget",
            "UpdateBudget",
            "DeleteBudget",
            "CreateBudgetAction",
            "UpdateBudgetAction",
            "DeleteBudgetAction",
            "*Notification",
            "*Subscriber",
        ],
    ),
    ops(
        "batch",
        &["*ComputeEnvironment", "*JobQueue", "*SchedulingPolicy"],
    ),
    ops(
        "cloudformation",
        &[
            "CreateStack",
            "UpdateStack",
            "DeleteStack",
            "ExecuteChangeSet",
            "*StackSet",
            "*StackInstances",
            "SetStackPolicy",
            "UpdateTerminationProtection",
        ],
    ),
    ops(
        "cloudtrail",
        &[
            "CreateTrail",
            "DeleteTrail",
            "UpdateTrail",
            "PutEventSelectors",
            "PutInsightSelectors",
            "*EventDataStore",
            "*Channel",
            "PutResourcePolicy",
            "DeleteResourcePolicy",
        ],
    ),
    ops(
        "config",
        &[
            "*ConfigurationRecorder",
            "*DeliveryChannel",
            "*ConfigRule",
            "*ConformancePack",
            "*ConfigurationAggregator",
            "*AggregationAuthorization",
            "PutRemediationConfigurations",
            "DeleteRemediationConfiguration",
        ],
    ),
    ops(
        "guardduty",
        &[
            "CreateDetector",
            "DeleteDetector",
            "UpdateDetector",
            "*Filter",
            "*IPSet",
            "*ThreatIntelSet",
            "*PublishingDestination",
            "*MalwareProtectionPlan",
        ],
    ),
    ops(
        "wafv2",
        &[
            "Create*",
            "Update*",
            "Delete*",
            "Associate*",
            "Disassociate*",
            "Put*",
        ],
    ),
    ops(
        "network-firewall",
        &[
            "Create*",
            "Update*",
            "Delete*",
            "Associate*",
            "Disassociate*",
            "Put*",
        ],
    ),
    ops("vpc-lattice", &["Create*", "Update*", "Delete*", "Put*"]),
    ops("globalaccelerator", &["Create*", "Update*", "Delete*"]),
    ops(
        "directconnect",
        &[
            "Create*",
            "Delete*",
            "Update*",
            "Allocate*",
            "Associate*",
            "Disassociate*",
        ],
    ),
    ops("transfer", &["Create*", "Update*", "Delete*"]),
    ops("opensearchserverless", &["Create*", "Update*", "Delete*"]),
    ops("memorydb", &["Create*", "Update*", "Delete*"]),
    ops("kafka", &["Create*", "Update*", "Delete*"]),
    ops("mq", &["Create*", "Update*", "Delete*"]),
    ops("dax", &["Create*", "Update*", "Delete*"]),
    ops(
        "elasticbeanstalk",
        &[
            "CreateEnvironment",
            "TerminateEnvironment",
            "UpdateEnvironment",
            "CreateApplication",
            "DeleteApplication",
            "UpdateApplication",
        ],
    ),
    ops(
        "cognito-idp",
        &[
            "CreateUserPool",
            "DeleteUserPool",
            "UpdateUserPool",
            "*UserPoolClient",
            "*UserPoolDomain",
            "*IdentityProvider",
            "*ResourceServer",
            "SetUserPoolMfaConfig",
        ],
    ),
    ops(
        "appsync",
        &[
            "CreateGraphqlApi",
            "DeleteGraphqlApi",
            "UpdateGraphqlApi",
            "CreateApi",
            "DeleteApi",
            "UpdateApi",
            "*DataSource",
            "*Resolver",
            "*DomainName",
        ],
    ),
    ops(
        "amplify",
        &[
            "CreateApp",
            "DeleteApp",
            "UpdateApp",
            "*Branch",
            "*DomainAssociation",
            "*Webhook",
            "*BackendEnvironment",
        ],
    ),
    ops(
        "apprunner",
        &[
            "CreateService",
            "DeleteService",
            "UpdateService",
            "*AutoScalingConfiguration",
            "*Connection",
            "*VpcConnector",
            "*VpcIngressConnection",
            "*ObservabilityConfiguration",
        ],
    ),
    ops(
        "lightsail",
        &[
            "Create*",
            "Delete*",
            "Update*",
            "Attach*",
            "Detach*",
            "Allocate*",
            "Release*",
            "OpenInstancePublicPorts",
            "PutInstancePublicPorts",
            "CloseInstancePublicPorts",
        ],
    ),
];

pub(crate) struct RetryRow {
    pub(crate) service: &'static str,
    pub(crate) op: &'static str,
    pub(crate) retry: RetryClass,
}

const fn retry(service: &'static str, op: &'static str, retry: RetryClass) -> RetryRow {
    RetryRow { service, op, retry }
}

/// Retry classes the traits do not give.
pub(crate) static RETRY: &[RetryRow] = &[
    // A repeat writes the same bytes to the same key, or deletes what is
    // already gone.
    retry("s3", "PutObject", RetryClass::SafeToRepeat),
    retry("s3", "CopyObject", RetryClass::SafeToRepeat),
    retry("s3", "DeleteObject", RetryClass::SafeToRepeat),
    retry("s3", "DeleteObjects", RetryClass::SafeToRepeat),
    // A repeat mints another short-lived credential; the first expires.
    retry("sts", "AssumeRole*", RetryClass::SafeToRepeat),
    retry("sts", "AssumeRoot", RetryClass::SafeToRepeat),
    retry("sts", "GetSessionToken", RetryClass::SafeToRepeat),
    retry("sts", "GetFederationToken", RetryClass::SafeToRepeat),
    retry("sso", "GetRoleCredentials", RetryClass::SafeToRepeat),
    retry("ecr", "GetAuthorizationToken", RetryClass::SafeToRepeat),
    // A repeat would receive, and hide, other messages.
    retry("sqs", "ReceiveMessage", RetryClass::NonRepeatable),
];
