// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionListParams = { 
/**
 * Only this execution's actions.
 */
execution_id: string | null, 
/**
 * Newest `n` (default 200).
 */
n: number | null, };
