// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

export type ActionConfirmParams = { correlation_id: string, approve: boolean, note: string | null, 
/**
 * Subscribe this connection to the session's events before the answer
 * wakes the execution, so the continuation turn is seen from its start.
 */
watch: boolean, 
/**
 * Who answered, as a label (e.g. `discord:eddie`). Default: the connection.
 * A label names; it proves nothing. With `[approval]`, the connection's
 * surface and `discord` decide whether the answer counts.
 */
author?: string, 
/**
 * Set by the Discord binding: the channel and user the answer came from.
 */
discord?: DiscordOrigin, 
/**
 * Approve, and trust the session again (theseus-9bp): it no longer holds
 * external text, so its calls that act go back to their postures. Only
 * with `approve`; the answer's judgment covers it.
 */
trust?: boolean, };
