// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The adjacency projection (M6 32b): built after serving, kept current at
 * each spread.
 */
export type AdjacencyHealth = { 
/**
 * `built`, `building`, `waiting` (to be built after serving or at the
 * first spread), or `failed`.
 */
state: string, why?: string, nodes: number, 
/**
 * Stored edges, each way counted.
 */
edges: number, entities: number, 
/**
 * EDGE records whose kind or route spreads nothing.
 */
unmapped: number, 
/**
 * An estimate of what it holds in memory.
 */
bytes: number, 
/**
 * The WAL position it holds everything through.
 */
through: number, };
