// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Style } from "./Style";

/**
 * One answer to a question.
 */
export type AnswerOption = { 
/**
 * `approve`, `approve_trust`, `decline`, `reset`, `accept`, `ack`, or
 * `choice:N`.
 */
id: string, label: string, style: Style, 
/**
 * The answer takes a note in words.
 */
takes_note: boolean, 
/**
 * What it does, in a phrase.
 */
effect: string, };
