// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asker } from "./Asker";

/**
 * `approval.refused`: an answer, an undo, or a trust from a Theseus job's
 * process, refused (theseus-6qy). A security event every connection hears.
 */
export type ApprovalRefused = { 
/**
 * The method of the act: `action.confirm`, `policy.tighten`,
 * `policy.untighten`, or `policy.trust`.
 */
act: string, 
/**
 * The session it was about; `null` for a tool's tightening.
 */
session_id: string | null, 
/**
 * An answer's call.
 */
correlation_id?: string, 
/**
 * The answer's call's tool, or the tightening's.
 */
tool?: string, 
/**
 * An answer's: approve or decline.
 */
approve?: boolean, 
/**
 * The connection it came through (`sock#9`), its surface (`cli`), why it
 * did not count, and the label it gave.
 */
who: string, via: string, why: string, by: string, asker?: Asker, 
/**
 * Always set: the asker was a job's.
 */
from_job: boolean, };
