// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One piece of an arrangement: a message of the parent's session, by
 * reference.
 */
export type ArrangementPiece = { 
/**
 * Its index in the call's `pieces`, from 0.
 */
index: number, 
/**
 * `objective`, `acceptance`, `design`, or `context`.
 */
role: string, 
/**
 * The node it quotes, and that node's session (the parent's).
 */
node_id: string, session_id: string, 
/**
 * Who wrote the node: `operator`, `agent`, `tool`, or `harness`, and
 * the client or principal that did, when known.
 */
origin: string, author?: string, at_ms: number, 
/**
 * The node's first line, for a list.
 */
first_line: string, 
/**
 * The call marked it trusted testimony.
 */
trusted?: boolean, 
/**
 * A later piece supersedes it: the child sees it by reference only.
 */
superseded_by?: number, };
