// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

/**
 * What an execution needs from people, and since when.
 */
export type Attention = { level: Level, 
/**
 * For people: `confirm proc.run: run cargo test`, `turn 4`, `ready`.
 */
label: string, 
/**
 * When the level last changed: within needs you, the longest waiting
 * comes first.
 */
since_ms: number, };
