// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwsBudgetStatus } from "./AwsBudgetStatus";
import type { AwsDurabilityStatus } from "./AwsDurabilityStatus";
import type { AwsGuardDutyStatus } from "./AwsGuardDutyStatus";
import type { AwsHandsStatus } from "./AwsHandsStatus";

/**
 * One AWS account: whether its key is bound, and its calls. The key is
 * bound once STS has named this account for it, after serving; until then,
 * and when that fails, no AWS call signs (it fails closed).
 */
export type AwsAccountStatus = { 
/**
 * The account's id.
 */
account: string, 
/**
 * The region a call goes to unless it names one.
 */
region: string, 
/**
 * The regions a call may name.
 */
regions: Array<string>, 
/**
 * `unchecked` (nothing has asked yet), `waiting` (for its key's
 * secrets), `checking`, `bound`, or `failed`.
 */
state: string, 
/**
 * Who the key is, as STS answered: `arn:aws:iam::…:user/…`.
 */
arn?: string, 
/**
 * When the check last ended.
 */
checked_at_unix_ms?: number, 
/**
 * Why it is not bound.
 */
error?: string, 
/**
 * AWS requests since the daemon started, the check's included, and how
 * many of them failed.
 */
calls: number, failed: number, 
/**
 * What signs its calls (AWS design §3.5): `its key` until the config
 * names the owner role the bootstrap made, then `role sessions
 * (theseus-owner)`, and the key signs only STS.
 */
signer?: string, 
/**
 * The month's budget, as AWS Budgets said at its last read (§3.7).
 */
budget?: AwsBudgetStatus, 
/**
 * GuardDuty's cost over its last 30 days, as its weekly read found.
 */
guardduty?: AwsGuardDutyStatus, 
/**
 * What the budget's reconcile did after serving (config to stack).
 */
reconcile?: string, 
/**
 * The durability tender (step 15), on this account when it ships.
 */
durability?: AwsDurabilityStatus, 
/**
 * Its hands, the hour's meter, and the reaper (step 40 part 2).
 */
hands?: AwsHandsStatus, };
