// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `aws.bootstrap`'s params: the plan of an account's foundation, posture,
 * and relay stacks, read-only; or, with `apply`, that plan carried out, if
 * its digest is still `apply`'s.
 */
export type AwsBootstrapParams = { 
/**
 * The account, when several are bound.
 */
account?: string, 
/**
 * The operator's address on the alerts topic; for a new foundation.
 */
alert_email?: string, 
/**
 * The trail's encryption: `aws-managed` (SSE-S3, the default) or
 * `customer` (its own KMS key, about $1 a month).
 */
trail_key?: string, 
/**
 * Apply the plan whose digest this is.
 */
apply?: string, };
