// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `aws.confirm_alerts`'s result: the subscription, as SNS read it back.
 */
export type AwsConfirmAlertsResult = { account: string, 
/**
 * The alerts topic's ARN.
 */
topic: string, 
/**
 * The subscription's ARN.
 */
subscription: string, 
/**
 * SNS's `ConfirmationWasAuthenticated`: only the account can
 * unsubscribe it.
 */
authenticated: boolean, 
/**
 * SNS's `PendingConfirmation`.
 */
pending: boolean, 
/**
 * The subscribed address, its local part masked.
 */
endpoint?: string, 
/**
 * The confirmation's request id.
 */
request_id?: string, };
