// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `aws.confirm_alerts`'s params (theseus-9p40): the token from SNS's
 * confirmation email, which the core confirms with
 * `AuthenticateOnUnsubscribe`. A secret: never printed, logged, or kept.
 */
export type AwsConfirmAlertsParams = { 
/**
 * The account, when several are bound.
 */
account?: string, 
/**
 * The token, or the whole confirmation link (copied, never opened).
 */
token: string, };
