// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The durability tender (AWS step 15): the store shipped off the machine,
 * WAL segments and blobs to the foundation's bucket and index rows to its
 * table. `oldest_unshipped_unix_ms` is the recovery point's exposure (spec
 * §6, the 5 to 60 s target): the commit time of the oldest record not yet
 * shipped, none when everything is; `lag_ms` is its age as health was asked.
 */
export type AwsDurabilityStatus = { 
/**
 * `waiting` (for serving, or the account's check), `shipping`,
 * `caught_up`, `failing` (it retries; `error` says why), or `stopped`
 * (it cannot go on; `error` says why).
 */
state: string, 
/**
 * Where it ships: `s3://<bucket>/<prefix>`, and the table.
 */
bucket: string, prefix: string, table: string, oldest_unshipped_unix_ms?: number, lag_ms: number, 
/**
 * The last position shipped, and when.
 */
shipped_to_position: number, last_shipped_unix_ms?: number, 
/**
 * Since the daemon started: sealed segments, tails of the open one,
 * blobs, index rows, and the bytes of them all.
 */
segments: number, tails: number, blobs: number, rows: number, bytes: number, error?: string, };
