// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GuardDuty's usage over its last 30 days (`GetUsageStatistics`, free),
 * read weekly after serving. Health warns past `warn_cents`.
 */
export type AwsGuardDutyStatus = { cents_30_days: number, warn_cents: number, read_at_unix_ms: number, };
