// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account's hands (AWS design §3.3, "Watching a hundred hands"; step 40
 * part 2): the hands running by backend, the oldest, what they hold
 * reserved, the hour's meter against its line, and the TTL reaper's
 * failures read off the completion queue. Amounts in micro-dollars.
 */
export type AwsHandsStatus = { 
/**
 * The groups whose call has not settled.
 */
groups_open: number, running_lambda: number, running_fargate: number, 
/**
 * When the oldest running hand was launched.
 */
oldest_unix_ms?: number, 
/**
 * What the running hands hold reserved against their sessions' budgets.
 */
reserved_micros: number, 
/**
 * The hour's meter: what the AWS actions dispatched this hour reserve
 * (those still running) and spent (those settled).
 */
hour_micros: number, 
/**
 * The hour's line (`hourly_alert_usd`): past it, one alert that hour.
 */
hour_line_micros: number, 
/**
 * The start of the hour whose alert fired, when this hour's has.
 */
alerted_hour_unix_ms?: number, 
/**
 * Runaway mode (theseus-ext.12), while it holds: until when, and in
 * words. New AWS actions that reserve are refused until then.
 */
runaway_until_unix_ms?: number, runaway?: string, 
/**
 * The reaper's failure records taken off the queue since the start, and
 * the last one's words.
 */
reaper_failures: number, reaper_last_failure?: string, 
/**
 * When this was read.
 */
read_at_unix_ms: number, };
