// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An AWS call's plan (AWS design §3.9): the account and region it goes to,
 * the operation, and what the catalog says of it. The gate's
 * `[policy.aws]` reads it, and the surfaces show it.
 */
export type AwsPlan = { account: string, region: string, 
/**
 * The service as the catalog names it (`cloudformation`).
 */
service: string, 
/**
 * `DescribeStacks`.
 */
operation: string, 
/**
 * Charged per request, or it starts something metered.
 */
cost_bearing?: boolean, 
/**
 * The names, ids, and ARNs its input gives (an S3 bucket and prefix).
 */
resources?: Array<string>, };
