// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwsAccountStatus } from "./AwsAccountStatus";

/**
 * The AWS accounts the config binds (`[aws.accounts.<id>]`).
 */
export type AwsStatus = { accounts: Array<AwsAccountStatus>, };
