// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The binary this daemon runs, and whether its jobs can write it (review
 * 2's consideration 3). At L0 a job runs as the daemon's user, so a binary
 * that user can write, or one in a directory it can write, is one a job can
 * replace, and the next start runs what it finds there.
 */
export type BinaryStatus = { 
/**
 * The path the next start runs ("" when it could not be read).
 */
path: string, 
/**
 * `jobs_can_write` (the file, or its directory, is writable by the
 * daemon's user), `ok`, or `unknown` (`detail` says why).
 */
state: string, 
/**
 * What is writable, or why it is not known, in words.
 */
detail: string, };
