// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookInfo } from "./BookInfo";

/**
 * `books.list`'s answer.
 */
export type BooksListResult = { 
/**
 * The seven books in `BOOKS`' order, then `unsorted`: each listed,
 * an empty one with no episodes.
 */
books: Array<BookInfo>, 
/**
 * Every episode held, the books' sum.
 */
episodes: number, 
/**
 * Read from the index's terms; false while the index builds them after
 * an upgrade, when the answer read every imported session's record.
 */
indexed: boolean, ms: number, };
