// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `books.page`: one book's episodes, newest first.
 */
export type BooksPageParams = { 
/**
 * One of `BOOKS`, or `unsorted`.
 */
book: string, 
/**
 * Only episodes with this topic, from this source, or in this place:
 * a place's kind (`dm`), or its kind and name (`dm:wren`), as the
 * facets name it.
 */
topic?: string, source?: string, place?: string, 
/**
 * The page after the one whose `next` this is.
 */
cursor?: string, 
/**
 * At most this many (default 50, at most 200).
 */
limit?: number, 
/**
 * As `books.list`'s.
 */
session_id?: string, };
