// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an episode happened, as the import kept it.
 */
export type BookPlace = { 
/**
 * `dm`, `slack-channel`, `discord-channel`, `cli`, `cron`,
 * `heartbeat`, or `file`.
 */
kind: string, name?: string, };
