// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `books.list`: as asked for the place `session_id` speaks in; none, a
 * private place (the CLI's, the web UI's).
 */
export type BooksListParams = { session_id?: string, };
