// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One value of a facet, with how many of the book's episodes have it.
 */
export type BookFacet = { value: string, episodes: number, };
