// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookEpisode } from "./BookEpisode";
import type { BookFacets } from "./BookFacets";

/**
 * `books.page`'s answer.
 */
export type BooksPageResult = { book: string, episodes: Array<BookEpisode>, 
/**
 * The cursor of the next page, when there is more.
 */
next?: string, 
/**
 * The book's episodes, unfiltered.
 */
total: number, 
/**
 * The book's facets, on a first page (no cursor) asked for a private
 * place.
 */
facets?: BookFacets, 
/**
 * The episodes this page looked at to fill itself: past `SCAN_MAX` with
 * a filter, it stops short, and `next` goes on from there.
 */
scanned: number, 
/**
 * As `BooksListResult`'s.
 */
indexed: boolean, ms: number, };
