// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookPlace } from "./BookPlace";

/**
 * One episode on a book's page.
 */
export type BookEpisode = { 
/**
 * Its imported session (`ses_ep…`): `session.history` reads its
 * messages.
 */
session_id: string, episode_id: string, book: string, 
/**
 * The import's tag.
 */
tag: string, 
/**
 * Its span of time (unix ms).
 */
start_ms: number, end_ms: number, source: string, agent?: string, 
/**
 * `personal`, `company-confidential`, `partner-confidential`, or
 * `public`: the pipeline's label.
 */
sensitivity: string, messages: number, 
/**
 * The pipeline removed a credential from its text.
 */
credential_redacted: boolean, 
/**
 * The pipeline's triage category, when it triaged the episode.
 */
triage?: string, 
/**
 * Its place, topics, partner and summary are its text: none when
 * withheld.
 */
place?: BookPlace, 
/**
 * Empty when withheld.
 */
topics: Array<string>, partner?: string, 
/**
 * Its summary, or, with none, its title (from its first message).
 */
summary?: string, 
/**
 * Why its text is not shown, when it is not.
 */
withheld?: string, };
