// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookFacet } from "./BookFacet";

/**
 * A book's facets: what its filters can name, the most episodes first,
 * each list cut at `FACET_MAX`.
 */
export type BookFacets = { topics: Array<BookFacet>, sources: Array<BookFacet>, places: Array<BookFacet>, 
/**
 * Whether a list was cut.
 */
cut: boolean, };
