// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One book, as `books.list` shows it.
 */
export type BookInfo = { 
/**
 * One of `BOOKS`, or `unsorted`.
 */
book: string, 
/**
 * Its episodes held (an erased one is in no book).
 */
episodes: number, 
/**
 * The earliest and the latest of its episodes' starts (unix ms).
 */
first_ms?: number, last_ms?: number, };
