// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A run of a session's nodes, first to last in order.
 */
export type BudgetRange = { first: string, last: string, nodes: number, };
