// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The totals. A task's spend is its parent's too, and its carve is its
 * parent's reservation, so the money figures add the top-level rows only;
 * the lifetime adds every session's, since each session counts its own.
 */
export type BudgetTotals = { executions: number, tasks: number, limit_usd: number, spent_usd: number, reserved_usd: number, held_unknown_usd: number, available_usd: number, lifetime_usd: number, 
/**
 * Budget questions waiting.
 */
questions: number, };
