// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A waiting budget question.
 */
export type BudgetQuestionInfo = { 
/**
 * Its correlation id, which `action.confirm` answers.
 */
correlation_id: string, 
/**
 * What the call waiting on it would reserve.
 */
needs_usd: number, };
