// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetRow } from "./BudgetRow";
import type { BudgetTotals } from "./BudgetTotals";
import type { JudgeDayBudget } from "./JudgeDayBudget";

/**
 * `budget.list`'s answer.
 */
export type BudgetListResult = { 
/**
 * The open executions that are no task of another open one, oldest
 * first, each with its tasks.
 */
executions: Array<BudgetRow>, totals: BudgetTotals, 
/**
 * `[kernel] spend_limit_usd`: an execution whose limit is `config`'s
 * follows it.
 */
config_limit_usd: number, 
/**
 * The judge's shadow budget for the local day (`[judge]`), a budget of
 * its own that no session's spends from.
 */
judge?: JudgeDayBudget, };
