// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a budget question asks about (theseus-0sg): the session reached its
 * spend limit. Approving resets `spent_usd` to $0 and the waiting call
 * proceeds; the session's lifetime cost keeps counting.
 */
export type BudgetAsk = { spent_usd: number, limit_usd: number, 
/**
 * What the waiting call reserves.
 */
needed_usd: number, 
/**
 * The session's lifetime cost, resets included.
 */
lifetime_usd: number, };
