// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An execution's budget in US dollars (theseus-0sg).
 */
export type BudgetInfo = { limit_usd: number, 
/**
 * Settled costs since the execution opened or was last reset. The
 * session's `cost_usd` is its lifetime total, which a reset never lowers.
 */
spent_usd: number, reserved_usd: number, held_unknown_usd: number, available_usd: number, 
/**
 * Approved resets of the spend to $0.
 */
resets: number, 
/**
 * The budget question waiting for the operator (a correlation id).
 */
question?: string, 
/**
 * The unit budget a record stored before dollar budgets carried, as it
 * was: `limit`, `spent`, `reserved`, `held_unknown`.
 */
units_before?: { limit: number; spent: number; reserved: number; held_unknown: number } | null, };
