// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetQuestionInfo } from "./BudgetQuestionInfo";
import type { BudgetResetInfo } from "./BudgetResetInfo";

/**
 * One open execution's money.
 */
export type BudgetRow = { execution_id: string, session_id: string, 
/**
 * `conversation` or `task`.
 */
kind: string, state: string, 
/**
 * The session's title or label, when it has one.
 */
title?: string, limit_usd: number, 
/**
 * Where the limit comes from: `config` (`[kernel] spend_limit_usd`,
 * followed when it changes), `place` (a place's ceiling, the lower of
 * its own and the config's), `carve` (a task's, carved from its
 * parent), or `pinned` (its own, named when it opened).
 */
limit_from: string, 
/**
 * What names it: the place (`#pier`), or the parent's session.
 */
limit_by?: string, 
/**
 * Settled costs since it opened or was last reset.
 */
spent_usd: number, 
/**
 * Reserved for calls in flight, its tasks' carves among them.
 */
reserved_usd: number, held_unknown_usd: number, available_usd: number, 
/**
 * The session's lifetime cost, which no reset lowers.
 */
lifetime_usd: number, 
/**
 * Approved resets of the spend to $0.
 */
resets: number, 
/**
 * The last of them, read from its `budget.reset` row.
 */
last_reset?: BudgetResetInfo, 
/**
 * Why the last reset was not read, when there was one: the ledger's
 * index is still being built after the start, and a scan of the
 * history is not this read's to make.
 */
last_reset_unread?: string, 
/**
 * The budget question waiting for the operator.
 */
question?: BudgetQuestionInfo, 
/**
 * A task's parent execution.
 */
parent?: string, 
/**
 * A task's carve as its parent holds it now: the parent's reservation
 * for it, which shrinks as the task spends.
 */
carve_held_usd?: number, 
/**
 * Its open tasks, oldest first.
 */
tasks?: Array<BudgetRow>, };
