// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An approved reset, from its `budget.reset` row.
 */
export type BudgetResetInfo = { at_ms: number, 
/**
 * Who approved it.
 */
by: string, spent_before_usd: number, };
