// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What did not fit even after every drop: a named outcome, never a
 * thinner prompt.
 */
export type BudgetOverage = { 
/**
 * The tokens over the limit.
 */
tokens: number, why: string, };
