// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetRange } from "./BudgetRange";

/**
 * One thing a budget left out.
 */
export type BudgetDrop = { 
/**
 * A node left out alone (a recall's item).
 */
node_id?: string, 
/**
 * A run of nodes left out (the ring's cut).
 */
range?: BudgetRange, 
/**
 * `budget` (a recall's), `overflow` (the ring's).
 */
reason: string, tokens: number, 
/**
 * `recall`, `ring`, or (30c) `compaction`.
 */
tier: string, };
