// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetDrop } from "./BudgetDrop";
import type { BudgetOverage } from "./BudgetOverage";

/**
 * What a compilation, or a recall's pack, fitted into its limit and what it
 * left out (M6 30b; §2.8, §2.11): every drop with its reason, tokens, and
 * tier, the ring's cut as a range, and an overage when even the kept part
 * did not fit. A compilation's is stored with it (`budget`); a recall's
 * rides in its manifest.
 */
export type BudgetReport = { 
/**
 * The tokens it had: a request's, the model's window less the output
 * cap and a margin; a pack's, `[memory] recall_budget_tokens`. 0: no
 * window is known.
 */
limit_tokens: number, 
/**
 * The tokens it used, as estimated.
 */
used_tokens: number, dropped?: Array<BudgetDrop>, overage?: BudgetOverage, };
