// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cache by size: `bytes` is an estimate where `estimated`, and
 * `cap_bytes` its bound (0: none of its own, as the import's catalog,
 * which is dropped after an idle stretch instead).
 */
export type CacheHealth = { name: string, bytes: number, cap_bytes: number, entries: number, estimated: boolean, 
/**
 * What else to know: its idle bound, its drops, or why it is empty.
 */
note: string, };
