// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a request's cache breakpoints went, and their TTLs (theseus-ev1).
 */
export type CacheSummary = { 
/**
 * The blocks marked, in order: `header`, `context`, `conversation`.
 */
breakpoints: Array<string>, 
/**
 * The system blocks' TTL: `5m` or `1h`.
 */
ttl: string, 
/**
 * The conversation's TTL, at most `ttl`.
 */
conversation_ttl: string, };
