// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReliabilityBin } from "./ReliabilityBin";

export type Calibration = { n: number, brier: number, ece: number, 
/**
 * The reliability table: ten equal bins, empty ones included.
 */
bins: Array<ReliabilityBin>, };
