// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogModel = { model: string, 
/**
 * The catalog row as configured (provider, window, prices, capabilities, source).
 */
entry: Record<string, unknown>, 
/**
 * Profiles that use this model.
 */
profiles: Array<string>, };
