// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node the check was admitted.
 */
export type CheckPiece = { node_id: string, session_id: string, 
/**
 * `objective` or `acceptance` (the checked task's), a role of the
 * check's own pieces, or `claim` (the report).
 */
role: string, 
/**
 * `checked`: a piece of the checked task's arrangement; `own`: a piece
 * the check's call quoted; `claim`: the checked task's report.
 */
from: string, };
