// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span the check's words share with the checked task's working.
 */
export type CheckOverlap = { 
/**
 * `brief`, or `piece N` (its index in the check's arrangement, from 0).
 */
source: string, 
/**
 * The node of the checked task's session that holds it.
 */
node_id: string, 
/**
 * Its length in words.
 */
words: number, 
/**
 * The span, as the source says it (cut at 200 characters).
 */
span: string, };
