// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TenderStatus } from "./TenderStatus";

/**
 * The daemon's children (theseus-z4b): the job wrappers it spawned, the
 * orphans it adopted, and what waits to be reaped. The daemon reaps each
 * wrapper and orphan once it exits, and leaves the `op` processes to tokio,
 * which waits for them.
 */
export type ChildrenStatus = { 
/**
 * The daemon is a child subreaper, so a job's descendant whose wrapper
 * died is reparented to it, not to init. Only the socket daemon is one.
 */
subreaper: boolean, 
/**
 * Job wrappers among its children whose command still runs.
 */
wrappers_running: number, 
/**
 * Job wrappers among its children whose command has exited, each
 * lingering for what it left running.
 */
wrappers_lingering: number, 
/**
 * Processes it adopted: a job's descendants whose wrapper died. None of
 * them may answer an approval.
 */
orphans: number, 
/**
 * Children that have exited and wait to be reaped: 0 in steady state, so
 * a count that grows is a leak.
 */
zombies: number, 
/**
 * Children that tokio waits for itself: the `op` processes.
 */
owned: number, 
/**
 * Job wrappers reaped since the daemon's image started.
 */
reaped_wrappers: number, 
/**
 * Orphans reaped since the daemon's image started.
 */
reaped_orphans: number, 
/**
 * The long-lived children it supervises (roadmap row 51): the index
 * tender, restarted with backoff whenever it exits. Empty from a daemon
 * before it, and from one that runs none.
 */
tenders?: Array<TenderStatus>, };
