// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassReport = { class: string, 
/**
 * Labeled judgments whose top answer was this class, and whose label is.
 */
predicted: number, actual: number, precision: number | null, recall: number | null, };
