// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The prove's classification part (design §2.9): `classify.v1`'s decision
 * on one question against its baseline's, on the judgments an operator or
 * an audit labeled. `should_promote`'s baseline is the model's own
 * `task.create` in that turn, as the system's `task_create` label records it.
 */
export type ClassifyQuality = { 
/**
 * `classify.v1`.
 */
pack: string, question: string, 
/**
 * Judgments in the window with an operator's or an audit's label on it.
 */
labeled: number, 
/**
 * Of those, the ones whose baseline is recorded: the compared set.
 */
compared: number, 
/**
 * Right on the compared set: Jev's lean, and the baseline's decision.
 */
jev_right: number, baseline_right: number, 
/**
 * The shares right, when `compared` reaches the minimum.
 */
jev_rate: number | null, baseline_rate: number | null, 
/**
 * `jev_better`, `baseline_better`, `no_difference` (McNemar's test on
 * the pairs where they disagree, at 95%), or `insufficient`.
 */
verdict: string, 
/**
 * Set when the sample is short: "compared 3 of 30".
 */
insufficient: string | null, };
