// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One candidate signal that fired at a compile.
 */
export type CompileSignal = { 
/**
 * `dormancy`, `tail_band`, `report`, `wake`, or `cache_miss`.
 */
name: string, 
/**
 * Its measure, in the signal's unit: the gap's minutes, the share of
 * the window the tail reached (in percent), the reports or wakes that
 * arrived, or the cache read before the miss (in tokens).
 */
value: number, 
/**
 * The same in words, as `continue.v1` reads it.
 */
detail: string, };
