// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A restart onto the vault's changed config note (theseus-2fo): what
 * changed since the copy, by table name and digest, never by value.
 */
export type ConfigRestart = { reference: string, 
/**
 * When the process that found the change asked to restart.
 */
at_unix_ms: number, 
/**
 * The tables that differ (`kernel`, `policy.tools`, `profiles.glm`).
 */
tables: Array<string>, copy_sha256: string, vault_sha256: string, };
