// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetAsk } from "./BudgetAsk";
import type { ExternalText } from "./ExternalText";
import type { TaskChange } from "./TaskChange";
import type { TaskRef } from "./TaskRef";

/**
 * A tool call waiting for the operator (spec §3.9: confirmation is bound to
 * the exact tool, arguments, resource, and an expiry).
 */
export type ConfirmRequest = { correlation_id: string, session_id: string, execution_id: string, tool: string, input: unknown, resource?: string, 
/**
 * Why policy asks (e.g. "write under /home/x/projects", "run cargo test").
 */
reason: string, by: string, requested_at_ms: number, 
/**
 * When the question stops holding; 0 for a budget question, which
 * holds until it is answered or a newer one replaces it.
 */
expires_at_ms: number, 
/**
 * The floor asks: the call touches Theseus's own binary or state, or the
 * 1Password CLI or token. It asks at every posture.
 */
floor: boolean, 
/**
 * Set on a budget question (`tool` is `budget.reset`): the figures it
 * asks about. `reason` is the question in words.
 */
budget?: BudgetAsk, 
/**
 * The task that asks, when a task does (DD7).
 */
task?: TaskRef, 
/**
 * The call waits because its session read external text (theseus-9bp):
 * what it read. An approval with `trust` clears that as well.
 */
external_text?: ExternalText, 
/**
 * The layer-1 task change the call asks for, when it is one (39b).
 */
change?: TaskChange, };
