// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigRestart } from "./ConfigRestart";

/**
 * Where the config came from, and whether it may act (theseus-2fo, spec
 * §3.19). A start whose config is an `op://` reference serves from the
 * last-known-good copy of the note and reads the vault behind the socket;
 * until the vault confirms the copy, the daemon answers only what reads.
 */
export type ConfigStatus = { 
/**
 * `vault` or `file`: where the config lives.
 */
source: string, 
/**
 * The `op://` reference, or the file's path.
 */
reference: string, 
/**
 * `confirmed` (it may act), `confirming` (serving from the copy while
 * the vault is read), `held` (the vault answered, and the copy may not
 * act: `detail` says why), or `restarting` (onto the vault's changed
 * note).
 */
state: string, 
/**
 * How this start got it: `vault` (read before serving), `copy`, or `file`.
 */
started_from: string, 
/**
 * Why it is held, what it is doing, or how it was confirmed, in words.
 */
detail?: string, 
/**
 * When it was confirmed, in ms after the process started: the vault's
 * answer, or the end of a read before serving.
 */
confirmed_ms?: number, 
/**
 * The last-known-good copy's path, when the config is in the vault.
 */
copy?: string, 
/**
 * Reads of the vault behind the socket: the first, then each retry.
 */
reads: number, 
/**
 * Until the next read, when held.
 */
retry_in_ms?: number, 
/**
 * This process began as a restart onto the vault's changed note.
 */
restarted?: ConfigRestart, };
