// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigRestart } from "./ConfigRestart";

/**
 * Where the config came from, and what the vault said of it (theseus-2fo,
 * spec §3.19). A start whose config is an `op://` reference serves from the
 * last-known-good copy of the note and acts on it at once when its digest is
 * the one the daemon recorded as it wrote it (theseus-zmgb); after serving,
 * it reads the vault once.
 */
export type ConfigStatus = { 
/**
 * `vault` or `file`: where the config lives.
 */
source: string, 
/**
 * The `op://` reference, or the file's path.
 */
reference: string, 
/**
 * `confirmed` (a file, a note read before serving, or a copy the vault
 * agrees with), `confirming` (acting on the copy while the vault is
 * read), `held` (the vault's read did not settle it: it did not answer,
 * its note does not load, or it changed again since a restart; the
 * daemon keeps serving the copy, and `detail` says why), or
 * `restarting` (onto the vault's changed note).
 */
state: string, 
/**
 * How this start got it: `vault` (read before serving), `copy`, or `file`.
 */
started_from: string, 
/**
 * Why it is held, what it is doing, or how it was confirmed, in words.
 */
detail?: string, 
/**
 * When it was confirmed, in ms after the process started: the vault's
 * answer, or the end of a read before serving.
 */
confirmed_ms?: number, 
/**
 * The last-known-good copy's path, when the config is in the vault.
 */
copy?: string, 
/**
 * Reads of the vault behind the socket: one a start from the copy.
 */
reads: number, 
/**
 * This process began as a restart onto the vault's changed note.
 */
restarted?: ConfigRestart, };
