// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The socket's connections for health (theseus-7vtp): `connections: 3 of
 * 768 · 0 refused · open files 65536 of 1048576`. Past the ceiling, which
 * sits under the open-files limit, a new connection is told why and closed.
 */
export type ConnectionsHealth = { 
/**
 * Socket connections held now.
 */
held: number, 
/**
 * The most it holds (`[server] max_connections`, or derived from the limit).
 */
ceiling: number, 
/**
 * Connections refused at the ceiling since the daemon started.
 */
refused: number, 
/**
 * The soft open-files limit in effect, after the raise at start.
 */
fd_soft: number, 
/**
 * The hard open-files limit.
 */
fd_hard: number, };
