// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A turn of the session, as its compiles recorded it.
 */
export type ContextTurn = { turn_id: string, 
/**
 * Its first compile's time.
 */
at_ms: number, loops: number, 
/**
 * Its last loop's estimate.
 */
est_tokens: number, compilation_id: string, };
