// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextExplainParams = { session_id: string, 
/**
 * The turn; default the session's latest.
 */
turn_id?: string, };
