// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One part of a request, in the request's order.
 */
export type ContextPart = { 
/**
 * `header` (the system's first block), `context` (a context file in its
 * second), `guidance` (a category's section after the files), `tools`,
 * `recall` (an assembled prefix's recall section), or `conversation`.
 */
block: string, 
/**
 * `persona`, `assembly`, `precedence`, `tools note`, `profile`; a
 * file's path; a category's id (`preamble` for the guidance's first
 * section); a recalled source's header.
 */
name: string, bytes: number, 
/**
 * Its tokens at the model's figures (`TokenRates`), as the compiler
 * estimates a request; the conversation's are the rest of the turn's
 * estimate.
 */
tokens: number, digest?: string, 
/**
 * Against the turn's compilation: `same` (the digest it recorded),
 * `changed`, or `new` (it carried no such part). Absent when there is
 * no turn to compare, or the part has no digest of its own.
 */
then?: string, 
/**
 * Its version (a guidance's).
 */
version?: number, 
/**
 * Its text, to a private place only.
 */
text?: string, 
/**
 * What else to know: a file missing or cut, a shared place's file
 * carried as its header alone, the tools' names.
 */
note?: string, };
