// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedEpisode } from "./ImportedEpisode";

/**
 * Where a recalled node came from: its session's place by name, and for an
 * imported one, its episode's labels.
 */
export type ContextSource = { place: string, title?: string, imported?: ImportedEpisode, };
