// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheSummary } from "./CacheSummary";
import type { CompileSignal } from "./CompileSignal";
import type { ContextFileRef } from "./ContextFileRef";
import type { EstimateSummary } from "./EstimateSummary";
import type { PlaceClass } from "./PlaceClass";
import type { TaskViewSummary } from "./TaskViewSummary";

/**
 * `context.compiled`: the context a loop's request was compiled from
 * (§3.13). The `context.compiled` ledger row and the trace's compile span
 * carry the same.
 */
export type ContextCompiled = { session_id: string, turn_id: string, loop: number, 
/**
 * `recompile` (a new compilation) or `append`.
 */
decision: string, 
/**
 * What made it recompile (`new_session`, `window`, `manual_fresh`, …);
 * `null` for an append.
 */
trigger: string | null, compilation_id: string, 
/**
 * The compilation's strategy: `fresh` or `transcript`.
 */
strategy: string, prefix_nodes: number, tail_nodes: number, messages: number, est_tokens: number, 
/**
 * How `est_tokens` was reached (theseus-f5hf); absent in rows written
 * before it.
 */
estimate?: EstimateSummary, digest: string, 
/**
 * The tool calls that had no result, given a synthetic one.
 */
repairs: Array<string>, 
/**
 * Tools offered.
 */
tools: number, nodes_scanned: number, 
/**
 * Of `nodes_scanned`, those this compile read past their stub (M6 step
 * 33): the nodes its request renders that the turn had not read yet,
 * each taken from the heat cache or decoded from its record (health's
 * `store.node_cache` counts which). Absent in rows before it, and when
 * it read none.
 */
decoded?: number, 
/**
 * Of `nodes_scanned`, those left stubs, never decoded: before a ring's
 * cut or a compaction's floor (step 33).
 */
stubs?: number, context_files?: Array<ContextFileRef>, 
/**
 * The persona in play (theseus-c48).
 */
persona?: string, cache: CacheSummary, 
/**
 * The class of the place the turn speaks in (the place rule,
 * theseus-nbsh), fixed for the turn; absent from a daemon before it.
 */
class?: PlaceClass, 
/**
 * Context files the request carries as their headers alone: a shared
 * place's that are not marked public.
 */
withheld?: number, 
/**
 * CONTINUE's candidate signals that fired (M5 25b): a compile that
 * fired one and no trigger asks `continue.v1` in shadow.
 */
signals?: Array<CompileSignal>, 
/**
 * The task graph the request showed (39a); absent when its scope has
 * no task, as in a plain turn.
 */
tasks?: TaskViewSummary, };
