// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilationInfo } from "./CompilationInfo";
import type { ContextCompiled } from "./ContextCompiled";
import type { ContextPart } from "./ContextPart";
import type { ContextSource } from "./ContextSource";
import type { ContextTurn } from "./ContextTurn";
import type { ImportedEpisode } from "./ImportedEpisode";
import type { RecallManifest } from "./RecallManifest";

/**
 * `context.explain`'s answer.
 */
export type ContextExplainResult = { session_id: string, title?: string, kind: string, 
/**
 * The place class its turns speak in (`private`, `shared`), and the
 * place by name.
 */
class: string, place: string, 
/**
 * An imported session: its episode. It takes no turn, so it has no
 * parts; it reaches a model only as recall's testimony, from a private
 * place.
 */
imported?: ImportedEpisode, 
/**
 * The session's turns with compiles, newest first (the newest 50).
 */
turns: Array<ContextTurn>, 
/**
 * The turn explained, and its last loop's compile.
 */
turn_id?: string, compiled?: ContextCompiled, 
/**
 * That compile's compilation, or the session's current one.
 */
compilation?: CompilationInfo, 
/**
 * What the turn ran on (the session's last target), and its window.
 */
profile: string, model: string, window?: number, 
/**
 * The request's parts, as the next turn would build them now.
 */
parts: Array<ContextPart>, 
/**
 * The system blocks' digest now, and the turn's compilation's.
 */
digest_now: string, digest_then?: string, 
/**
 * The system blocks are the bytes that turn saw (the digests agree).
 * Absent with no turn to compare.
 */
unchanged?: boolean, 
/**
 * Why the parts could not be built, when they could not (a profile no
 * longer configured).
 */
unbuilt?: string, 
/**
 * The turn's recalls (its `recall.shadow` manifests, each admitted
 * node's excerpt filled to a private place), and each recalled
 * session's place.
 */
recalls: Array<RecallManifest>, sources: { [key in string]: ContextSource }, 
/**
 * Why the text was left out: a place that is not private reads sizes
 * and digests alone. Absent when it was given.
 */
withheld?: string, ms: number, };
