// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The crash file a start found (Review 2's consideration 1): the release
 * build aborts on a panic, and its panic hook first writes the thread, the
 * location, and the message beside the store. The next start moves the
 * file into `crashes/` and says so (`server.crashed`). The message stays in
 * the file, as in the log.
 */
export type CrashStatus = { at_unix_ms: number, 
/**
 * The panicking daemon's pid and build.
 */
pid: number, version: string, thread: string, 
/**
 * `file:line:column`.
 */
location: string, 
/**
 * The crash file, under the state dir's `crashes/`.
 */
file: string, 
/**
 * This start found it: the run before this one ended in it.
 */
this_start: boolean, };
