// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The daemon's day ceiling (`[kernel] daily_spend_ceiling_usd`,
 * theseus-kp20): every model call's spend today, against the ceiling.
 */
export type DayCeilingBudget = { 
/**
 * The local day, `YYYY-MM-DD`.
 */
day: string, ceiling_usd: number, 
/**
 * Settled and booked today.
 */
spent_usd: number, 
/**
 * Held by calls in flight.
 */
held_usd: number, 
/**
 * Whether no model call is made until the day turns.
 */
reached: boolean, 
/**
 * When the first call was refused today (unix ms).
 */
reached_at_ms?: number, 
/**
 * When the day turns: the next local midnight (unix ms), and its local
 * time, `2026-10-09 00:00`.
 */
turns_at_ms: number, turns_at: string, };
