// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a notice reaches a viewer.
 */
export type Delivery = { "as": "ping", sound: boolean, } | { "as": "badge" } | { "as": "nothing" };
