// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoingKind } from "./DoingKind";

export type Doing = { what: DoingKind, 
/**
 * `turn 4`, `fs.write`, `waiting on 2 calls`.
 */
label: string, since_ms: number, turn: number, loop_index: number, };
