// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a conversation or a task is doing now.
 */
export type DoingKind = "thinking" | "tool" | "job" | "asking" | "waiting_on_tasks" | "sleeping";
