// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `events.lost` (design `stage2` §2.5): a connection's queue passed the
 * backlog cap, so its notifications were dropped from then until it drained.
 * Responses are never dropped. Re-read each stream: `executions` with
 * `executions.watch`, `session:<id>` with `session.history` then
 * `session.watch`, `narrative` with `narrative.watch`, `policy` with
 * `health`.
 */
export type EventsLost = { 
/**
 * How many notifications were dropped.
 */
dropped: number, 
/**
 * The streams they belonged to.
 */
streams: Array<string>, };
