// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionCancelParams = { execution_id: string, 
/**
 * Who asked, as a label in the ledger (e.g. `discord:zeroaltitude`). Default: the connection.
 */
author?: string, };
