// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfirmRequest } from "./ConfirmRequest";
import type { ExecutionView } from "./ExecutionView";

/**
 * `executions.watch`'s answer: the board as it stood when the watch began.
 * The subscription comes first, so no change falls between the two: apply a
 * snapshot row, as an event, only if its `position` is greater than the
 * last one applied for its execution.
 */
export type ExecutionsWatchResult = { 
/**
 * The board's position when the snapshot was taken: the last frame it
 * applied.
 */
position: number, 
/**
 * Every execution that needs you or works, then the `limit` most
 * recently active of the rest.
 */
executions: Array<ExecutionView>, 
/**
 * Every question waiting for the operator, as `confirm.list` gives them.
 */
confirms: Array<ConfirmRequest>, 
/**
 * How many executions the board holds.
 */
total: number, };
