// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionInfo } from "./ExecutionInfo";

export type ExecutionListResult = { executions: Array<ExecutionInfo>, 
/**
 * With `n`: the `before` for the next page back while older executions
 * remain; absent at the last page, and without `n`.
 */
older?: number, };
