// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `execution.list`'s params; absent, null or `{}` answers every execution.
 */
export type ExecutionListParams = { 
/**
 * Only these executions, in the order named, an unknown id left out: a
 * client that the push told of a change refreshes just those.
 */
ids?: Array<string>, 
/**
 * The newest `n` executions by birth, newest first (at most 1,000), in
 * place of every execution.
 */
n?: number, 
/**
 * With `n`: only executions born before this cursor, an answer's
 * `older`, to page back.
 */
before?: number, };
