// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One layer of the gate.
 */
export type ExplainLayer = { 
/**
 * The layer's name: `place`, `ceiling`, `class`, `posture`,
 * `tightening`, `grant`, `lsp`, `floor`, `hold`, `mcp_client`.
 */
layer: string, 
/**
 * What it says, in words.
 */
says: string, 
/**
 * The setting that says it (`[policy.tools] "proc.run" = approve`).
 */
setting?: string, 
/**
 * The posture after this layer.
 */
result: string, 
/**
 * This layer raised the posture.
 */
raised?: boolean, };
