// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A layer that depends on the call: when the call matches, `then`.
 */
export type ExplainCondition = { 
/**
 * `floor`, `approve_paths`, `outside_roots`, `private_address`,
 * `approve_argv`, `destructive`, `allow_argv`, `aws`, `l1`, `grant`,
 * `lsp_start`, `public_paths`.
 */
layer: string, 
/**
 * When it applies, in words.
 */
when: string, entries?: Array<string>, 
/**
 * What then: a posture, `at least <posture>`, or `refused`.
 */
then: string, };
