// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a revoke did: the server stopped, its tools dropped from the next
 * turn; the frozen copy stays on disk.
 */
export type ExtensionRevokeResult = { name: string, digest: string, tools: Array<string>, 
/**
 * The frozen copy, kept.
 */
frozen: string, };
