// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalText } from "./ExternalText";

/**
 * A session that holds external text, as health lists it (theseus-9bp).
 */
export type ExternalTextInfo = { session_id: string, title?: string, 
/**
 * The task's short id, when the session is a task's.
 */
task?: string, held: ExternalText, 
/**
 * When the hold began, in the daemon's local time, as the hold's reason
 * says it (theseus-qiy): `12:55:01`, with the day when it is not today.
 * Empty from a daemon before it.
 */
since_local?: string, };
