// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What made a session hold external text (theseus-9bp, spec §3.9): the first
 * result marked `external` that entered its context since the operator last
 * trusted it, or the hold it took from another session. From then on, every
 * call whose class is not `read` waits for the operator's approval.
 */
export type ExternalText = { 
/**
 * When the session came to hold it.
 */
since_ms: number, 
/**
 * The tool whose result it was (`http.fetch`, `web.search`). A hold
 * taken from another session names that session's first source.
 */
tool: string, 
/**
 * Where the text came from: the page's final URL, or the search's
 * request.
 */
url: string, 
/**
 * The node that brought it into this session: the result, a task's
 * brief, or a task's report; empty when a job brought it (`via: job`).
 */
node_id: string, 
/**
 * The session it came from, when this one took it from another.
 */
from_session?: string, 
/**
 * How it came from there: `task.create` (a task that a session holding
 * it started), `task.report` (a report from a task that held it), or `job`
 * (a holding session's job opened it or sent it a turn); or how it came at
 * all: `egress` (M4 18c), an L1 job that connected out, its `url` the hosts
 * it reached, or `program` (theseus-b5cl), a listed program's job.
 */
via?: string, 
/**
 * A search's query (`web.search`), which the hold names in place of
 * the request's URL (theseus-qiy); the URL stays on the result node.
 * Absent for a fetch, and in holds written before it.
 */
query?: string, };
