// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A loaded extension (43b): what the ack loaded, and its server now.
 */
export type ExtendLoadedInfo = { name: string, 
/**
 * Its server on the board: `ext-<name>`.
 */
server: string, digest: string, description: string, command: Array<string>, 
/**
 * The frozen copy that runs.
 */
frozen: string, 
/**
 * Its tools, `mcp:ext-<name>/<tool>`, as the ack loaded them.
 */
tools: Array<string>, 
/**
 * The hosts it may reach; empty: no network.
 */
network: Array<string>, acked_by: string, acked_via: string, acked_at_ms: number, 
/**
 * The session that proposed it.
 */
session_id: string, 
/**
 * The digest this one replaced, when it was a new version.
 */
replaced?: string, 
/**
 * Its server's state on the board (`ready`, `starting`, `failed`, …).
 */
state: string, calls: number, errors: number, last_error?: string, };
