// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health's count of proposals, by state. Absent when there are none.
 */
export type ExtendHealth = { proposals: number, 
/**
 * Waiting for the operator's ack.
 */
waiting: number, acked: number, declined: number, failed: number, 
/**
 * Loaded now (43b).
 */
loaded?: number, };
