// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtendInfo } from "./ExtendInfo";
import type { ExtendLoadedInfo } from "./ExtendLoadedInfo";

/**
 * `extend.list`: every proposal, newest first, and the loaded ones.
 */
export type ExtendListResult = { extensions: Array<ExtendInfo>, 
/**
 * The loaded extensions, by name (43b).
 */
loaded?: Array<ExtendLoadedInfo>, };
