// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `extension.revoke` (43b): the operator's, from a private place.
 */
export type ExtensionRevokeParams = { name: string, 
/**
 * Who presses, as a client names them (Discord's button).
 */
author?: string, 
/**
 * Where the press came from, which only the Discord binding names.
 */
discord?: DiscordOrigin, };
