// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One proposal, as its manifest has it now.
 */
export type ExtendInfo = { name: string, 
/**
 * The frozen tree's SHA-256.
 */
digest: string, 
/**
 * `proposed` (its question waits), `failed` (it did not come up in L1,
 * so nothing was asked), `acked`, or `declined`.
 */
state: string, description: string, command: Array<string>, 
/**
 * The workspace directory it was frozen from, and the frozen copy.
 */
source: string, frozen: string, 
/**
 * The tools it listed in L1.
 */
tools: Array<string>, passed: number, tests: number, 
/**
 * The hosts it asked to reach; empty: no network.
 */
network: Array<string>, 
/**
 * Why it did not come up in L1.
 */
error?: string, session_id: string, 
/**
 * The question that asks the operator (`theseus confirm <it>`).
 */
question?: string, proposed_at_ms: number, answered_by?: string, };
