// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtendInfo } from "./ExtendInfo";

/**
 * `extend.list`: every proposal, newest first.
 */
export type ExtendListResult = { extensions: Array<ExtendInfo>, };
