// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDecision } from "./GateDecision";
import type { GateResult } from "./GateResult";
import type { Plan } from "./Plan";
import type { Proposal } from "./Proposal";

/**
 * The gate's record of one tool call: its input's validation, the policy's
 * verdict, the plan it judged, and the proposal a confirmation binds.
 *
 * Every record before this type was a JSON map with its keys sorted, and a
 * node keeps writing it so (`canonical`): a stored record decodes and
 * encodes again byte for byte.
 */
export type GateRecord = { result: GateResult, 
/**
 * The input passed the tool's validation.
 */
validated: boolean, 
/**
 * The policy's verdict; `null` when the input failed validation.
 */
decision: GateDecision | null, 
/**
 * The tool's plan; `null` when the input failed validation.
 */
plan: Plan | null, proposal: Proposal, };
