// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A guild the bindings file binds places in, and the operator's word on it
 * (step 38a): a trusted guild's channels are private unless one says not.
 */
export type GuildInfo = { id: string, 
/**
 * Its label in the bindings file, if it gives one.
 */
name?: string, trusted?: boolean, };
