// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One group: its call, where its hands run, each hand's cell, and its
 * money. A cell is `waiting` (not launched yet), `running`, `stopping` (its
 * stop asked, not yet seen), `succeeded`, `failed`, `unknown`, `cancelled`
 * (stopped after a launch), or `not_launched` (cancelled before one).
 */
export type HandsGroupInfo = { 
/**
 * The `aws.hands.run` call's correlation id.
 */
group: string, session_id: string, execution_id: string, account: string, region: string, 
/**
 * `lambda` or `fargate`.
 */
backend: string, 
/**
 * `all`, `first_success`, or `a quorum of n`.
 */
until: string, 
/**
 * One per hand, in index order.
 */
cells: Array<string>, succeeded: number, failed: number, running: number, cancelled: number, not_launched: number, 
/**
 * What its settled hands cost, and what its running ones hold.
 */
spent_micros: number, reserved_micros: number, 
/**
 * `max_usd`, when the call named one.
 */
cap_micros?: number, 
/**
 * The worst case of all its hands: each one's TTL at its size's rate.
 */
worst_micros: number, created_at_unix_ms: number, 
/**
 * How it ended (`met`, `not_met`, `cancelled`), once it has.
 */
settled?: string, 
/**
 * Its one line, as Discord shows it: "🖐️ 37/100 done, 2 failed, $1.84
 * of $5".
 */
line: string, };
