// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandsGroupInfo } from "./HandsGroupInfo";

export type HandsListResult = { groups: Array<HandsGroupInfo>, };
