// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `hands.list`'s params: the newest groups first, at most `limit`
 * (default 20), only the open ones when `open` is set.
 */
export type HandsListParams = { limit?: number, open?: boolean, };
