// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health's count of what an import wrote (theseus-revl): the sessions an
 * import holds, apart from the owner's own (`HealthResult.sessions`), and
 * the erased ones. Both are nothing when there is no import.
 */
export type HealthImported = { 
/**
 * Imported sessions still held: the tags' sessions less their erased.
 */
sessions: number, 
/**
 * Imported sessions an `import.erase` tombstoned. Their keys remain.
 */
erased: number, };
