// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwsStatus } from "./AwsStatus";
import type { BinaryStatus } from "./BinaryStatus";
import type { BindingStatus } from "./BindingStatus";
import type { Build } from "./Build";
import type { CancelCount } from "./CancelCount";
import type { ChildrenStatus } from "./ChildrenStatus";
import type { ConfigStatus } from "./ConfigStatus";
import type { ContextStatus } from "./ContextStatus";
import type { CrashStatus } from "./CrashStatus";
import type { DiskStatus } from "./DiskStatus";
import type { ExternalTextInfo } from "./ExternalTextInfo";
import type { GrantStatus } from "./GrantStatus";
import type { HarnessOnly } from "./HarnessOnly";
import type { IndexHealth } from "./IndexHealth";
import type { KernelStatus } from "./KernelStatus";
import type { LspServerStatus } from "./LspServerStatus";
import type { PlacesHealth } from "./PlacesHealth";
import type { PushStatus } from "./PushStatus";
import type { SandboxHealth } from "./SandboxHealth";
import type { SecretsStatus } from "./SecretsStatus";
import type { SpoolStatus } from "./SpoolStatus";
import type { StartupPhase } from "./StartupPhase";
import type { StoreStatus } from "./StoreStatus";
import type { TelemetryStatus } from "./TelemetryStatus";
import type { Tightening } from "./Tightening";
import type { Usage } from "./Usage";
import type { WakeInfo } from "./WakeInfo";
import type { WebStatus } from "./WebStatus";

export type HealthResult = { name: string, version: string, protocol: string, 
/**
 * The binary's version and commit, as `server.started` names them (theseus-9o5n).
 */
build: Build, uptime_secs: number, sessions: number, turns: number, model: string, 
/**
 * The live profile name.
 */
profile: string, 
/**
 * Default provider name and every configured provider.
 */
provider: string, providers: Array<string>, 
/**
 * The secrets whose values are ready (names only).
 */
secrets_resolved: Array<string>, 
/**
 * Where every secret stands: the daemon serves before they resolve
 * (theseus-qa0), and each consumer waits for its own.
 */
secrets: SecretsStatus, 
/**
 * Where the config came from, and what the vault said of the copy this
 * start served from (theseus-2fo, theseus-zmgb).
 */
config: ConfigStatus, 
/**
 * The last start's phases, timed from process start: those on the path
 * to answering the socket, then those after it.
 */
startup: Array<StartupPhase>, 
/**
 * Tokens across every session, summed from session records.
 */
usage_total: Usage, provider_errors: number, ledger_rows: number, telemetry: TelemetryStatus, 
/**
 * The durable kernel (M2): executions, actions, admission.
 */
kernel: KernelStatus, 
/**
 * The daemon's own children: its job wrappers, the orphans it adopted,
 * and what waits to be reaped (theseus-z4b).
 */
children: ChildrenStatus, 
/**
 * The secret broker's grants, each with its uses (theseus-dcy). Names
 * only, never a value.
 */
broker: Array<GrantStatus>, 
/**
 * What a job may be handed, and what stays the harness's own: the AWS
 * and providers' keys (theseus-gh7). Absent from a daemon before it.
 */
harness_only?: HarnessOnly, 
/**
 * Dollars across every session, from the model catalog.
 */
cost_usd_total: number, catalog_version: string, 
/**
 * Channel bindings (M3: Discord) and what each is doing.
 */
bindings: Array<BindingStatus>, 
/**
 * `narrative = true` in the config: the narrative runs, and the web UI
 * shows its tab.
 */
narrative: boolean, 
/**
 * The context files every session's system block carries, and the
 * persona in play with its own (theseus-c48).
 */
context: ContextStatus, 
/**
 * The tools that ask first because someone pressed "should have asked"
 * (theseus-sgh), oldest first. They are stored, not configured.
 */
tightenings: Array<Tightening>, 
/**
 * The wakes conversations set with `wake.at` that have not run yet,
 * soonest first (DD8).
 */
wakes: Array<WakeInfo>, 
/**
 * The sessions that hold external text (theseus-9bp), the longest-held
 * first: in each, a call that acts waits for approval until the operator
 * trusts it again.
 */
external_text: Array<ExternalTextInfo>, 
/**
 * The web UI's refusals since the daemon's image started (theseus-70f).
 */
web: WebStatus, 
/**
 * Free space under the state dir, read when health is asked
 * (theseus-102).
 */
disk: DiskStatus, 
/**
 * Whether this daemon's jobs can write the binary it runs, read when
 * health is asked (review 2's consideration 3).
 */
binary: BinaryStatus, 
/**
 * The spool's sweeps of raw job output (theseus-2ij).
 */
spool: SpoolStatus, 
/**
 * The push (theseus-in3): its board, its watchers, and its seed. Absent
 * from a daemon before it.
 */
push?: PushStatus, 
/**
 * The AWS accounts the config binds (AWS design §3.10), each as its
 * check left it. Absent when it binds none.
 */
aws?: AwsStatus, 
/**
 * The index tender (M6 §2.2, roadmap row 51): the tender as the core
 * supervises it, and its own status when it answers. Absent from a
 * daemon before it.
 */
index?: IndexHealth, 
/**
 * The store's refused reads (R4, theseus-15g); zero from a daemon before it.
 */
store: StoreStatus, 
/**
 * The newest crash a start found (Review 2's consideration 1): what
 * panicked when the daemon last died. Absent when it never has.
 */
crash?: CrashStatus, 
/**
 * L1 (M4 17b): the class choice's settings, the limits, the last L1
 * launch since the start, and the jobs by class. Absent without tools.
 */
sandbox?: SandboxHealth, 
/**
 * Each backend's cancels since the daemon started, by how they ended
 * (M4 18a). Empty until the first.
 */
cancels?: Array<CancelCount>, 
/**
 * The place rule (theseus-nbsh): each place and its class.
 */
places?: PlacesHealth, 
/**
 * The language servers (L2): absent when `[lsp]` is off.
 */
lsp?: Array<LspServerStatus>, };
