// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The allocator's heap (glibc's `mallinfo2`, every arena).
 */
export type HeapHealth = { 
/**
 * Bytes the daemon's allocations hold now.
 */
in_use_bytes: number, 
/**
 * Bytes the allocator holds from the system: in use and free.
 */
held_bytes: number, };
