// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A frozen holdout's window, `[start, end)`, unix ms.
 */
export type HoldoutBounds = { start_ms: number, end_ms: number, };
