// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionReport } from "./QuestionReport";

/**
 * The holdout: a closed window of judgment times, `[start, end)`, the
 * latest 14 days before the report's local midnight, frozen with the
 * judgments inside it and their labels as of the run. Later judgments
 * belong to neither side.
 */
export type Holdout = { start_ms: number, end_ms: number, 
/**
 * The answered judgments inside the window, by id.
 */
judgments: Array<string>, 
/**
 * The labels on them that count, by id.
 */
labels: Array<string>, 
/**
 * Answered judgments before the window (what a candidate may be
 * written from), and after it.
 */
train: number, later: number, labeled_per_question: { [key in string]: number }, 
/**
 * Labeled judgments whose top answer is a class that acts
 * (`loop.v1`'s `progressing`).
 */
labeled_per_acting_class: { [key in string]: number }, 
/**
 * The minimum (200 labeled per deciding question, 30 per acting
 * class) is met.
 */
sufficient: boolean, 
/**
 * What is short, when it is not: `insufficient: work_state: labeled 3
 * of 200`.
 */
insufficient: string | null, 
/**
 * The holdout's own numbers, per question.
 */
questions: Array<QuestionReport>, };
