// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `import.people` (theseus-wy7y): a tag's imported sessions' people as the
 * ontology's: each message author who is a person (`person:<name>`), and
 * each DM's other party with its id, one person each, found by an exact
 * handle first; and each session a person spoke in or was the DM of, a
 * membership of origin `import`. From the stored records, deterministic,
 * no model call; a second run changes nothing. `dry_run` counts and writes
 * nothing. The owner's act, from a private place.
 */
export type ImportPeopleParams = { tag: string, dry_run: boolean, 
/**
 * Propose people from the sessions' text (theseus-wy7y): a model
 * extracts the candidates, Jev judges them, and each kept one is a
 * proposal; nothing joins the ontology until the owner accepts. With
 * `dry_run`, the sessions, tokens and projected cost, with no call.
 */
propose?: boolean, 
/**
 * `propose`'s spend cap for this run, in dollars (5 when absent).
 */
cap_usd?: number, };
