// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportLine } from "./ImportLine";

/**
 * `import.episodes`: one batch of a file's lines.
 */
export type ImportEpisodesParams = { 
/**
 * The file the lines came from, as the client names it: for the
 * report and the ledger's row.
 */
file: string, lines: Array<ImportLine>, };
