// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One imported episode, as `import.sessions` lists it: its provenance and
 * labels from its session's record. The labels are the pipeline's recorded
 * facts, never enforcement.
 */
export type ImportedEpisode = { session_id: string, episode_id: string, tag: string, source: string, agent?: string, 
/**
 * Where it happened, as the pipeline names it: its kind, and its name
 * when the source records one.
 */
place_kind: string, place_name?: string, 
/**
 * Its span (unix ms): the as-of time.
 */
start_ms: number, end_ms: number, 
/**
 * `personal`, `company-confidential`, `partner-confidential`, `public`.
 */
sensitivity: string, partner?: string, topics: Array<string>, book?: string, credential_redacted?: boolean, 
/**
 * The pipeline's triage: its category and keep score.
 */
triage?: string, keep?: number, messages: number, 
/**
 * A summary node was written.
 */
summary: boolean, 
/**
 * The first words of its summary (or its first message). Absent when
 * withheld (`ImportSessionsResult.withheld`) or erased.
 */
title?: string, erased?: boolean, 
/**
 * The episode file it was read from, as the client named it, and its line.
 */
file: string, line: number, imported_at_ms: number, 
/**
 * With `summaries`: the summary's text, and how many messages it cites.
 */
summary_text?: string, cites?: number, };
