// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `import.people` did, or would do.
 */
export type ImportPeopleResult = { tag: string, dry_run: boolean, 
/**
 * Live imported sessions read.
 */
sessions: number, 
/**
 * Distinct people found, and of those, the ones held already (by an
 * exact handle, or made by this tag's run before) and the ones made.
 */
people: number, held: number, made: number, 
/**
 * Sessions whose person list was written, and the memberships of
 * origin `import` they hold.
 */
joined: number, memberships: number, 
/**
 * Sessions with more people than a list keeps: the most active ones
 * were taken.
 */
capped: number, frames: number, ms: number, };
