// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `import.topics` (theseus-anh3): a tag's imported sessions' topic labels
 * (`labels.topic`, slash paths) as ontology topics, a tree with a topic
 * for each prefix, and each session's topic memberships, origin `import`:
 * at most the kind's per-session count, the rest kept as labels. From the
 * stored labels, never a re-import; a second run changes nothing. The
 * owner's act, from a private place.
 */
export type ImportTopicsParams = { tag: string, };
