// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `import.sessions` (theseus-7n3e): the imported episodes, filtered,
 * counted by facet, a page at a time, for the cockpit's context explorer.
 * `session.list` leaves imported sessions out (theseus-7087); this is
 * their list. A read: it writes nothing.
 *
 * Every filter is optional and they combine: `topic` takes a topic and
 * everything under it (a slash path, cut at a slash); `q` is words over
 * the title, the place's name and the topics, case folded; `from_ms` and
 * `to_ms` keep the episodes whose span meets them.
 */
export type ImportSessionsParams = { tag?: string, source?: string, 
/**
 * A place kind: `dm`, `slack-channel`, `cli`, ...
 */
place?: string, sensitivity?: string, 
/**
 * A book hint (`diary`, `casebook`, ...).
 */
book?: string, topic?: string, q?: string, from_ms?: number, to_ms?: number, 
/**
 * Count the erased ones too (their text is gone).
 */
erased?: boolean, 
/**
 * `newest` (by the span's end; the default), `oldest`, or `longest`
 * (most messages).
 */
sort?: string, offset?: number, 
/**
 * The page's size: 50 by default, at most 500.
 */
limit?: number, 
/**
 * Each row of the page with its summary's text.
 */
summaries?: boolean, 
/**
 * Only these sessions (a recalled note's, a deep link's): their rows and
 * labels in one read. Empty: every session.
 */
ids?: Array<string>, };
