// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFacet } from "./ImportFacet";

/**
 * Each facet's values, counted over the episodes every other filter keeps
 * (a facet's own filter aside, so its other values stay in view), most
 * first.
 */
export type ImportFacets = { tags: Array<ImportFacet>, sources: Array<ImportFacet>, places: Array<ImportFacet>, sensitivities: Array<ImportFacet>, books: Array<ImportFacet>, 
/**
 * Every topic path and each of its ancestors, an episode counted once
 * under each, by path.
 */
topics: Array<ImportFacet>, 
/**
 * The span's start by month (`2026-03`), oldest first.
 */
months: Array<ImportFacet>, };
