// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A facet's value and the episodes that have it.
 */
export type ImportFacet = { value: string, count: number, };
