// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of an episode file, with its number in the file (from 1).
 */
export type ImportLine = { line: number, text: string, };
