// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeopleProposeReport } from "./PeopleProposeReport";

/**
 * What `import.people` did, or would do.
 */
export type ImportPeopleResult = { tag: string, dry_run: boolean, 
/**
 * Live imported sessions read.
 */
sessions: number, 
/**
 * Distinct people found, and of those, the ones held already (by an
 * exact handle, or made by this tag's run before) and the ones made.
 */
people: number, held: number, made: number, 
/**
 * Sessions whose person list was written, and the memberships of
 * origin `import` they hold.
 */
joined: number, memberships: number, 
/**
 * Sessions with more people than a list keeps: the most active ones
 * were taken.
 */
capped: number, frames: number, 
/**
 * Distinct authors and DM parties the exclusions left out (the owner,
 * his agents, the house's names, a bot's or a UI's: theseus-0p1r).
 */
excluded: number, ms: number, 
/**
 * `propose`'s report, in place of the counts above.
 */
propose?: PeopleProposeReport, };
