// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFacets } from "./ImportFacets";
import type { ImportedEpisode } from "./ImportedEpisode";

/**
 * `import.sessions`' answer.
 */
export type ImportSessionsResult = { 
/**
 * The episodes every filter keeps.
 */
total: number, 
/**
 * Every imported episode held (erased ones too).
 */
all: number, offset: number, episodes: Array<ImportedEpisode>, facets: ImportFacets, 
/**
 * Why the text (titles, summaries) was left out: an imported session is
 * the owner's own history, so its text goes only to a private place
 * (the CLI, the web UI). Absent when it was given.
 */
withheld?: string, 
/**
 * The projection answered from: the import's counts it was built at,
 * which an import batch or an erase changes.
 */
version: string, 
/**
 * What building it took (ms), when this answer built it.
 */
built_ms?: number, ms: number, };
