// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tag, as `import.list` shows it.
 */
export type ImportTagInfo = { tag: string, 
/**
 * Imported sessions, erased ones included.
 */
sessions: number, nodes: number, erased: number, 
/**
 * Sessions by source (`openclaw-store`, `wiki`).
 */
sources: Record<string, number>, 
/**
 * The span of the episodes' own times (unix ms).
 */
first_ms?: number, last_ms?: number, 
/**
 * When its last batch was written (unix ms).
 */
updated_ms: number, };
