// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `import.erase`'s answer, its receipt.
 */
export type ImportEraseResult = { tag: string, 
/**
 * Sessions tombstoned now (an erased one is not counted again).
 */
sessions: number, 
/**
 * Their nodes, each written again with an erasure marker.
 */
nodes: number, frames: number, 
/**
 * What the index did: `forgot 120 nodes`, or why it was not asked and
 * that its follower drops them as it reads the markers.
 */
index: string, ms: number, };
