// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line the import did not take, and why.
 */
export type ImportRejected = { line: number, 
/**
 * The episode's id, when the line read far enough to name one.
 */
episode_id?: string, why: string, };
