// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportRejected } from "./ImportRejected";

/**
 * `import.episodes`' answer: what the batch did.
 */
export type ImportEpisodesResult = { 
/**
 * Lines read that were not blank.
 */
read: number, 
/**
 * Episodes written as new imported sessions.
 */
imported: number, 
/**
 * Episodes imported before, with the same hash.
 */
skipped: number, 
/**
 * Lines that did not read, and episodes whose id was imported before
 * with another hash.
 */
rejected: Array<ImportRejected>, 
/**
 * The nodes written: messages and summaries.
 */
nodes: number, 
/**
 * The frames written: one per batch.
 */
frames: number, ms: number, };
