// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `import.topics` did.
 */
export type ImportTopicsResult = { tag: string, 
/**
 * The tag's sessions read (an erased one is passed over).
 */
sessions: number, 
/**
 * The distinct labels they carry, and the topics those make: one for
 * each label and each prefix of one.
 */
labels: number, topics: number, 
/**
 * Topics declared now (the rest were held already).
 */
made: number, 
/**
 * Sessions whose topic list was written now (the rest held it already).
 */
joined: number, 
/**
 * The tag's sessions' memberships from the import, after the run.
 */
memberships: number, 
/**
 * Sessions with more topics than the kind allows one: the first ones in
 * the pipeline's order were taken, the rest stay labels.
 */
capped: number, 
/**
 * Labels no topic can be made of (an empty part, deeper than the tree
 * nests), left as labels.
 */
unplaced: number, frames: number, ms: number, };
