// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `import.erase`: every session of a tag.
 */
export type ImportEraseParams = { tag: string, 
/**
 * Why, in a few words, for the receipt.
 */
why?: string, };
