// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportTagInfo } from "./ImportTagInfo";

/**
 * `import.list`'s answer.
 */
export type ImportListResult = { tags: Array<ImportTagInfo>, };
