// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexStamp } from "./IndexStamp";

export type IndexReembed = { from: Array<IndexStamp>, done: number, total: number, };
