// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexFilters = { 
/**
 * Only these sessions.
 */
sessions?: Array<string>, 
/**
 * Only these kinds (`user_message`, `tool_result`, …).
 */
kinds?: Array<string>, 
/**
 * Only external text (`true`), or none of it (`false`).
 */
external?: boolean, };
