// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A backfill's progress, in WAL bytes.
 */
export type IndexBackfill = { done_bytes: number, total_bytes: number, };
