// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexSourceRank } from "./IndexSourceRank";

/**
 * A chunk that answered.
 */
export type IndexHit = { node_id: string, chunk: number, session_id: string, position: number, kind: string, origin: string, author?: string, place?: string, tool?: string, time_ms: number, external: boolean, 
/**
 * The chunk's text.
 */
text: string, 
/**
 * The query's entities this chunk holds.
 */
entities_matched?: Array<string>, 
/**
 * Each source that ranked it.
 */
sources: { [key in string]: IndexSourceRank }, 
/**
 * Reciprocal rank fusion over those sources.
 */
fused: number, };
