// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexNeighboursParams = { node_id: string, k: number, 
/**
 * Only nodes written before this position.
 */
as_of?: number, };
