// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexStamp } from "./IndexStamp";

export type IndexEmbedResult = { 
/**
 * Unit vectors, one per text.
 */
vectors: Array<Array<number>>, dims: number, stamp: IndexStamp, 
/**
 * Each text's tokens, its prefix and `[CLS]`/`[SEP]` included.
 */
tokens: Array<number>, embed_ms: number, };
