// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The vector files' compactions since the tender started (theseus-64x).
 */
export type IndexCompactions = { count: number, 
/**
 * Records dropped, in all.
 */
dropped: number, 
/**
 * The last one: when, why (`dead`, `rebuild`, `forget`), how long, and
 * the files' bytes before and after.
 */
last_at_ms: number, last_why: string, last_ms: number, last_bytes_before: number, last_bytes_after: number, };
