// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexCompactions } from "./IndexCompactions";
import type { IndexEmbedStats } from "./IndexEmbedStats";
import type { IndexReembed } from "./IndexReembed";
import type { IndexStamp } from "./IndexStamp";

/**
 * The tender's vector side: `IndexStatus`'s `vectors`.
 */
export type IndexVectorStatus = { 
/**
 * `off` (not configured), `no_weights`, `refused` (a file is not the
 * pinned one), `unloaded`, `loading`, or `loaded`.
 */
model: string, weights_dir?: string, 
/**
 * The stamp new vectors get.
 */
stamp?: IndexStamp, 
/**
 * Chunks the index holds, chunks with a vector that answers (this
 * stamp's, or an older one of its space), and distinct texts waiting
 * for this stamp's vector.
 */
chunks: number, vectors: number, pending: number, 
/**
 * When those counts, and `records`, `dead` and `reembed`, were read
 * (unix ms). A status that finds the tender's table held (a compaction
 * rewriting a file, a batch's write) answers the counts it last read,
 * and never waits for it (theseus-uazd).
 */
counted_ms: number, 
/**
 * Records in the vector files this space answers from, and the dead
 * among them: texts no chunk holds, which answer nothing and go at the
 * next compaction (a quarter of a file dead, a rebuild, a forget).
 */
records: number, dead: number, compactions: IndexCompactions, 
/**
 * While an older stamp's vectors answer, their stamps, and the chunks
 * already re-embedded.
 */
reembed?: IndexReembed, backfill: IndexEmbedStats, loads: number, unloads: number, 
/**
 * The last load, from the call to a model ready to run.
 */
load_ms: number, loaded_at_ms: number, last_used_ms: number, idle_unload_secs: number, 
/**
 * What candle's pools run with (`RAYON_NUM_THREADS`,
 * `CANDLE_NUM_THREADS`): the tender's own, or the core's.
 */
threads: string, last_error?: string, last_error_ms: number, };
