// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexWarmResult = { 
/**
 * The model's state after the call: `loaded`, `loading` (a load was
 * started or is running), or why it cannot (`off`, `no_weights`,
 * `refused`).
 */
model: string, mode: string, };
