// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `index.entities` (M6 step 31a): texts through the index's extractor,
 * so the memory pass names a node's entities exactly as the entity field
 * holds them, and no second copy of the rules exists.
 */
export type IndexEntitiesParams = { 
/**
 * At most [`IndexEntitiesParams::MAX_TEXTS`].
 */
texts: Array<string>, };
