// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nomic's task prefixes.
 */
export type IndexEmbedTask = "search_document" | "search_query" | "clustering" | "classification";
