// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Each source's weight in the fusion, `Σ w_s / (60 + rank_s)` (theseus-jz8):
 * the tender's defaults, which a query's `weights` override source by
 * source.
 */
export type IndexWeights = { bm25: number, entity: number, vector: number, };
