// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexEntitiesResult = { 
/**
 * Each text's entities, as `type:value` terms, sorted, in the texts'
 * order.
 */
entities: Array<Array<string>>, };
