// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexBackfill } from "./IndexBackfill";
import type { IndexLag } from "./IndexLag";
import type { IndexVectorStatus } from "./IndexVectorStatus";
import type { IndexWeights } from "./IndexWeights";

/**
 * The tender's own status, as it answers `index.status` on its socket.
 */
export type IndexStatus = { 
/**
 * `starting`, `backfilling`, `ready`, or `stalled` (the WAL could not be
 * read past a frame: `last_error` says why). The core adds `down`
 * ([`IndexHealth`]).
 */
state: string, 
/**
 * What answers: `hybrid` (BM25, entities, and vectors), or `bm25_only`
 * (no weights, or weights refused: `vectors` says which).
 */
mode: string, 
/**
 * The vector side.
 */
vectors?: IndexVectorStatus, 
/**
 * The fusion's default weights, by source.
 */
weights?: IndexWeights, pid: number, index_dir: string, wal_dir: string, 
/**
 * The index holds every node through this position.
 */
position: number, 
/**
 * The cursor: the segment and offset after the last frame read.
 */
segment: number, offset: number, documents: number, nodes: number, lag: IndexLag, 
/**
 * Why a ready tender has bytes after its cursor: a frame not yet whole
 * at the WAL's end (one being written, or a torn tail that the core's
 * next open cuts).
 */
waiting?: string, backfill?: IndexBackfill, commits: number, records_read: number, nodes_indexed: number, nodes_skipped: number, undecodable: number, rebuilds: number, extractor: number, schema: number, rss_bytes: number, started_at_ms: number, last_commit_ms: number, last_error?: string, last_error_ms: number, };
