// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node near another, by its best chunk.
 */
export type IndexNeighbour = { node_id: string, chunk: number, 
/**
 * Cosine of the 768-d vectors.
 */
score: number, position: number, session_id: string, kind: string, };
