// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexFilters } from "./IndexFilters";

export type IndexQueryParams = { text: string, 
/**
 * Hits wanted, at most 100.
 */
k: number, 
/**
 * Only nodes written before this position answer, so a replay never
 * sees its own future.
 */
as_of?: number, exclude_sessions?: Array<string>, filters?: IndexFilters, 
/**
 * The sources to rank and fuse (`bm25`, `entity`, `vector`); when
 * empty, BM25 and entities, and vectors in `hybrid` mode.
 */
sources?: Array<string>, 
/**
 * How long the vector source may wait for the model to load. 0 (the
 * core's): a model not loaded is sent to load, and this query answers
 * without vectors, saying so in `skipped`.
 */
wait_ms?: number, 
/**
 * Weights for the fusion, by source (`bm25`, `entity`, `vector`); a
 * source not named takes the tender's default ([`IndexWeights`]).
 */
weights?: { [key in string]: number }, 
/**
 * The vector source's text, when not `text` (theseus-zo1y): a turn's
 * new words alone, while BM25 and entities read the whole query.
 */
vector_text?: string, 
/**
 * The most word pieces of its text the vector source embeds, counted
 * by the model's own tokenizer; 0: as many as the model reads.
 */
vector_tokens?: number, };
