// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.label`: an operator's label on one judgment (acting: the owner,
 * from a private place).
 */
export type JudgeLabelParams = { 
/**
 * `jdg_…`.
 */
judgment: string, 
/**
 * The question it labels (`work_state`); none labels the whole
 * judgment.
 */
question: string | null, 
/**
 * The label: as the module says, by the question's kind.
 */
label: unknown, note: string | null, };
