// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JudgeLabelResult = { 
/**
 * `lbl_…`, the row's key.
 */
id: string, judgment: string, 
/**
 * `loop.v1`.
 */
pack: string, question: string | null, label: unknown, 
/**
 * `operator`.
 */
source: string, weight: number, };
