// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.noticed` (step 24's notices, design §2.8b with `security.v3` in
 * `security.v1`'s place): Jev answered `risky` in its act band for a call
 * the gate let run without asking, so the owner hears of it after the
 * call, which never waited. Told to the turn's clients, best effort; the
 * `tool.notified` row (`by: judge`) is the record, and the owner's DM has
 * the notice with its right / wrong / noise buttons.
 */
export type JudgeNoticed = { session_id: string, turn_id: string, tool_use_id: string, correlation_id: string, tool: string, 
/**
 * The plan's summary of the call.
 */
summary: string, 
/**
 * `security.v3`.
 */
pack: string, 
/**
 * The judgment's id, its `judge.call` row's key: what a label names.
 */
judgment: string, 
/**
 * `live`.
 */
mode: string, 
/**
 * `risky`'s probability, 0 to 1, and as a whole percent.
 */
risky: number, percent: number, 
/**
 * The pack's other yes-or-no answers at or above their confirm line,
 * in short words with their percents (`sends data out 92%`).
 */
reasons: Array<string>, };
