// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.audit`'s params.
 */
export type JudgeAuditParams = { 
/**
 * A pack version (`loop.v1`), or its id for the wired version.
 */
pack: string, 
/**
 * How many judgments to sample.
 */
sample: number, 
/**
 * The model profile that answers (`[profiles.<name>]`).
 */
profile: string, 
/**
 * The sample's seed; none takes the run's.
 */
seed: number | null, };
