// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.replay`'s params. Exactly one of `candidate` and `pack_text`.
 */
export type JudgeReplayParams = { 
/**
 * An embedded version the build does not wire, by name (`loop.v2`).
 */
candidate: string | null, 
/**
 * A pack file's text (`--pack-file`): the daemon parses it with the
 * loader's every rule, and opens no path.
 */
pack_text: string | null, 
/**
 * The report whose holdout (or train split) is the set:
 * `rpt_<date>_<pack>`.
 */
report: string | null, 
/**
 * `holdout` (the default with a report) or `train`.
 */
split: string | null, 
/**
 * Only the labeled judgments the incumbent got wrong.
 */
errors: boolean, 
/**
 * The set by id (`jdg_…`), instead of a report's.
 */
judgments?: Array<string>, };
