// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassifyQuality } from "./ClassifyQuality";

/**
 * `judge.prove`'s result: the generator's report (`theseus_judge::prove`)
 * over the records the ledger gives, as its JSON and its Markdown.
 */
export type JudgeProveResult = { 
/**
 * `loop.v1`.
 */
pack: string, 
/**
 * The window of task ends read, unix ms; none is open on that side.
 */
since_ms: number | null, until_ms: number | null, 
/**
 * Where the window came from, in words.
 */
window: string, 
/**
 * The verdict: `insufficient`, `canary_better`, `canary_worse`, or
 * `no_difference`.
 */
verdict: string, 
/**
 * The report as the generator's JSON (`theseus_judge::prove::Report`).
 */
report: unknown, 
/**
 * The report as the generator's Markdown: what `theseus-judge prove`
 * writes over the same records, byte for byte.
 */
markdown: string, 
/**
 * Finished tasks read in the window.
 */
tasks: number, 
/**
 * Records by arm (`canary`, `control`).
 */
arms: { [key in string]: number }, 
/**
 * Tasks left out, by reason (`never_judged`, `no_arm`, `both_arms`,
 * `cancelled`, `unreadable`).
 */
left_out: { [key in string]: number }, 
/**
 * What the records cannot say yet, in words (the nudge's fields).
 */
notes: Array<string>, 
/**
 * Classification's decision quality against its baseline.
 */
classification: Array<ClassifyQuality>, 
/**
 * The records, as JSON lines, when asked.
 */
records?: string, 
/**
 * How long the build and the report took.
 */
elapsed_ms: number, };
