// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.audit`'s result.
 */
export type JudgeAuditResult = { 
/**
 * `aud_…`: the `judge.audit` row's key.
 */
id: string, pack: string, profile: string, model: string, seed: number, 
/**
 * Answered judgments with no audit label, and those sampled.
 */
eligible: number, sampled: number, 
/**
 * Requests sent, and those that failed.
 */
asked: number, failed: number, 
/**
 * Audit labels written; answers dropped (outside the options, or not
 * a question the pack asks).
 */
labels: number, dropped: number, 
/**
 * Why the run stopped before its sample, when it did.
 */
stopped: string | null, limit_usd: number, cost_usd: number, };
