// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.list` (M5 23b): the newest judgments, as their `judge.call` rows,
 * without their states (`judge.get` gives one with its state).
 */
export type JudgeListParams = { 
/**
 * One pack's (`loop.v1`); none, every pack's.
 */
pack: string | null, 
/**
 * One session's.
 */
session_id: string | null, 
/**
 * Those recorded at or after this time (unix ms).
 */
since: number | null, 
/**
 * How many, newest kept (default 50, at most 500).
 */
limit: number | null, };
