// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerEntry } from "./LedgerEntry";

export type JudgeListResult = { 
/**
 * The scopes read, one a pack (`judge:loop`): the listing's scope.
 */
scopes: Array<string>, 
/**
 * The judgments that matched, before the limit cut them.
 */
matched: number, 
/**
 * The newest `limit` of them, oldest first: each a `judge.call` row
 * (its `data` the judgment whole: pack, mode, answers with bands,
 * timing, cost, outcome, context, and `disagrees`).
 */
judgments: Array<LedgerEntry>, };
