// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The judge's shadow day budget (`[judge] shadow_limit_usd_per_day`).
 */
export type JudgeDayBudget = { enabled: boolean, 
/**
 * The local day, `YYYY-MM-DD`.
 */
day: string, limit_usd: number, spent_usd: number, 
/**
 * Today's judgments skipped at the limit.
 */
paused: boolean, };
