// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackReport } from "./PackReport";
import type { ReplayClassFell } from "./ReplayClassFell";
import type { ReplayEval } from "./ReplayEval";
import type { ReplayJudgment } from "./ReplayJudgment";
import type { ReplayLeftOut } from "./ReplayLeftOut";

/**
 * `judge.replay`'s result: the candidate beside the incumbent on the same
 * judgments, every number the learning report's.
 */
export type JudgeReplayResult = { 
/**
 * `rpl_…`: the `judge.replay` row's key.
 */
id: string, 
/**
 * `loop.v2`, and the sha256 of its text.
 */
candidate: string, candidate_sha256: string, incumbent: string, 
/**
 * `asks` (each state asked again) or `thresholds_only` (re-banded).
 */
change: string, 
/**
 * `holdout`, `train`, or `judgments`.
 */
set: string, report: string | null, errors: boolean, 
/**
 * Whose labels graded both sides: `frozen` (the report's, for its
 * holdout) or `today` (every label as of the run).
 */
labels: string, 
/**
 * The set's judgments, those asked, and how each state went.
 */
judgments: number, called: number, stored: number, rebuilt: number, rebanded: number, left_out: Array<ReplayLeftOut>, 
/**
 * The run's estimate, checked against `[judge] replay_limit_usd`, and
 * what it cost.
 */
estimate_usd: number, limit_usd: number, cost_usd: number, incumbent_report: PackReport, candidate_report: PackReport, 
/**
 * The share of asked judgments where the candidate's top answer to
 * every question equals the incumbent's.
 */
agreement: number | null, per_judgment: Array<ReplayJudgment>, fixed: number, broken: number, fell: Array<ReplayClassFell>, 
/**
 * A security candidate's planted-injection set, beside the incumbent.
 */
eval: ReplayEval | null, };
