// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.prove`'s params (M5 L3, row 50; design §2.9, "The prove"): the
 * exit report for `loop.v1`'s canary, from the ledger. A read: it writes
 * nothing.
 */
export type JudgeProveParams = { 
/**
 * The first local day of tasks that ended (`2026-10-01`). None: since
 * `loop.v1`'s latest move to canary, else everything.
 */
since: string | null, 
/**
 * The last local day (`2026-10-04`), whole. None: up to now.
 */
until: string | null, 
/**
 * Labeled tasks each arm needs before a rate is stated (default 30).
 */
min_tasks: number | null, 
/**
 * Labeled items each precision, recall, or rate needs (default the
 * learning report's per acting class).
 */
min_labeled: number | null, 
/**
 * Also answer the records, as the generator's JSON lines.
 */
records: boolean, };
