// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearnQuestion } from "./LearnQuestion";
import type { LearnThreshold } from "./LearnThreshold";

/**
 * One proposal (`judge.proposal`, `prp_…`): what the learning loop did for
 * one lineage, and why. Also `judge.learn`'s result.
 */
export type JudgeProposal = { id: string, 
/**
 * The lineage's root (`classify.v1`).
 */
root: string, 
/**
 * The version whose text was rewritten.
 */
parent: string, 
/**
 * The candidate (`classify.v101`), once the writer gave one that loads.
 */
version: string | null, sha256: string | null, 
/**
 * `nightly` or `owner`.
 */
trigger: string, 
/**
 * `interleaved` or `time`, with the time split's bounds.
 */
split: string, split_start_ms: number | null, split_end_ms: number | null, 
/**
 * The owner's labels the writer read (`lbl_…`), newest first, and
 * their judgments.
 */
errors: Array<string>, error_judgments: Array<string>, 
/**
 * New train errors found, of which `errors` the writer read.
 */
new_errors: number, 
/**
 * Labeled judgments on each side.
 */
train: number, holdout: number, replay: string | null, 
/**
 * Train errors the candidate fixed, and labeled answers it broke.
 */
fixed: number, broken: number, sufficient: boolean, parent_holdout: Array<LearnQuestion>, candidate_holdout: Array<LearnQuestion>, thresholds: Array<LearnThreshold>, 
/**
 * `live`, `canary`, `shadow`, `card`, `held`, `none` (too few errors),
 * `skipped` (a budget, an open proposal), or `refused` (the writer's
 * file).
 */
decision: string, why: string, 
/**
 * A security pack's approval card.
 */
question: string | null, writer_model: string | null, writer_usd: number, replay_usd: number, 
/**
 * The candidate's text against its parent's, line by line.
 */
diff: string, 
/**
 * The notice's sentence.
 */
said: string, };
