// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerEntry } from "./LedgerEntry";

export type JudgeListResult = { 
/**
 * The scopes read, one a pack (`judge:loop`): the listing's scope.
 */
scopes: Array<string>, 
/**
 * The judgments that matched, before the limit cut them: exact unless
 * `more`. The newest are read first, and a read stops one match past
 * the limit (theseus-wse2), so with `more` this is a floor: the limit's
 * judgments and the one older match that proves there are more.
 */
matched: number, 
/**
 * Older judgments match beyond those `matched` counts: `matched` is
 * then at least the number that match, not the number. False from a
 * daemon that counted them all.
 */
more: boolean, 
/**
 * The newest `limit` of them, oldest first: each a `judge.call` row
 * (its `data` the judgment whole: pack, mode, answers with bands,
 * timing, cost, outcome, context, and `disagrees`).
 */
judgments: Array<LedgerEntry>, };
