// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.get`: one judgment by its id.
 */
export type JudgeGetParams = { 
/**
 * `jdg_…`.
 */
id: string, };
