// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.learn`'s params (M5 25f): run the learning loop for one pack now,
 * the owner's act. `split` sets the boundary: train before it, holdout from
 * it until now (unix ms, an RFC 3339 time, a local day such as
 * `2026-10-04`, or a duration ago such as `2h`). Without it, the nightly
 * rule: interleaved below 200 labeled in the window, else the window.
 */
export type JudgeLearnParams = { 
/**
 * A version (`classify.v1`) or an id (`classify`): its lineage.
 */
pack: string, split?: string | null, };
