// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplayLeftOut } from "./ReplayLeftOut";

/**
 * `judge.backfill`'s result.
 */
export type JudgeBackfillResult = { 
/**
 * `bkf_…`: the `judge.backfill` row's key.
 */
id: string, pack: string, since_ms: number, until_ms: number, 
/**
 * The sha256 of the config the run read its consent from.
 */
consent: string, 
/**
 * Events in the window; those judged before (by the live point or an
 * earlier backfill, skipped), those judged now, and those left out.
 */
events: number, already: number, judged: number, failed: number, left_out: Array<ReplayLeftOut>, estimate_usd: number, limit_usd: number, cost_usd: number, };
