// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerEntry } from "./LedgerEntry";

export type JudgeGetResult = { 
/**
 * Its `judge.call` row.
 */
judgment: LedgerEntry, 
/**
 * The state Jev was sent, from its blob: named fields, as JSON. `None`
 * when the blob is missing or no longer matches its digest
 * (`state_missing` says which).
 */
state: unknown, state_missing?: string | null, };
