// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `judge.label`: an operator's label on one judgment (acting: the owner,
 * from a private place).
 */
export type JudgeLabelParams = { 
/**
 * `jdg_…`.
 */
judgment: string, 
/**
 * The question it labels (`work_state`); none labels the whole
 * judgment.
 */
question: string | null, 
/**
 * The label: as the module says, by the question's kind.
 */
label: unknown, note: string | null, 
/**
 * Set by the Discord binding alone (a notice's right / wrong / noise
 * press, step 24's notices): the channel and user the press came from,
 * which the core judges the label by, as it judges an answer.
 */
discord?: DiscordOrigin, };
