// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.scored` (M5 step 24, design §2.8b): a notified call's
 * `security.v1` judgment landed, after its notice. In shadow the score is
 * uncalibrated and acts on nothing; a notice line shows it as
 * `risk 12% (shadow)`. Live progress, best effort: the judgment's
 * `judge.call` row is the record.
 */
export type JudgeScored = { session_id: string, turn_id: string, 
/**
 * The call its notice named.
 */
tool_use_id: string, correlation_id: string, tool: string, 
/**
 * `security.v1`.
 */
pack: string, 
/**
 * The judgment's id, its `judge.call` row's key.
 */
judgment: string, 
/**
 * `shadow`.
 */
mode: string, 
/**
 * `risky`'s probability, 0 to 1.
 */
risky: number, 
/**
 * The same, as a whole percent.
 */
percent: number, };
