// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `judge.backfill`'s params.
 */
export type JudgeBackfillParams = { 
/**
 * A pack version (`loop.v1`), or its id for the wired version.
 */
pack: string, 
/**
 * The local day the window starts (`2026-10-01`); it ends now.
 */
since: string, };
