// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health's `judge` block.
 */
export type JudgeHealth = { 
/**
 * `[judge] enabled`. Off: nothing below is counted.
 */
enabled: boolean, 
/**
 * `[judge] max_mode`: the ceiling on every pack.
 */
max_mode: string, 
/**
 * Each wired pack and the mode it runs in now (`loop.v1: shadow`).
 */
packs: Array<string>, 
/**
 * The circuit breaker: `closed`, `open (Ns left)`, `half_open`, or
 * `idle` before the first judgment builds the client.
 */
breaker: string, 
/**
 * The breakers of their own (32d), each `<name>: <state>` as above:
 * `rerank: closed`. Their packs' failures move only them.
 */
breakers: Array<string>, in_flight: number, 
/**
 * The local day the counts below are of.
 */
day: string, 
/**
 * Judgments that reached Jev today, and those that failed there.
 */
calls_today: number, failed_today: number, 
/**
 * Judgments skipped today without a call: the shadow budget's pause,
 * shedding, the breaker, an unsettled key.
 */
skipped_today: number, 
/**
 * What shadow judgments spent today, and the day's limit, in dollars.
 */
spend_today_usd: number, shadow_limit_usd: number, 
/**
 * The shadow budget's limit is reached: shadow is paused until midnight.
 */
paused: boolean, 
/**
 * Shadow judgments shed for want of an in-flight permit since the
 * client was built (23b).
 */
shed: number, 
/**
 * The key's state (23b): `ready`, `resolving`, `failed: <why>`, or
 * `not configured` (`[judge] key_secret` names no `[secrets]` entry).
 * Never a value.
 */
key: string, 
/**
 * `security.v3`'s live notices (step 24's notices): `on`, `paused
 * until <day>: <rule>`, or `off`. Empty from a daemon before them.
 */
notices: string, };
