// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KernelStatus = { 
/**
 * Startup finished (five steps) and events are accepted.
 */
accepting: boolean, admission_ceiling: number, 
/**
 * Executions holding a turn right now.
 */
turns_held: number, 
/**
 * Counts by state: queued, running, waiting, blocked, cancelled, failed, budget_exhausted, complete.
 */
executions_by_state: { [key in string]: number }, 
/**
 * Counts by state: planned, authorized, dispatched, succeeded, failed, outcome_unknown, cancelled.
 */
actions_by_state: { [key in string]: number }, 
/**
 * Completions that matched no action (never inferred into anything).
 */
quarantined_completions: number, 
/**
 * The last startup: step timings in µs and what it recovered.
 */
startup: unknown, 
/**
 * The spend limit a new session gets, in US dollars (`[kernel]
 * spend_limit_usd`).
 */
spend_limit_usd: number, 
/**
 * What reaching it does (`[kernel] spend_limit_mode`, theseus-usei):
 * `notify` or `ask`. Unset from a build before it.
 */
spend_limit_mode?: string, 
/**
 * Job wrappers whose command has exited, each still waiting for the
 * descendants that outlived it (theseus-6qy).
 */
lingering_wrappers: number, };
