// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabelCounts = { operator: number, system: number, audit: number, system_written: number, };
