// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaterWake } from "./LaterWake";

/**
 * A turn's leftovers, as its daemon's kernel held them as the turn ended.
 */
export type Later = { 
/**
 * Jobs its turns left running (answered `background`), not yet settled.
 */
jobs: number, 
/**
 * A result came back that no turn has read yet: a turn for it is queued.
 */
queued: boolean, 
/**
 * Its pending wakes, the soonest first.
 */
wakes: Array<LaterWake>, };
