// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LatencyRow = { class: string, n: number, p50_ms: number | null, p95_ms: number | null, p99_ms: number | null, };
