// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pending wake.
 */
export type LaterWake = { wake_id: string, 
/**
 * When it is due, in Unix ms.
 */
due_at_ms: number, note: string, };
