// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `learning.report`: with `date`, the report stored for that local day;
 * without, the report run now (as the tender runs it), written and
 * returned. `pack` keeps one pack's (`loop.v1`, or `loop` for every
 * version).
 */
export type LearningReportParams = { pack: string | null, 
/**
 * `2026-10-04`, a local day.
 */
date: string | null, };
