// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One class's holdout numbers.
 */
export type LearnClass = { class: string, precision: number | null, recall: number | null, };
