// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelCounts } from "./LabelCounts";
import type { PackReport } from "./PackReport";

/**
 * One report: every pack version's, as of its run.
 */
export type LearningReport = { 
/**
 * The local day it is of.
 */
date: string, at_unix_ms: number, 
/**
 * `nightly`, `missed` (a night the daemon was down, run once after the
 * next start), or `on_demand`.
 */
trigger: string, 
/**
 * The labels the report read, by source, and the system labels this
 * run derived and wrote (a second run writes none again).
 */
labels: LabelCounts, packs: Array<PackReport>, };
