// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A threshold the re-fit moved (or kept), per question.
 */
export type LearnThreshold = { question: string, act_was: number, act: number, confirm: number, 
/**
 * Labeled train answers the re-fit read.
 */
train: number, };
