// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearnClass } from "./LearnClass";

/**
 * One question's holdout numbers on one side.
 */
export type LearnQuestion = { question: string, labeled: number, classes: Array<LearnClass>, 
/**
 * The mean of its classes' precisions, and of their recalls.
 */
precision: number | null, recall: number | null, };
