// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerEntry } from "./LedgerEntry";

export type LedgerTailResult = { rows: Array<LedgerEntry>, total: number, 
/**
 * With `after`: the `after` for the next page while more rows may
 * follow (the last row read, whether or not a filter kept it); absent
 * at the ledger's end, and without `after`.
 */
next?: number, 
/**
 * With `before`: the `before` for the next page back while older rows
 * match (the first row of this page); absent once none do, and
 * without `before`.
 */
older?: number, };
