// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LedgerEntry = { position: number, at_unix_ms: number, kind: string, session_id: string | null, turn_id: string | null, data: unknown, };
