// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One language server: up (`starting`, `loading`, or `ready`), or the last
 * start that `failed`.
 */
export type LspServerStatus = { 
/**
 * The server's name: a preset's (`rust-analyzer`), or the config's.
 */
server: string, 
/**
 * The workspace root it serves.
 */
root: string, 
/**
 * `starting` (before `initialize` answered), `loading` (answered, still
 * indexing), `ready`, or `failed`.
 */
state: string, pid?: number, 
/**
 * When it was started (or failed), in Unix ms.
 */
since_ms: number, 
/**
 * From its start to its readiness.
 */
ready_ms?: number, 
/**
 * The resident memory of its process group, read when health is asked.
 */
memory_kib?: number, 
/**
 * How long since a call last used it.
 */
idle_secs?: number, 
/**
 * Requests the tools sent it.
 */
requests: number, 
/**
 * Why its last start failed, or why it ended unasked.
 */
why?: string, };
