// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerStatus } from "./McpServerStatus";
import type { McpToolInfo } from "./McpToolInfo";

/**
 * `mcp.list`: every configured server and the tools offered.
 */
export type McpListResult = { servers: Array<McpServerStatus>, tools: Array<McpToolInfo>, };
