// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpPromptInfo } from "./McpPromptInfo";

export type McpPromptListResult = { prompts: Array<McpPromptInfo>, };
