// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `mcp.prompt.list`: the prompts of one server, or of every server.
 */
export type McpPromptListParams = { server?: string, };
