// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The prompt a `turn.submit` runs as its input (36c): the core asks the
 * server for it, and its messages become the turn's input nodes.
 */
export type McpPromptRef = { server: string, name: string, arguments: { [key in string]: string }, };
