// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpPromptArgument } from "./McpPromptArgument";

/**
 * One prompt a server lists (36c), as the operator picks it.
 */
export type McpPromptInfo = { server: string, 
/**
 * The prompt's own name, at its server.
 */
prompt: string, 
/**
 * `<server>/<prompt>`: what `/prompt` and `theseus prompt` name.
 */
name: string, title?: string, description?: string, arguments: Array<McpPromptArgument>, 
/**
 * The digest of its definition: its name, description, and arguments.
 */
digest: string, 
/**
 * Whether the list is the stored one, the server not having listed
 * prompts since the start.
 */
stored: boolean, };
