// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One argument a prompt takes.
 */
export type McpPromptArgument = { name: string, description?: string, required: boolean, };
