// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The MCP server's refusals, by why.
 */
export type McpServerRefusals = { 
/**
 * A `Host` that does not name the listener (DNS rebinding).
 */
host: number, 
/**
 * An `Origin` that is not a loopback page.
 */
origin: number, 
/**
 * No key, or a wrong one.
 */
key: number, 
/**
 * Past `requests_per_minute`.
 */
rate: number, 
/**
 * A connection whose client socket another uid owns.
 */
peer: number, };
