// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One MCP tool, as the model is offered it.
 */
export type McpToolInfo = { server: string, 
/**
 * The tool's own name, at its server.
 */
tool: string, 
/**
 * `mcp:<server>/<tool>`: what the gate and `[policy.mcp]` name.
 */
name: string, 
/**
 * `mcp__<server>__<tool>`: what the model calls.
 */
wire_name: string, 
/**
 * `read` or `run`.
 */
class: string, posture: string, 
/**
 * The setting the posture comes from.
 */
setting: string, 
/**
 * The server's own hints (`readOnlyHint`, `destructiveHint`,
 * `idempotentHint`, `openWorldHint`), shown, never loosening.
 */
hints?: Array<string>, 
/**
 * The description the model reads, whole (capped at 2,000 characters).
 */
description: string, calls: number, };
