// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memory.recalls`: a session's recalls, newest last.
 */
export type MemoryRecallsParams = { session_id: string, 
/**
 * The newest this many (default 10, at most 200).
 */
limit?: number, };
