// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SynthesisReport } from "./SynthesisReport";

/**
 * What a consolidation did, cluster by cluster.
 */
export type MemoryConsolidateResult = { dry_run: boolean, 
/**
 * The recall rows read (`recall.shadow`, `recall.ran`).
 */
recalls: number, clusters: Array<SynthesisReport>, 
/**
 * Components and clusters left out, by reason (`size`,
 * `not_a_source`, `synthesized`, `external`, `profiles_disagree`, …).
 */
skipped: { [key in string]: number }, 
/**
 * The local day's spend, this run's included, and its limit.
 */
spent_today_usd: number, limit_usd: number, 
/**
 * Why the run stopped before its last cluster, if it did.
 */
stopped?: string, };
