// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memory.search`: recall's pipeline over `query`, as a turn in
 * `session_id`'s place would run it, writing nothing. With no session, as
 * the CLI's: a private place.
 */
export type MemorySearchParams = { query: string, session_id?: string, 
/**
 * Hits asked of the index (default 40, at most 100).
 */
k?: number, 
/**
 * The arm whose sources and science rank it (`[memory] arm`'s names:
 * `baseline`, `bm25`, `+retention`, `+activation`, `+synthesis`); default
 * `baseline`.
 */
arm?: string, };
