// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdjacencyHealth } from "./AdjacencyHealth";
import type { RecallOutcomes } from "./RecallOutcomes";

/**
 * Health's memory block (M6): recall's mode and arm, the retention
 * projection (32a), and the adjacency projection spreading activation walks
 * (32b).
 */
export type MemoryHealth = { 
/**
 * `off`, `shadow`, `canary`, or `live`.
 */
mode: string, 
/**
 * The arm canary and live sessions get.
 */
arm: string, 
/**
 * The retention projection (32a): `unbuilt` (nothing has read it),
 * `building`, `ready`, or `failed` (`why` says why).
 */
retention: string, why?: string, 
/**
 * Nodes with a retention, and the events folded into them.
 */
nodes: number, events: number, 
/**
 * The adjacency projection (32b): absent while no arm reads it and no
 * search has built it.
 */
adjacency?: AdjacencyHealth, 
/**
 * Recall's recent outcomes (theseus-w9qv): absent until a turn has
 * recalled in this daemon's life.
 */
recalls?: RecallOutcomes, };
