// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdjacencyHealth } from "./AdjacencyHealth";

/**
 * Health's memory block (M6): recall's mode and arm, and the adjacency
 * projection spreading activation walks (32b).
 */
export type MemoryHealth = { 
/**
 * `off`, `shadow`, `canary`, or `live`.
 */
mode: string, 
/**
 * The arm canary and live sessions get.
 */
arm: string, 
/**
 * Absent while no arm reads it and no search has built it.
 */
adjacency?: AdjacencyHealth, };
