// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryLabelResult = { node_id: string, label: string, 
/**
 * Whether recall now leaves the node out.
 */
excluded: boolean, };
