// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memory.label` (M6 30b, §2.14): an operator's label on a node. `wrong`
 * and `stale` keep the node out of recall (`labeled_wrong`), and `useful`
 * lets it back; `should_have` says recall missed it.
 */
export type MemoryLabelParams = { node_id: string, 
/**
 * `useful`, `wrong`, `stale`, or `should_have`.
 */
label: string, 
/**
 * The recall that offered it, when one did.
 */
recall_id?: string, note?: string, };
