// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `memory.consolidate` (M6 31b): consolidation now. A dry run lists the
 * clusters it would synthesize, and writes nothing.
 */
export type MemoryConsolidateParams = { dry_run?: boolean, };
