// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NarrativeLine } from "./NarrativeLine";

export type NarrativeWatchResult = { 
/**
 * The most recent lines, oldest first; at most `capacity`.
 */
lines: Array<NarrativeLine>, capacity: number, };
