// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NarrativePart } from "./NarrativePart";

/**
 * One sentence of the narrative, filled into a fixed template from the
 * structure itself (never written by a model). Kept only in memory.
 */
export type NarrativeLine = { 
/**
 * Counts from 1 since the daemon started; a client merges the tail and
 * the live lines on it.
 */
seq: number, at_unix_ms: number, part: NarrativePart, session_id?: string, turn_id?: string, text: string, };
