// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `node.reach` (theseus-n4m, step 12a; design stage2 §2.11).
 */
export type NodeReachParams = { node_id: string, 
/**
 * How many generations of copies to follow: 3 by default, at most 16.
 * 0 answers the node's own session only.
 */
max_generations?: number, };
