// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `node.written`: a turn wrote a node.
 */
export type NodeWritten = { session_id: string, node_id: string, 
/**
 * `user_message`, `assistant_message`, `tool_call`, `tool_result`.
 */
kind: string, };
