// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The store's heat cache of decoded nodes (M6 step 33, theseus-6fn.13):
 * its bound (`[memory] node_cache_mb`; 0 is off), what it holds, and its
 * counts since the daemon started. A hit is a node served without a decode;
 * a miss, one decoded; `failed`, a stub whose node could not be read back.
 */
export type NodeCacheHealth = { cap_bytes: number, bytes: number, entries: number, hits: number, misses: number, decodes: number, evictions: number, failed: number, };
