// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeListParams = { session_id: string | null, kind: string | null, n: number | null, };
