// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReachDescendant } from "./ReachDescendant";
import type { ReachExposure } from "./ReachExposure";
import type { ReachTotals } from "./ReachTotals";

export type NodeReachResult = { node_id: string, session_id: string, position: number, direct: ReachExposure, descendants: Array<ReachDescendant>, totals: ReachTotals, 
/**
 * The walk stopped short: a node at `max_generations` has copies of
 * its own, or the walk reached its cap of copies.
 */
partial: boolean, };
