// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The structured notice a `notify` posture posts: to the session's channel
 * (Discord, web UI, CLI) and to the ledger (`tool.notified`).
 */
export type Notice = { 
/**
 * `notify`.
 */
kind: string, 
/**
 * The setting that chose the posture, e.g. `enforcement = notify`.
 */
setting: string, 
/**
 * The gate's reason, e.g. `proc.run — notify (enforcement = notify)`.
 */
rule: string, };
