// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.proposal.accept`: the operator's yes to a proposal. The
 * session joins the topic (an `operator`-origin membership, through the
 * ontology's write path) and the judgment gets its `judge.label` row, in
 * one frame. For `new_topic`, `topic` names the topic: an existing one, or
 * a new one made in the same frame, with `description`.
 */
export type OntologyProposalAcceptParams = { judgment: string, topic?: string, description?: string, 
/**
 * A new person's proposal accepted as this person (theseus-fvyx): a
 * held person by id or name, or else the name of the person the accept
 * declares; a bare first name beside its full name.
 */
as_person?: string, note?: string, author?: string, discord?: DiscordOrigin, };
