// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.proposal.reject_all` (theseus-fvyx): the operator's no to each
 * named proposal (one person's row), each as `ontology.proposal.reject`
 * takes it: its label, and nothing else.
 */
export type OntologyProposalRejectAllParams = { judgments: Array<string>, note?: string, author?: string, discord?: DiscordOrigin, };
