// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row of the kinds table.
 */
export type OntologyKind = { name: string, 
/**
 * `given` (the transport's facts) or `interpreted`.
 */
basis: string, 
/**
 * The origins that may assign a membership: `transport`, `operator`.
 */
assigned_by: Array<string>, 
/**
 * How many a session may hold: a number, or `many`.
 */
per_session: string, parent?: string, precedence: number, 
/**
 * `chain` or `intent_line`.
 */
rule: string, description: string, version: number, added_by: string, };
