// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.proposal.reject`: the operator's no; the judgment gets its
 * `judge.label` row, and nothing else changes.
 */
export type OntologyProposalRejectParams = { judgment: string, note?: string, author?: string, discord?: DiscordOrigin, };
