// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One proposal: a `categorize.v1` judgment's `topic` answer.
 */
export type OntologyProposal = { 
/**
 * The judgment (`jdg_…`), which `ontology.proposal.accept` and
 * `ontology.proposal.reject` name.
 */
judgment: string, session_id: string, session_title?: string, 
/**
 * The topic it proposes (`topic:harbor`); absent for `new_topic`.
 */
topic?: string, 
/**
 * The topic's name, as the ontology holds it now.
 */
topic_name?: string, 
/**
 * Jev's answer was `new_topic`: the messages share a subject no topic
 * covers, and the operator names it at accept.
 */
new_topic: boolean, 
/**
 * The top choice's probability.
 */
confidence: number, 
/**
 * `act`, `confirm`, or `escalate`, by the pack's thresholds.
 */
band: string, 
/**
 * When it was judged.
 */
at_ms: number, };
