// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OntologyProposalRejectAllResult = { rejected: Array<string>, 
/**
 * Named proposals left unanswered, each with why.
 */
left: Array<string>, };
