// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.person.merge` (theseus-wy7y): two people who are one. `survivor`
 * keeps its id and takes `absorbed`'s handles, memberships and guidance;
 * `absorbed` is written as merged into it, and the `ontology.merged` row
 * holds what moved, which `ontology.person.unmerge` reads to undo it. A DM's
 * person (the transport's) always survives. The owner's act, from a private
 * place.
 */
export type OntologyPersonMergeParams = { 
/**
 * Each by id, or by its name among the people.
 */
absorbed: string, survivor: string, 
/**
 * `ontology.person.unmerge`: undo the newest merge of `absorbed` (an id),
 * from its row; `survivor` is then ignored.
 */
undo: boolean, author?: string, discord?: DiscordOrigin, };
