// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyProposal } from "./OntologyProposal";

export type OntologyProposalsResult = { proposals: Array<OntologyProposal>, 
/**
 * Unanswered proposals past `limit`, left out.
 */
more: number, };
