// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyPersonProposals } from "./OntologyPersonProposals";
import type { OntologyProposal } from "./OntologyProposal";

export type OntologyProposalsResult = { proposals: Array<OntologyProposal>, 
/**
 * Unanswered proposals past `limit`, left out.
 */
more: number, 
/**
 * Unanswered proposals of a person the exclusions exclude (the owner,
 * his agents, the house's names: theseus-0p1r), not listed and never
 * taken in bulk; nothing deleted, nothing answered for the owner.
 */
hidden: number, 
/**
 * With `by_person`: one row per proposed person, most sessions first.
 */
people?: Array<OntologyPersonProposals>, 
/**
 * People past `limit`, left out.
 */
people_more: number, };
