// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.guidance.set`: a category's guidance, replaced whole. Empty
 * text takes it away. A session whose compilation carries it recompiles
 * once (`system_changed`) at its next turn.
 */
export type OntologyGuidanceSetParams = { 
/**
 * Its id, or its name among the topics.
 */
category: string, text: string, author?: string, discord?: DiscordOrigin, };
