// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ontology.proposals` (M5 28b): what `categorize.v1`, in shadow, proposed
 * and the operator has not answered: each answered judgment whose `topic`
 * names a topic its session is not in, or `new_topic`, newest first. Jev
 * writes no membership; the operator accepts or rejects each.
 */
export type OntologyProposalsParams = { 
/**
 * Only this session's.
 */
session_id?: string, 
/**
 * At most this many (default 50).
 */
limit?: number, };
