// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.proposal.accept_all` (theseus-wy7y): the operator's yes to every
 * unanswered proposal of a kind at or above a confidence, each as
 * `ontology.proposal.accept` would take it (a proposal naming a new topic
 * or person with no name is left for one at a time).
 */
export type OntologyProposalAcceptAllParams = { 
/**
 * `topic` or `person`; absent: both.
 */
kind?: string, 
/**
 * At least this top-choice probability (default 0).
 */
min_confidence: number, 
/**
 * Exactly these judgments (the cockpit's selection), else every match.
 */
judgments?: Array<string>, author?: string, discord?: DiscordOrigin, };
