// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `ontology.category.add`: the operator declares a category of an
 * interpreted kind (a topic). Its id is made from its name. Given kinds'
 * categories come from the transport, and are refused here.
 */
export type OntologyCategoryAddParams = { 
/**
 * Default `topic`.
 */
kind?: string, name: string, 
/**
 * The parent: its id, or its name among its kind's categories.
 */
parent?: string, description?: string, 
/**
 * A person's handles (theseus-wy7y): `discord:<id>`, `slack:<id>`,
 * `email:<addr>`, `name:<name>`. A handle another person holds exactly
 * (not a name) merges this one into that person instead.
 */
handles?: Array<string>, 
/**
 * Who made it, as a label. Default: the connection. It names and
 * proves nothing; the connection's surface decides.
 */
author?: string, discord?: DiscordOrigin, };
