// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One proposed person's proposals (theseus-fvyx): every unanswered
 * `people.v1` and `people_seen.v1` proposal of one person, a held person by
 * its id or a new one by its folded name, with one answer for them all
 * (`ontology.proposal.accept_all` with `judgments` and `as_person`, or
 * `ontology.proposal.reject_all`). A new person whose whole name is one
 * word that is a word of exactly one other person's name, proposed or
 * held, is listed inside that person (`first_names`) and accepted as them;
 * one with two or more such people is its own row, `ambiguous` naming them.
 */
export type OntologyPersonProposals = { 
/**
 * `person:<id>` for a held person, `name:<folded name>` for a new one.
 */
key: string, 
/**
 * The held person's name, or the name most of its proposals give.
 */
name: string, 
/**
 * No person holds it yet: the first accept declares it.
 */
new: boolean, 
/**
 * What `as_person` names at the group's accept: the held person's id,
 * or the name.
 */
as_person: string, 
/**
 * Every proposal of it, newest first.
 */
judgments: Array<string>, 
/**
 * The sessions they are for.
 */
sessions: number, 
/**
 * Their top-choice probabilities, least and greatest.
 */
confidence_min: number, confidence_max: number, 
/**
 * Their bands, the best first (`act`, `confirm`, `escalate`).
 */
bands: Array<string>, 
/**
 * The handles its proposals read.
 */
handles?: Array<string>, 
/**
 * The newest role line Jev kept.
 */
role_line?: string, 
/**
 * A few of its sessions' titles, newest first.
 */
titles?: Array<string>, 
/**
 * The bare first names listed inside it ("Marlo" beside "Marlo
 * Quill"), accepted as this person.
 */
first_names?: Array<string>, 
/**
 * A bare first name two or more people's names hold: their names. It
 * is never accepted in bulk; `as_person` picks one.
 */
ambiguous?: Array<string>, 
/**
 * The newest proposal's time.
 */
at_ms: number, };
