// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyMembership } from "./OntologyMembership";

/**
 * What an accept or a reject wrote.
 */
export type OntologyProposalAnswered = { judgment: string, session_id: string, 
/**
 * The label row's key (`lbl_…`).
 */
label_id: string, 
/**
 * `accepted` or `rejected`.
 */
label: string, 
/**
 * The topic the session joined (accept).
 */
topic?: string, 
/**
 * The session's interpreted memberships after it.
 */
memberships: Array<OntologyMembership>, };
