// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyGuidance } from "./OntologyGuidance";

/**
 * A category, with its guidance.
 */
export type OntologyCategory = { 
/**
 * `<kind>:<local>`: `topic:theseus`, `channel:<id>`.
 */
id: string, kind: string, name: string, parent?: string, 
/**
 * How deep it nests: a root is 1.
 */
depth: number, description: string, added_by: string, 
/**
 * Absent when it has none, or its guidance was taken away (empty text).
 */
guidance?: OntologyGuidance, 
/**
 * The sessions whose stored memberships hold it (an interpreted kind's;
 * a given one is read from a place, and counts none).
 */
members: number, 
/**
 * A person's handles (theseus-wy7y): `discord:<id>`, `slack:<id>`,
 * `email:<addr>`, `name:<display name>`; a DM's person holds its
 * `discord:<id>` without storing it.
 */
handles?: Array<string>, };
