// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OntologyCategory } from "./OntologyCategory";

/**
 * What a merge, or its undo, did.
 */
export type OntologyPersonMerged = { survivor: OntologyCategory, absorbed: string, 
/**
 * The sessions whose person lists moved.
 */
sessions: number, guidance_moved: boolean, 
/**
 * True for an undo.
 */
undone: boolean, };
