// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A binding's outbox (theseus-q4v): what waits to reach its channels.
 */
export type OutboxStatus = { 
/**
 * Posts written and not yet delivered.
 */
pending: number, 
/**
 * Posts delivered, in this store's life.
 */
sent: number, 
/**
 * Posts the channel refused for good (a deleted channel, lost access).
 */
failed: number, 
/**
 * When the oldest pending post was written (unix ms); 0 with none.
 */
oldest_pending_ms: number, 
/**
 * The last delivery error, and when (unix ms).
 */
last_error?: string, last_error_ms: number, };
