// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `pack.promote`: move a pack version up, to a canary share or live.
 */
export type PackPromoteParams = { 
/**
 * `loop.v1`.
 */
pack: string, 
/**
 * `canary` or `live`.
 */
to: string, 
/**
 * A canary's share, above 0 and at most 1.
 */
share?: number, 
/**
 * The learning report it cites (`rpt_<date>_<pack>`); none, the latest.
 */
report?: string, };
