// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackInfo } from "./PackInfo";

/**
 * `pack.list`'s answer.
 */
export type PackListResult = { 
/**
 * `[judge] enabled`: off, every pack is off whatever its rows say.
 */
enabled: boolean, 
/**
 * `[judge] max_mode`: the ceiling of every pack.
 */
max_mode: string, packs: Array<PackInfo>, };
