// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `pack.rollback`: the owner moves a pack version down to `rolled_back`.
 */
export type PackRollbackParams = { pack: string, why?: string, };
