// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldoutBounds } from "./HoldoutBounds";

/**
 * One `pack.mode` row, as the ladder reads it.
 */
export type PackModeRow = { 
/**
 * Where the row landed, and when: the record's, not in the row's data.
 */
position: number, at_unix_ms: number, 
/**
 * `loop.v1`.
 */
pack: string, 
/**
 * The mode it gives the version (or asked for, when `declined`).
 */
mode: string, 
/**
 * The mode before it.
 */
from: string, share?: number, 
/**
 * `owner` or `system`.
 */
who: string, 
/**
 * Who answered, as an approval names them, and through what.
 */
by: string, via: string, why: string, 
/**
 * The learning report it cites (`rpt_<date>_<pack>`), and its holdout's
 * bounds.
 */
report?: string, holdout?: HoldoutBounds, 
/**
 * The owner moved it up short of the bar.
 */
forced: boolean, 
/**
 * What was short, in numbers (`work_state: labeled 37 of 200`).
 */
numbers?: string, 
/**
 * A rollback's rule and its words.
 */
rule?: string, words?: string, 
/**
 * A day's brake lapses then (unix ms, a local midnight).
 */
until_ms?: number, 
/**
 * The approval card it answers (a security pack's promotion).
 */
question?: string, 
/**
 * The card was declined, or nobody answered it: the mode is unchanged.
 */
declined: boolean, };
