// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackModeRow } from "./PackModeRow";

/**
 * One pack version on the ladder.
 */
export type PackInfo = { 
/**
 * `loop.v1`.
 */
pack: string, 
/**
 * The ladder's mode: its latest row's, else `wired`'s.
 */
mode: string, 
/**
 * A canary's share of sessions, 0 to 1.
 */
share?: number, 
/**
 * What it does under the config's ceiling: `off`, `shadow`, `canary`,
 * or `live`.
 */
acts: string, 
/**
 * The line the build wires it at, its mode with no row.
 */
wired: string, 
/**
 * Why it is in its mode, as health says it (`owner: decision of
 * 2026-10-04`, `rolled back until 00:00 (notices_per_day)`).
 */
why: string, 
/**
 * A day's brake lapses at this local midnight (unix ms).
 */
until_ms?: number, 
/**
 * Its rollback rules: its file's, then those its adoption gives it.
 */
rules: Array<string>, 
/**
 * Its newest `pack.mode` rows, oldest first.
 */
rows: Array<PackModeRow>, 
/**
 * `compiled` (in the binary) or `learned` (25f: written by the
 * learning loop, its text in the store).
 */
source: string, 
/**
 * A learned version's parent, and the compiled-in version heading its
 * lineage.
 */
parent?: string, root?: string, 
/**
 * Whether it stands at its point now (a learned version placed, or a
 * root no learned version displaces).
 */
standing: boolean, 
/**
 * The pack file's text, for the diff between versions.
 */
text: string, };
