// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Holdout } from "./Holdout";
import type { LatencyRow } from "./LatencyRow";
import type { QuestionReport } from "./QuestionReport";

/**
 * One pack version's report: every judgment of it up to the run, and its
 * frozen holdout.
 */
export type PackReport = { 
/**
 * `loop.v1`.
 */
pack: string, calls: number, answered: number, failed: number, skipped: number, 
/**
 * Judgments with at least one label that counts toward a question.
 */
labeled: number, 
/**
 * What Jev is set beside (the pack's `baseline`).
 */
baseline: string, 
/**
 * Answered judgments that agree with the baseline, as a share: one
 * agrees unless its deciding questions reach the act verdict (23b's
 * `disagrees`, the rule behind `theseus.judge.disagreements`). None
 * with none answered.
 */
agreement: number | null, disagreements: number, cost_usd: number, 
/**
 * Latency per workload class (`task`, `reply`, `tools`, `inbound`, …):
 * each call that reached Jev, whole (`timing.total_ms`).
 */
latency: Array<LatencyRow>, questions: Array<QuestionReport>, holdout: Holdout, };
