// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackModeRow } from "./PackModeRow";

/**
 * `pack.promote`'s answer: the row it wrote, or the card it asked.
 */
export type PackPromoteResult = { row?: PackModeRow, 
/**
 * A security pack's card: its question's id, answered with
 * `action.confirm` (`theseus confirm <id> --approve`).
 */
question?: string, 
/**
 * What happened, in words.
 */
said: string, };
