// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task that waits on something that will not come by itself.
 */
export type ParkedTask = { 
/**
 * The task's session.
 */
task_id: string, short: string, execution_id: string, title?: string, 
/**
 * Its execution's state: `waiting` or `blocked`.
 */
state: string, 
/**
 * What holds it: `input` (a task gets none), `stopped`, `approval`,
 * `budget` (a question older than 24 hours), `blocked`, or `nothing`
 * (it waits with no wake).
 */
blocker: string, 
/**
 * The blocker, said.
 */
detail: string, 
/**
 * Since when (ms since the epoch): the question's, or the execution's
 * last change.
 */
since_ms: number, };
