// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A question waiting for the operator, in brief: the whole question, with its
 * input, is `confirm.requested`'s or `confirm.list`'s.
 */
export type PendingConfirm = { correlation_id: string, 
/**
 * The tool that asks (`proc.run`), or `budget.reset`.
 */
tool: string, 
/**
 * Why policy asks (`run cargo test`); empty when the server could not
 * read it.
 */
reason: string, 
/**
 * The floor asked: the call touches Theseus's own binary or state.
 */
floor: boolean, 
/**
 * A budget question: the session reached its spend limit.
 */
budget: boolean, 
/**
 * When the question stops holding; 0 for a budget question.
 */
expires_at_ms: number, };
