// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `import.people { propose }` did, or would do (theseus-wy7y).
 */
export type PeopleProposeReport = { 
/**
 * The tag's live imported sessions, and of those: done by an earlier
 * run (before the tag's mark), skipped for no human-facing text, and
 * read by this run (or, dry, that a run would read).
 */
sessions: number, done_before: number, no_text: number, read: number, 
/**
 * The extractor's input, estimated, over the sessions read.
 */
tokens: number, 
/**
 * The extractor's profile and model.
 */
profile: string, model: string, 
/**
 * Dry: the projected cost of the sessions left (the extractor's price
 * and Jev's); else what this run spent, both calls.
 */
projected_usd: number, spent_usd: number, cap_usd: number, 
/**
 * Candidates the extractor returned, those excluded before any call
 * (the owner, personas, agents, `[people] not_people`, a rejected or
 * held name), and Jev's judgments asked.
 */
candidates: number, excluded: number, judged: number, 
/**
 * Extractions that failed (each booked at its reservation).
 */
failed: number, 
/**
 * Sessions left after a stop (the cap, or the daemon's), and how to go
 * on from the tag's mark.
 */
left: number, stopped?: string, };
