// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceInfo } from "./PlaceInfo";
import type { PlaceWarning } from "./PlaceWarning";

/**
 * Health's `places` block: each place Theseus speaks in, and its class.
 */
export type PlacesHealth = { 
/**
 * The local surfaces first (the CLI and the web UI), then each place
 * the bindings file binds, in its order.
 */
places: Array<PlaceInfo>, 
/**
 * `public_paths`, as configured: the trees a shared place's file tools
 * may reach. Empty: a shared place gets no file tools.
 */
public_paths?: Array<string>, 
/**
 * What the binding's last start found wrong with its places
 * (theseus-ext.11): a place left unbound, a ceiling's unknown tool
 * family, a spend limit below one call.
 */
warnings?: Array<PlaceWarning>, };
