// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing the binding's start found wrong with a place (theseus-ext.11),
 * said in health, in the log, and as a `place.warned` row.
 */
export type PlaceWarning = { 
/**
 * `discord:channel:<id>` or `discord:dm:<user id>`.
 */
place: string, 
/**
 * `#lab`, `DM @zeroaltitude`.
 */
name: string, 
/**
 * `unbound` (its ceiling names a profile the config lacks: only it is
 * left unbound), `unknown_family` (a ceiling's tool family this daemon
 * has no tool of), or `limit_below_call` (its spend limit is below one
 * call's output reservation on its profile).
 */
kind: string, 
/**
 * The sentence that says it, with its figures.
 */
detail: string, };
