// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A place's ceiling (step 38a, theseus-ext.3): what the operator's bindings
 * file lets the place have, beneath what the place rule allows. It narrows
 * and never widens: a shared place's ceiling never offers it a private tool.
 * Each field absent is no narrowing.
 */
export type PlaceCeiling = { 
/**
 * No call here runs looser than this: `open`, `notify`, or `approve`.
 * A call's posture is the strictest of the config's, a tightening, this,
 * and an external-text hold; never a refusal.
 */
posture_floor?: string, 
/**
 * The tool families offered here (`fs`, `git`, `web`, `proc`, …), and
 * MCP servers as `mcp:<server>`.
 */
tools?: Array<string>, 
/**
 * The place's session's spend limit is the lower of this and `[kernel]
 * spend_limit_usd`.
 */
spend_limit_usd?: number, 
/**
 * The place's model, as a profile name, unless a turn names one.
 */
profile?: string, };
