// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalText } from "./ExternalText";
import type { PlaceCeiling } from "./PlaceCeiling";
import type { PlaceClass } from "./PlaceClass";
import type { ToolExplain } from "./ToolExplain";

/**
 * One place: what it is, and each tool there.
 */
export type PlaceExplain = { 
/**
 * `cli`, or the place's target (`discord:channel:<id>`).
 */
place: string, 
/**
 * `CLI`, `#pier`, `DM @owner`.
 */
name: string, class: PlaceClass, ceiling?: PlaceCeiling, 
/**
 * The session explained, when one was asked for (or the place's own).
 */
session_id?: string, 
/**
 * T1's hold: what the session read, so its calls that act wait.
 */
hold?: ExternalText, tools: Array<ToolExplain>, };
