// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceClass } from "./PlaceClass";

/**
 * One place and its class.
 */
export type PlaceInfo = { 
/**
 * `cli`, `web`, `discord:dm:<user id>`, or `discord:channel:<id>`.
 */
place: string, 
/**
 * How it is named: `CLI`, `web`, `DM @eddie`, `#openclaw`.
 */
name: string, class: PlaceClass, 
/**
 * A guild channel bound `private = true`, as the binding read it at its
 * start: the people besides the owner who can view it, by name. Absent
 * until it is read, or when it cannot be (`unchecked`).
 */
others?: Array<string>, 
/**
 * Why who can view it could not be read: the Server Members intent is
 * off, or Discord refused the read.
 */
unchecked?: string, };
