// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `place.publish` (the place rule's publish, theseus-nbsh): the owner, from
 * a private place, puts one item into a place's conversation: a node by id,
 * a file by path, or a message. Exactly one of the three.
 */
export type PlacePublishParams = { node_id?: string, 
/**
 * A file the owner can read, absolute or `~/`.
 */
path?: string, text?: string, 
/**
 * The place: `#openclaw`, `discord:channel:<id>`, or its id.
 */
to: string, 
/**
 * The owner's words above it.
 */
note?: string, 
/**
 * Who published it, as a label. Default: the connection. It names and
 * proves nothing; the connection's surface decides.
 */
author?: string, discord?: DiscordOrigin, };
