// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `policy.explain`'s params: one session's place, or every place; one
 * tool, or every tool the daemon has.
 */
export type PolicyExplainParams = { session_id?: string, 
/**
 * A canonical tool name (`proc.run`, `mcp:<server>/<tool>`).
 */
tool?: string, };
