// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceExplain } from "./PlaceExplain";

/**
 * `policy.explain`'s answer.
 */
export type PolicyExplainResult = { 
/**
 * The session's place, or the CLI then every bound place.
 */
places: Array<PlaceExplain>, 
/**
 * The workspace roots: each tool's result is for a call inside them.
 */
roots: Array<string>, };
