// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `policy.trust`: the session no longer holds external text.
 */
export type PolicyTrustParams = { session_id: string, 
/**
 * Who trusted it, as a label. Default: the connection. It names and
 * proves nothing; the connection's surface decides.
 */
author?: string, discord?: DiscordOrigin, };
