// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A profile's cache TTL (`5m` or `1h`), whether it inherited `[model]`'s,
 * and its keep-warm window in hours (0: none, as for every 5-minute one).
 */
export type ProfileTtl = { profile: string, model: string, ttl: string, inherited: boolean, keep_warm_hours: number, };
