// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileInfo } from "./ProfileInfo";

export type ProfileListResult = { live: string, 
/**
 * Where the live choice came from: "config" or "runtime" (persisted switch).
 */
live_source: string, profiles: Array<ProfileInfo>, };
