// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Progress = { steps_done: number, steps_total: number, current?: string, 
/**
 * The model's last word.
 */
said?: string, at_ms: number, };
