// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileTtl } from "./ProfileTtl";

/**
 * The prompt cache (theseus-ezeg): each profile's TTL and where it comes
 * from, and the keep-warm read's state. Absent from a daemon before it.
 */
export type PromptCacheHealth = { 
/**
 * Every profile, by name.
 */
profiles: Array<ProfileTtl>, 
/**
 * `[cache] keep_warm_minutes`: how long after a session's last call
 * its read goes.
 */
keep_warm_minutes: number, 
/**
 * Sessions kept warm now: in their window, their reads not stopped.
 */
kept: number, 
/**
 * Sessions whose reads stopped (refused or failed) until their next
 * message.
 */
stopped: number, 
/**
 * Today's reads (local day) and what they cost.
 */
reads_today: number, usd_today: number, };
