// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person a proposal names (theseus-wy7y): what the extractor read and Jev
 * kept. `new` when Jev matched no held person: an accept declares it (or
 * joins the held person an exact handle or name finds by then).
 */
export type ProposedPerson = { name: string, handles?: Array<string>, 
/**
 * What the person does or owns; absent when the text said nothing, or
 * Jev found the line judged the person rather than stating a role.
 */
role_line?: string, new: boolean, };
