// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";
import type { Usage } from "./Usage";

/**
 * `error.data` on a provider failure.
 */
export type ProviderErrorData = { class: string, transient: boolean, usage_unknown: boolean, turn_id: string | null, session_id: string, elapsed_ms: number, 
/**
 * The trace up to the failure.
 */
trace: Span | null, 
/**
 * What the turn's finished loops spent before it failed.
 */
usage: Usage, cost_usd: number | null, tool_calls: number, };
