// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionsHealth } from "./ConnectionsHealth";

/**
 * The push for health (theseus-in3): `push: 3 watchers · board 212 · 1
 * question · seeded in 38 ms`.
 */
export type PushStatus = { 
/**
 * The board was seeded: something watched since the daemon started. A
 * daemon nothing watches never pays for it.
 */
seeded: boolean, 
/**
 * How long the seed took, in microseconds.
 */
seed_us: number, 
/**
 * The executions the board holds.
 */
board: number, 
/**
 * The questions waiting for the operator, as the board holds them.
 */
questions: number, 
/**
 * Connections with an `executions.watch`.
 */
watchers: number, 
/**
 * `execution.changed` notifications made since the daemon started.
 */
events: number, 
/**
 * `session.wait` calls parked now.
 */
waiting: number, 
/**
 * Notifications dropped at a connection's backlog cap since the daemon
 * started, every stream's.
 */
lost: number, 
/**
 * The board's position: the last frame it applied.
 */
position: number, 
/**
 * The socket's connections and the descriptor limits they sit under
 * (theseus-7vtp).
 */
connections: ConnectionsHealth, };
