// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandShare } from "./BandShare";
import type { Calibration } from "./Calibration";
import type { ClassReport } from "./ClassReport";

/**
 * One question's numbers, over a set of judgments.
 */
export type QuestionReport = { question: string, 
/**
 * `choice`, `noul`, or `score`.
 */
kind: string, decides: boolean, answered: number, labeled: number, 
/**
 * Answers by band (`act`, `confirm`, `escalate`), each with its share.
 */
bands: Array<BandShare>, 
/**
 * A Choice's precision and recall, per class.
 */
classes: Array<ClassReport>, 
/**
 * A Noul's p against its label; a Choice's or Score's confidence
 * against whether its top answer was right. None with nothing labeled.
 */
calibration: Calibration | null, };
