// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerOption } from "./AnswerOption";
import type { QuestionKind } from "./QuestionKind";
import type { WorkRef } from "./WorkRef";

export type Question = { 
/**
 * The correlation id an answer names.
 */
id: string, kind: QuestionKind, asked_by: WorkRef, 
/**
 * `fs.write create projects/beta-summary.txt (40 B)`.
 */
prompt: string, detail?: string, input?: unknown, options: Array<AnswerOption>, 
/**
 * What happens if no one answers: `declined`, `not run`.
 */
on_expiry?: string, expires_at_ms?: number, 
/**
 * The floor asks: the call touches Theseus's own binary or state.
 */
floor: boolean, 
/**
 * This connection may answer it (the place rule).
 */
may_answer: boolean, 
/**
 * The tool that asks (`fs.write`, `budget.reset`), when one does.
 */
tool?: string, 
/**
 * When it was asked; on an execution's brief, when the execution came
 * to need you.
 */
asked_at_ms: number, 
/**
 * The call waits because its session read external text: an approval
 * may trust the session again (`action.confirm`'s `trust`).
 */
external_text?: boolean, 
/**
 * An `ask`'s own choices, in order.
 */
choices?: Array<string>, };
