// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReachCompilation } from "./ReachCompilation";

/**
 * A copy of the node in another session, found by walking the edges into
 * it: generation 1 copies the node, generation 2 a copy, and so on.
 */
export type ReachDescendant = { node_id: string, session_id: string, position: number, generation: number, 
/**
 * The edge's kind: `derived_from`.
 */
via: string, 
/**
 * The route that wrote the edge: `report` or `brief`.
 */
route: string, 
/**
 * The node it copies, one generation up.
 */
from: string, compilations: Array<ReachCompilation>, loops: number, first_ms?: number, last_ms?: number, };
