// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReachCompilation } from "./ReachCompilation";

/**
 * Where a node was seen in its own session: the compilations that hold it,
 * and the loops whose context held it (a model call made after it was
 * written, whose compilation holds it or left it in the tail). A context is
 * a compilation or a loop. The first and last exposure are absent when it
 * was never seen.
 */
export type ReachExposure = { compilations: Array<ReachCompilation>, loops: number, first_ms?: number, last_ms?: number, };
