// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span of time a question named (theseus-w9qv): "March 2026", "last
 * week", read from its words in the owner's time zone. Recall keeps to the
 * nodes whose own time is inside it: an imported message's (inside its
 * episode's as-of span; its summary's is the span's end), a native node's
 * creation. Either end may be open.
 */
export type RecallWhen = { 
/**
 * The words that named it, as the question wrote them.
 */
said: string, 
/**
 * Its start, unix ms.
 */
from_ms?: number, 
/**
 * Its end, unix ms, not included.
 */
to_ms?: number, };
