// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexSourceRank } from "./IndexSourceRank";
import type { RecallRetention } from "./RecallRetention";

/**
 * An item the pack would admit: a reference, never a copy.
 */
export type RecallItem = { node_id: string, chunk: number, session_id: string, position: number, kind: string, 
/**
 * Its place in the science's order, from 1.
 */
rank: number, fused: number, 
/**
 * Each source's rank and score.
 */
sources?: { [key in string]: IndexSourceRank }, 
/**
 * Its excerpt's tokens.
 */
tokens: number, 
/**
 * The excerpt itself: `memory.search` and `memory.recalls` give it; the
 * row does not keep it.
 */
text?: string, 
/**
 * Under `+retention` (32a): its node's retention as the rank read it.
 */
retention?: RecallRetention, };
