// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recalled node's FSRS-6 retention at the recall (M6 32a): what the
 * `+retention` arm weighed.
 */
export type RecallRetention = { 
/**
 * The chance of recall at the turn's time, 0 to 1.
 */
retrievability: number, 
/**
 * Days until retrievability falls to 0.9.
 */
stability: number, 
/**
 * 1 to 10.
 */
difficulty: number, 
/**
 * The last review, in ms since the epoch.
 */
last_review_ms: number, };
