// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a live rerank did to a recall (M6 32d): the turn waited at most
 * `[memory] rerank_wait_ms` from its start for `rerank.v1`'s answer.
 */
export type RecallRerank = { 
/**
 * `jdg_…`, the rerank's judgment; none when nothing was sent.
 */
judgment?: string, 
/**
 * Jev's order is what the pack admitted from.
 */
applied: boolean, 
/**
 * Why recall's own order stood: `timeout` (the wait ended first; the
 * answer, when it comes, is recorded `late`), `breaker_open`,
 * `budget`, `nothing_eligible`, or the call's fallback (`model_drift`,
 * a failure's class, a skip's reason).
 */
why?: string, 
/**
 * How long the turn waited, from the rerank's start.
 */
waited_ms: number, 
/**
 * The wait's bound.
 */
wait_ms: number, };
