// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What spreading activation did in a recall (M6 32b): its seeds, the nodes
 * it reached, the index's hits it ranked (each gains its term), and the
 * nodes it added that the index did not return. An item's rank and score
 * in it are its `sources.activation`.
 */
export type RecallActivation = { 
/**
 * `ran`, or why it did not: `building` (the projection is built after
 * serving), `deadline` (recall's ran out first), `no_hits`, or the
 * projection's error.
 */
outcome: string, why?: string, seeds: number, 
/**
 * The new node's entities the spread read: the query's, as the
 * index's hits matched them.
 */
entities?: Array<string>, reached: number, 
/**
 * The index's hits it reached, each gaining its term.
 */
boosted: number, 
/**
 * The reached nodes the index did not return, joined as candidates.
 */
added: number, 
/**
 * Of the admitted items, those it ranked, and those it alone found.
 */
admitted: number, admitted_added: number, 
/**
 * The projection as the spread read it.
 */
nodes: number, edges: number, 
/**
 * The projection's refresh and the spread, and the added nodes' reads.
 */
took_ms: number, };
