// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecallRetention } from "./RecallRetention";

/**
 * A candidate dropped, and why: `place`, `in_context`, `untrusted`,
 * `recursion`, `threshold`, or `budget`.
 */
export type RecallDrop = { node_id: string, chunk: number, session_id: string, reason: string, fused: number, 
/**
 * A `budget` drop's tokens.
 */
tokens?: number, 
/**
 * Under `+retention` (32a): its node's retention, as for an item, so a
 * node a label dropped still shows what the label did to it.
 */
retention?: RecallRetention, };
