// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the last turns' recalls went (theseus-w9qv), counted in memory since
 * the daemon started: the index's answer to the query as asked (`ok`; a
 * source the tender could not answer, such as vectors without weights, is in
 * its `skipped`), the word sources' alone when the vector search missed the
 * deadline or failed (`words_only`), nothing in time (`deadline`), and no
 * index to ask (`error`).
 */
export type RecallOutcomes = { 
/**
 * The most recalls counted: the newest this many.
 */
window: number, 
/**
 * Recalls counted, at most `window`.
 */
turns: number, ok: number, words_only: number, deadline: number, error: number, 
/**
 * When an answer last came from every source it asked for (nothing
 * skipped), in ms since the epoch: absent when none has since the start.
 */
last_full_ms?: number, };
