// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetReport } from "./BudgetReport";
import type { RecallDrop } from "./RecallDrop";
import type { RecallItem } from "./RecallItem";
import type { RecallTimings } from "./RecallTimings";

/**
 * One recall: what the index offered, what the pack would admit, and why
 * each other candidate was dropped. A turn's `recall.shadow` row is one,
 * and so is `memory.search`'s answer.
 */
export type RecallManifest = { 
/**
 * `rcl_<id>`.
 */
recall_id: string, 
/**
 * `shadow` (a turn's: nothing reaches the model) or `search`
 * (`memory.search`).
 */
mode: string, 
/**
 * The science and its parameters' digest (`baseline@<digest>`).
 */
science: string, 
/**
 * `ran`, `deadline` (the index did not answer in time; the turn went
 * on), or `unavailable` (no index answered: `why` says why).
 */
outcome: string, why?: string, session_id?: string, turn_id?: string, 
/**
 * Where the turn speaks: `private`, or `shared:<target>`.
 */
place: string, 
/**
 * The query's length in characters, and its SHA-256's first 16 hex
 * digits: the row keeps no copy of the text.
 */
query_chars: number, query_digest: string, 
/**
 * Only nodes written before this position were candidates.
 */
as_of?: number, 
/**
 * The position the index held every node through, as it answered.
 */
indexed_through?: number, 
/**
 * The hits the index answered with.
 */
candidates: number, 
/**
 * Each source's hits among them (`bm25`, `entity`, `vector`).
 */
sources?: { [key in string]: number }, 
/**
 * Sources that did not answer, and why (the model loading).
 */
skipped?: { [key in string]: string }, admitted: Array<RecallItem>, dropped: Array<RecallDrop>, 
/**
 * The drops by reason.
 */
drops?: { [key in string]: number }, 
/**
 * The pack's limit, and what the admitted items would take.
 */
budget_tokens: number, used_tokens: number, timings: RecallTimings, 
/**
 * The session's arm (M6 30b): `baseline` for recall in front of the
 * model, or the control's `none` with `baseline` in shadow.
 */
arm?: string, 
/**
 * The pack's budget: its limit, what it used, and each item it dropped
 * for the budget (§2.11: never silently thinner).
 */
budget?: BudgetReport, };
