// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side of the planted-injection set (a security candidate's).
 */
export type ReplayEvalSide = { pack: string, 
/**
 * Expectations met and missed, over every judged case.
 */
met: number, missed: number, 
/**
 * Cases whose call failed or was skipped.
 */
unanswered: number, };
