// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One judgment, replayed: how its state went, and the questions the
 * candidate fixed (the incumbent wrong, the candidate right, by the label)
 * and broke (the reverse).
 */
export type ReplayJudgment = { 
/**
 * The incumbent's judgment it re-asks.
 */
judgment: string, 
/**
 * The candidate's judgment (`jdg_…`), when one was called.
 */
replayed: string | null, 
/**
 * `stored` (sent as it was), `rebuilt` (from its inputs), or
 * `rebanded` (a thresholds-only candidate: no call).
 */
state: string, fixed: Array<string>, broken: Array<string>, };
