// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Choice class whose precision or recall fell with the candidate.
 */
export type ReplayClassFell = { question: string, class: string, precision_fell: boolean, recall_fell: boolean, };
