// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A judgment the replay could not ask, and why.
 */
export type ReplayLeftOut = { judgment: string, reason: string, };
