// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheHealth } from "./CacheHealth";
import type { HeapHealth } from "./HeapHealth";
import type { TrimHealth } from "./TrimHealth";

/**
 * The daemon's resident memory and its largest caches.
 */
export type ResidentHealth = { 
/**
 * The process's resident set (`/proc/self/statm`), in bytes.
 */
rss_bytes: number, 
/**
 * The allocator's heap: absent where it cannot be read (a musl build).
 */
heap?: HeapHealth, 
/**
 * Trims since the start: each gives the allocator's free pages back
 * after a quiet stretch that followed work.
 */
trims: number, 
/**
 * The newest trim.
 */
last_trim?: TrimHealth, 
/**
 * The largest caches, each with its size and its bound.
 */
caches: Array<CacheHealth>, };
