// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Access } from "./Access";

/**
 * A path a call will touch, already resolved against the context.
 */
export type Resource = { path: string, access: Access, };
