// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a session is retired.
 */
export type RetiredReason = "superseded" | "empty" | "by_hand";
