// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subtree counted by level.
 */
export type Rollup = { needs_you: number, working: number, done: number, failed: number, total: number, };
