// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One correction in the layer.
 */
export type RouteCorrectionInfo = { id: string, label?: string, pack: string, session_id: string, turn_id: string, 
/**
 * Where a close message runs: a profile, or `mode <id>`.
 */
to: string, 
/**
 * The corrected message's content words, which a close message shares.
 */
words: Array<string>, at_ms: number, };
