// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a correction did.
 */
export type RouteCorrectResult = { 
/**
 * The correction's id (`rcx_…`), its `route.corrected` row's key.
 */
correction: string, turn_id: string, 
/**
 * The owner's label it wrote, when the turn's mode was wrong.
 */
label?: string, judgment?: string, 
/**
 * Where the session runs from its next turn, when it moves.
 */
profile?: string, 
/**
 * One line that says it.
 */
line: string, };
