// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteCorrectionInfo } from "./RouteCorrectionInfo";

/**
 * `route.corrections`: the live correction layer, a read.
 */
export type RouteCorrectionsResult = { 
/**
 * The route pack version acting; entries of any other have retired.
 */
pack: string, 
/**
 * Newest first.
 */
entries: Array<RouteCorrectionInfo>, max_entries: number, similarity: number, 
/**
 * Entries retired since the daemon started.
 */
retired: number, enabled: boolean, };
