// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `route.correct` (theseus-q31l): the owner's correction of a turn's
 * routing, from a reaction, a footer's control, the cockpit, or the CLI.
 * Judged as `judge.label` is: the owner, from a private place.
 */
export type RouteCorrectParams = { session_id: string, 
/**
 * The turn corrected; absent: the session's last turn routing decided.
 */
turn_id?: string, 
/**
 * Where it should have run: a profile (`fable`), a profile's model, a
 * mode of the acting route pack (`deep_coding`), `stronger` or `cheaper`.
 */
to: string, 
/**
 * What the owner corrected with: `reaction`, `button`, `cockpit`, `cli`.
 */
via?: string, 
/**
 * Its id there (a reaction's message and emoji, a press's interaction).
 */
provenance?: string, 
/**
 * The binding's reading of where it came from, as `judge.label`'s.
 */
discord?: DiscordOrigin, };
