// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finished } from "./Finished";

/**
 * The policy's numbers, as the owner's thread decided them: data, so a
 * config section can tune them later without code.
 */
export type Rules = { 
/**
 * A root that worked this long interrupts when it is done: 5 minutes.
 */
long_run_ms: number, 
/**
 * A question is reminded of once, at this share of its life: half.
 */
remind_at: number, finished: Finished, 
/**
 * At most one Interrupt per root in this window: 10 s.
 */
burst_ms: number, };
