// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An L1 job that runs, before its `tool.job_started` row is written: what
 * that row will say it ran (theseus-kpz1).
 */
export type RunningJob = { correlation_id: string, session_id: string, tool: string, 
/**
 * Its command, as its row's `argv` will have it.
 */
argv: Array<string>, 
/**
 * When its wrapper was launched (unix ms).
 */
started_at_ms: number, };
