// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An L1 launch, as a job's completion reports it (theseus-gyin): health's
 * last one since the start, and `theseusd check`'s self-test.
 */
export type SandboxLaunch = { 
/**
 * The job started in L1.
 */
ok: boolean, 
/**
 * When it was launched (unix ms).
 */
at_ms: number, 
/**
 * Why not, when it did not: the stage, and the error.
 */
why?: string, 
/**
 * The start, from the spawn to the command's exec, in ms.
 */
start_ms?: number, 
/**
 * A fresh sysfs was mounted (the kernel may refuse it).
 */
sys?: boolean, 
/**
 * `lo` came up in the job's network namespace.
 */
lo?: boolean, 
/**
 * `[sandbox] ro_paths` that do not exist, so a job is given none of
 * them.
 */
skipped?: Array<string>, };
