// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunningJob } from "./RunningJob";

/**
 * `sandbox.usage`: the L1 jobs running now, read when asked. An L1 job has
 * no cgroup of its own to read (theseus-gyin).
 */
export type SandboxUsage = { 
/**
 * When it was read (unix ms).
 */
at_ms: number, 
/**
 * The L1 jobs running now whose `tool.job_started` row is not written
 * yet (theseus-kpz1): it rides the turn's next frame, after the job ends
 * or its turn stops waiting for it, so until then their commands are
 * here, from the daemon's memory.
 */
running?: Array<RunningJob>, };
