// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretFailed } from "./SecretFailed";
import type { SecretSource } from "./SecretSource";

/**
 * Where the vault's secrets stand (theseus-qa0, spec §2 FAST): the daemon
 * answers its socket before they resolve, and each consumer waits for its own.
 */
export type SecretsStatus = { 
/**
 * `resolving` until every secret has settled, then `ready`, or `failed`
 * with `failed` naming each one that did not resolve.
 */
state: string, ready: Array<string>, resolving: Array<string>, failed: Array<SecretFailed>, 
/**
 * How the vault was read: `inject` (one `op inject` for every reference),
 * or `inject, then read` after a failed injection.
 */
method: string | null, 
/**
 * Rounds run: the first, then one per retry of what failed.
 */
rounds: number, 
/**
 * When resolution began, and when its first round settled, in ms after
 * the process started.
 */
started_ms: number | null, settled_ms: number | null, 
/**
 * Until the next fetch of what failed.
 */
retry_in_ms: number | null, 
/**
 * The secrets whose values come from outside the vault, the recommended
 * source (theseus-n88g.1): an `env:` or `file:` entry, by name and
 * source. Empty when every secret is the vault's.
 */
outside_vault?: Array<SecretSource>, };
