// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `self.log`'s params.
 */
export type SelfLogParams = { 
/**
 * Only rows at this time or after (unix ms).
 */
since_ms?: number, 
/**
 * At most this many rows (default 50, at most 500).
 */
limit?: number, };
