// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfState } from "./SelfState";

/**
 * `self.halt`'s and `self.resume`'s answer: the state after it, and
 * whether this call moved the switch (a halt of a halted switch does not).
 */
export type SelfSwitchResult = { state: SelfState, changed: boolean, };
