// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `self.halt`'s params. Anyone who may speak to the daemon may halt.
 */
export type SelfHaltParams = { 
/**
 * Why, in the halter's words.
 */
why?: string, 
/**
 * Who, as a label; set by the Discord binding.
 */
author?: string, 
/**
 * Set by the Discord binding: the channel and user it came from.
 */
discord?: DiscordOrigin, };
