// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfMode } from "./SelfMode";

/**
 * The kill switch and the mode, as every surface shows them.
 */
export type SelfState = { mode: SelfMode, 
/**
 * Whether the switch holds every self step. A store that has never seen
 * the owner's resume is halted.
 */
halted: boolean, 
/**
 * The owner has never resumed: halted from the first day.
 */
never_resumed?: boolean, 
/**
 * When the switch last moved, who moved it and from where, and why (a
 * halt's words).
 */
at_ms?: number, by?: string, via?: string, why?: string, 
/**
 * What a self step would hear now: `off`, `halted` or `allowed`.
 */
gate: string, };
