// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `self.digest`'s params: the week that ends at `until_ms` (default now).
 */
export type SelfDigestParams = { until_ms?: number, };
