// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `self.digest`'s answer: the week's text, and its window.
 */
export type SelfDigestResult = { since_ms: number, until_ms: number, text: string, rows: number, };
