// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One change Theseus made to itself, or one move of its switch.
 */
export type SelfLogRow = { position: number, at_unix_ms: number, kind: string, 
/**
 * What changed, in a sentence.
 */
what: string, why?: string, 
/**
 * The numbers it carries (a cost, a replay's fixed and broken, a share).
 */
numbers?: unknown, 
/**
 * The command that reverses it, where there is one.
 */
undo?: string, session_id?: string, };
