// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `self.resume`'s params: only the owner, from a private place, counts.
 */
export type SelfResumeParams = { author?: string, discord?: DiscordOrigin, 
/**
 * The `THESEUS_SESSION` of the shell that sent it, which the CLI sends:
 * a job's shell never resumes, and its refusal is ledgered.
 */
from_job?: string, };
