// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfLogRow } from "./SelfLogRow";
import type { SelfState } from "./SelfState";

/**
 * `self.log`'s answer: the rows, newest first, and the switch now.
 */
export type SelfLogResult = { rows: Array<SelfLogRow>, state: SelfState, 
/**
 * More rows matched past `limit`.
 */
more: boolean, 
/**
 * The ledger's index is still being built after a start: nothing could
 * be read yet, so the list is empty for now, not empty for good.
 */
building?: boolean, };
