// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInfo } from "./SessionInfo";

export type SessionListResult = { sessions: Array<SessionInfo>, 
/**
 * With `n`: the `before` for the next page back while older sessions
 * remain; absent at the first one, and without `n`.
 */
older?: number, };
