// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One end of a supersession: the other session, and when the place moved.
 */
export type SessionLink = { session_id: string, at_ms: number, 
/**
 * The place whose binding moved (`dm:<user>`, `channel:<id>`).
 */
place?: string, };
