// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session.reopen`: clears a retirement (by hand, superseded, or empty).
 * A superseded session keeps both links as history, and its place stays
 * on its successor.
 */
export type SessionReopenParams = { session_id: string, };
