// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the daemon did with the notice.
 */
export type SessionTypingResult = { 
/**
 * True when it started a warm-up: false when the session had one within
 * the idle spell, or the typist is not one the daemon warms for.
 */
started: boolean, 
/**
 * Why not, in words, when it did not start.
 */
why?: string, };
