// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetiredReason } from "./RetiredReason";

/**
 * A retirement: why, and when. Stored for `superseded` and `by_hand`;
 * derived for `empty` (its time the end of the grace).
 */
export type SessionRetired = { reason: RetiredReason, at_ms: number, };
