// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a session is now (theseus-emqx).
 */
export type SessionState = "live" | "quiet" | "retired";
