// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordOrigin } from "./DiscordOrigin";

/**
 * `session.typing`: someone began to type into `session_id` (none yet:
 * a new session's first words). Fire and forget: the answer says only
 * whether the daemon took the notice, and nothing on a turn's path waits
 * for what it starts.
 */
export type SessionTypingParams = { session_id?: string, 
/**
 * Who is typing, as `turn.submit`'s `author` names them (a label).
 */
author?: string, 
/**
 * Where it came from, for the Discord binding: the daemon warms only
 * for an owner's typing, never for another person in a shared place.
 */
discord?: DiscordOrigin, };
