// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attention } from "./Attention";
import type { ExternalText } from "./ExternalText";
import type { SessionKind } from "./SessionKind";
import type { Usage } from "./Usage";

export type SessionInfo = { session_id: string, kind: SessionKind, label: string | null, created_at_unix_ms: number, turns: number, 
/**
 * Cumulative tokens over every turn in this session.
 */
usage: Usage, 
/**
 * The session's one execution (spec §3.2a) and its current state.
 */
execution_id?: string, execution_state?: string, last_active_ms: number, cost_usd: number, tool_calls: number, 
/**
 * Profile/provider/model of the last turn (continuations reuse it).
 */
profile?: string, model?: string, compilation_id?: string, 
/**
 * First words of the first prompt, for pickers.
 */
title?: string, 
/**
 * Tool calls in this session waiting for the operator's confirmation.
 */
pending_confirms: number, 
/**
 * A task session's parent (DD7): the session that started it.
 */
parent_session_id?: string, 
/**
 * A task's carved limit, in US dollars.
 */
limit_usd?: number, 
/**
 * The session holds external text (theseus-9bp): what it read, and
 * since when. Its calls that act wait until the operator trusts it.
 */
external_text?: ExternalText, 
/**
 * What its execution needs from people, by `attention()` (theseus-in3).
 */
attention?: Attention, };
