// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session.retire`: the owner retires a session by hand. Nothing is
 * deleted, and `session.reopen` undoes it.
 */
export type SessionRetireParams = { session_id: string, };
