// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

export type SessionOpenParams = { kind: SessionKind | null, label: string | null, 
/**
 * The session whose job opened this one (`JOB_SESSION_ENV`, theseus-b5cl):
 * one opened from a session that holds external text holds it too.
 */
opened_from?: string, };
