// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a compile is for (M6 35a, §2.11): the compiler's input that decides
 * what a request may admit. The compile step tells what it holds; a compile
 * whose own triggers recompile (a model, system, or tools change, the ring)
 * settles as `recompile` with its trigger.
 */
export type Situation = { "kind": "conversation_start" } | { "kind": "task_start" } | { "kind": "continuation" } | { "kind": "recompile", trigger: string, } | { "kind": "resume" } | { "kind": "detour" } | { "kind": "unknown" };
