// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One timed span of a turn trace. Times are microseconds from the turn's
 * start; a mark has `end_us == start_us`. Children are in start order.
 */
export type Span = { name: string, 
/**
 * turn | loop | provider | tool | mark | advancer | store | lock | compile.
 * Traces stored before theseus-hco also hold `hook` spans.
 */
kind: string, start_us: number, end_us: number | null, attrs?: unknown, children?: Array<Span>, };
