// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeCacheHealth } from "./NodeCacheHealth";

/**
 * The store's reads (R4, theseus-15g). After the history check finds a
 * frame corrupt (the `store.verify` phase), a read of one of its records is
 * refused. A list read skips it instead of failing whole, and counts it
 * here, so a corrupt record degrades what reads it rather than stopping
 * every continuation, and says so.
 */
export type StoreStatus = { 
/**
 * Records list reads skipped since the daemon started, each once.
 */
refused_records: number, 
/**
 * The first of their WAL positions, lowest first.
 */
refused_positions: Array<number>, 
/**
 * What repairs it, when any are refused: `theseusd restore --repair`
 * with a copy of the store that holds the frame whole.
 */
repair?: string, 
/**
 * The heat cache of decoded nodes (M6 step 33): absent from a daemon
 * before it.
 */
node_cache?: NodeCacheHealth, };
