// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attachment a request sent as its one line, not its text
 * (theseus-ezeg): its message, its place among the message's files, its
 * name, and the tokens its text is estimated at. The stored message keeps
 * it whole.
 */
export type StubbedFile = { node_id: string, index: number, name: string, tokens: number, };
