// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an answer looks on a button.
 */
export type Style = "primary" | "plain" | "danger";
