// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One cluster's synthesis, or what a dry run would ask.
 */
export type SynthesisReport = { 
/**
 * The digest of its sources' ids.
 */
cluster: string, sources: Array<string>, 
/**
 * The distinct turns that admitted its weakest pair together.
 */
turns: number, profile: string, 
/**
 * `would_propose` (a dry run), `supported`, `unchecked`, `rejected`, or
 * `failed`.
 */
outcome: string, synthesis_id?: string, text?: string, why?: string, cost_usd: number, };
