// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a turn's request showed of the task graph (`context.compiled`):
 * absent when its scope has no task.
 */
export type TaskViewSummary = { 
/**
 * The view's text's digest.
 */
digest: string, open: number, closed: number, 
/**
 * Lines shown, and the tasks left out past the bound.
 */
lines: number, left_out: number, 
/**
 * Its size, estimated.
 */
tokens: number, };
