// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckOverlap } from "./CheckOverlap";
import type { CheckPiece } from "./CheckPiece";

/**
 * What a check task was admitted, what it was kept from, and on what model.
 */
export type TaskCheck = { 
/**
 * The task it checks: its session's id, and how people name it.
 */
checked_task: string, checked_short: string, 
/**
 * The checked task's report: its last message, in its own session,
 * which the check reads as a claim, and when it was written.
 */
report_node: string, report_at_ms: number, 
/**
 * The sessions none of whose other nodes reach the check: the checked
 * task's.
 */
excluded_sessions: Array<string>, 
/**
 * What the check reads after its brief, in order.
 */
admitted: Array<CheckPiece>, 
/**
 * What the check runs on: the call's `profile`, or its parent's.
 */
profile: string, provider: string, model: string, 
/**
 * The spans of 12 words or more that its brief or its own pieces share
 * with a node of the checked task's session. The check still runs.
 */
overlaps?: Array<CheckOverlap>, at_ms: number, };
