// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParkedTask } from "./ParkedTask";

/**
 * Health's `tasks` block (M5 28b; the parked-task invariant, theseus-vug).
 */
export type TasksHealth = { 
/**
 * Each task in progress that cannot progress by itself: no running
 * turn, queue place, job, wake of its own, or pending question younger
 * than 24 hours. Read from the open executions alone.
 */
parked: Array<ParkedTask>, };
