// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A claim's lease on a task (39b, M7 §2.4): the execution that holds it,
 * its session (how a refusal names it), and when it lapses. The holder's own
 * edits renew it; a close ends it; past `until_ms` it reads free, and the
 * due pass clears it (`task.lease_expired`).
 */
export type TaskClaim = { 
/**
 * `exe_…`.
 */
by: string, session: string, until_ms: number, };
