// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who asked for a task: the session its creating call ran in, and that
 * session's principal (the requester a layer-1 change waits for).
 */
export type TaskOrigin = { session: string, principal: string, };
