// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A question's task, when a task asks it (DD7): the card names it.
 */
export type TaskRef = { task_id: string, short: string, title?: string, };
