// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskClaim } from "./TaskClaim";
import type { TaskEvidence } from "./TaskEvidence";
import type { TaskOrigin } from "./TaskOrigin";
import type { TaskProposal } from "./TaskProposal";
import type { TaskState } from "./TaskState";

/**
 * A task (§2.4).
 */
export type TaskRecord = { 
/**
 * `tsk_…`.
 */
id: string, 
/**
 * Moves by one at every change to it; an edit names the one it read.
 */
version: number, title: string, 
/**
 * Layer 1: what it is for, the operator's.
 */
objective: string, 
/**
 * Layer 1: how to know it is done, one line each.
 */
acceptance: Array<string>, state: TaskState, parent?: string, 
/**
 * Tasks it waits on.
 */
deps: Array<string>, 
/**
 * `agent`, or a principal.
 */
owner: string, 
/**
 * The task's own session, when it delegates (DD7).
 */
session?: string, origin: TaskOrigin, 
/**
 * Layer 3: append-only.
 */
evidence: Array<TaskEvidence>, proposal?: TaskProposal, 
/**
 * The lease one execution holds on it (39b; format 17).
 */
claim?: TaskClaim, created_at_ms: number, updated_at_ms: number, };
