// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskRecord } from "./TaskRecord";

/**
 * `task.changed`: a task's record after a change, with the verb that made
 * it (`created`, `updated`, `split`, `closed`, `change_proposed`,
 * `change_accepted`, `change_declined`).
 */
export type TaskChanged = { 
/**
 * The session whose call or answer changed it.
 */
session_id: string, verb: string, task: TaskRecord, };
