// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of a task's evidence (layer 3): a node and its identity (a
 * commit, a job id, a snapshot id). Nothing removes one.
 */
export type TaskEvidence = { 
/**
 * The node that holds it: a report, or the reply that closed the task.
 */
node?: string, 
/**
 * `commit:<sha>`, `job:<id>`, `report:<task>`, or the model's own words.
 */
identity: string, note?: string, 
/**
 * Who added it: a session, or `report`.
 */
by: string, at_ms: number, };
