// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskInfo } from "./TaskInfo";
import type { TaskRecord } from "./TaskRecord";

export type TaskListResult = { tasks: Array<TaskInfo>, 
/**
 * The task records (39a), each task once: its graph, sessions' and plan items'.
 */
records: Array<TaskRecord>, };
