// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `task.get`: one task's record, by its id or the end of it.
 */
export type TaskGetParams = { id: string, };
