// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task's state (§3.5's machine). A task with a session shows its
 * execution's running state when read (`in_progress`, `waiting_human`,
 * `suspended`); its record is written at its own changes only.
 */
export type TaskState = "proposed" | "accepted" | "in_progress" | "blocked" | "waiting_human" | "suspended" | "done" | "failed" | "abandoned";
