// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrangementPiece } from "./ArrangementPiece";

/**
 * A task's arrangement, as `TaskInfo` carries it.
 */
export type TaskArrangement = { 
/**
 * The node in the task's session that holds the pieces.
 */
node_id: string, 
/**
 * Every piece, in the order the call gave them.
 */
pieces: Array<ArrangementPiece>, 
/**
 * The call said `fidelity_ack: true`: a one-line brief from a long
 * discussion, with a single piece, started anyway.
 */
fidelity_ack?: boolean, };
