// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A layer-1 change waiting for the requester, else the owner (§2.4): it
 * asks through the gate as a call that always waits, and its question is
 * `card`. Accept applies it in one frame; decline leaves the task.
 */
export type TaskProposal = { objective?: string, acceptance?: Array<string>, 
/**
 * It abandons the task ("abandoning is not completing").
 */
abandon?: boolean, 
/**
 * The session that proposed it.
 */
by: string, 
/**
 * The question that asks it (an action's correlation id).
 */
card: string, 
/**
 * The version it was proposed against: accept applies it only there.
 */
base_version: number, at_ms: number, };
