// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The layer-1 change a question asks (39b): the task, its title, the field,
 * and the field before and after; or abandoning it (`field` `abandon`, its
 * state before). The card on Discord, `theseus confirm`, and the cockpit
 * word it the one way (`question`).
 */
export type TaskChange = { task: string, title: string, 
/**
 * `objective`, `acceptance`, `objective and acceptance`, or `abandon`.
 */
field: string, before: string, after: string, };
