// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A long-lived child the daemon supervises (roadmap row 51; M6 §2.2): the
 * index tender. It starts 2 s after serving, never on the start path; it is
 * restarted whenever it exits, 1 s after the first exit, the wait doubling to
 * 60 s while it keeps failing; and a stop sends it SIGTERM and never waits.
 */
export type TenderStatus = { 
/**
 * What it tends: `index`.
 */
name: string, 
/**
 * `pending` (not started yet: it starts 2 s after the daemon's socket
 * answers, at `next_start_ms`), `running`, `backoff` (it exited, and starts again at
 * `next_start_ms`), `absent` (its binary is not installed beside the
 * daemon's: `why`), or `stopped` (the daemon is stopping, and sent it
 * SIGTERM, or restarts in place and keeps it).
 */
state: string, 
/**
 * Its pid, while it runs.
 */
pid?: number, 
/**
 * It was already running when this image started (a restart onto the
 * vault's changed note keeps the pid, and so its children): the core
 * took it over instead of starting a second.
 */
adopted: boolean, 
/**
 * When its process started, unix ms.
 */
started_at_ms: number, 
/**
 * Starts after the first: one for each exit.
 */
restarts: number, 
/**
 * How its last run ended (`exit 1`, `signal 9`), and when.
 */
last_exit?: string, last_exit_ms: number, 
/**
 * In `backoff`: when it starts again, unix ms.
 */
next_start_ms?: number, 
/**
 * The wait after its next exit: 1 s, doubling to 60 s, and 1 s again
 * after a run of a minute.
 */
backoff_ms: number, 
/**
 * Why it is not running, in words.
 */
why?: string, 
/**
 * The binary it runs.
 */
binary?: string, };
