// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open terminal.
 */
export type TerminalInfo = { 
/**
 * Its id, as `term.open` gave it (`t3`).
 */
id: string, session_id: string, 
/**
 * Its program, by its file name.
 */
program: string, pid: number, rows: number, cols: number, opened_at_unix_ms: number, 
/**
 * Its program still runs.
 */
running: boolean, 
/**
 * The listed program that makes its screen outside text, when one does
 * (`[policy] external_programs`).
 */
external?: string, 
/**
 * Bytes its program wrote, and bytes typed into it.
 */
bytes_out: number, bytes_in: number, last_output_unix_ms: number, };
