// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A process a terminal's close left running (theseus-ggqf): it was in the
 * background when its session ended or the daemon stopped, and runs on, as
 * a `proc.run` job's background process does. Listed while it runs.
 */
export type TerminalLeft = { pid: number, 
/**
 * Its program, by its process name.
 */
program: string, 
/**
 * Why the close left it: "a background job" (a group of its own in the
 * terminal's session) or "its own session (setsid, or a daemon)".
 */
why: string, 
/**
 * The terminal that started it, its program, and its session.
 */
terminal: string, terminal_program: string, session_id: string, left_at_unix_ms: number, };
