// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A runtime tightening (theseus-sgh, spec §3.9): one press on a notice made
 * a tool ask first from then on. The gate applies it after the config's
 * posture, and the stricter of the two wins, so it never loosens anything.
 */
export type Tightening = { 
/**
 * The tool's canonical name (`proc.run`).
 */
tool: string, 
/**
 * What the tool asks at least: `approve`.
 */
posture: string, 
/**
 * Who pressed, as a label (`discord:zeroaltitude`, `sock#3`, `web#1`).
 */
by: string, 
/**
 * Who pressed, as the approval rule knows them: a Discord user by id,
 * anyone else by label.
 */
who: string, 
/**
 * The channel it came through, as `[approval].channels` names it
 * (`cli`, `web`, `discord:dm`, `discord:<channel id>`).
 */
via: string, at_ms: number, 
/**
 * The call whose notice was pressed. With `digest` and `tool`, it is a
 * labeled example for later judgment work (Jev, M5). A press from the
 * CLI without `--call` names none.
 */
correlation_id?: string, session_id?: string, 
/**
 * The call's proposal digest (its action's `args_digest`).
 */
digest?: string, };
