// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tightening } from "./Tightening";

/**
 * What a tighten or an undo did, and the tool's posture now. Also the
 * params of `policy.tightened` and `policy.untightened`, where a field a
 * notification lacks reads as its default (theseus-0g4).
 */
export type TightenResult = { tool: string, 
/**
 * Who made this change: the one who pressed, or the one who undid it.
 */
by: string, 
/**
 * The tightening recorded (tighten) or removed (untighten).
 */
tightening: Tightening, 
/**
 * The posture the gate applies to the tool now, and the setting that
 * chose it.
 */
posture: string, setting: string, 
/**
 * What the config alone says.
 */
config_posture: string, config_setting: string, 
/**
 * The tool's posture changed. False for a press under a config that
 * already asks, and for an undo the config still asks under.
 */
changed: boolean, 
/**
 * The tool was tightened already, so nothing was recorded.
 */
already: boolean, };
