// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tool.started`: a call runs. A job's says how, and what the broker gave
 * it; a call that is not a job's has none of those fields.
 */
export type ToolStarted = { session_id: string, turn_id: string, tool_use_id: string, tool: string, correlation_id: string, 
/**
 * `harness`, `inproc`, or `job`.
 */
backend: string, 
/**
 * A job's wrapper's pid.
 */
pid?: number, argv?: Array<string>, cwd?: string, 
/**
 * What the secret broker gave a job, by name (`gh got GH_TOKEN`): `null`
 * for nothing (theseus-dcy).
 */
granted?: string | null, 
/**
 * What a job was not given (`git got no GIT_TOKEN`).
 */
withheld?: Array<string>, 
/**
 * A job's class (M4 17b): `l1` when it runs in the sandbox. Absent: L0.
 */
class?: string, 
/**
 * An L1 job's egress list (M4 18c): the hosts its proxy lets it reach,
 * empty for no network at all. Absent at L0.
 */
egress?: Array<string>, };
