// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExplainCondition } from "./ExplainCondition";
import type { ExplainLayer } from "./ExplainLayer";

/**
 * One tool in one place.
 */
export type ToolExplain = { tool: string, 
/**
 * `read`, `write`, or `run`.
 */
class: string, 
/**
 * Offered to the model here. One not offered is refused if called,
 * and `refused` says why.
 */
offered: boolean, refused?: string, 
/**
 * Every layer in the gate's order, for a call inside the roots that no
 * condition below matches.
 */
layers: Array<ExplainLayer>, 
/**
 * The layers that depend on the call, with their entries.
 */
conditions?: Array<ExplainCondition>, 
/**
 * `open`, `notify`, `approve`, or `refused`.
 */
result: string, 
/**
 * The gate's reason for that call, as its record would keep it.
 */
reason: string, };
