// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a tool does: read, write, or run a program. The tools' type
 * (`theseus_tools` re-exports it), here since a plan carries a call's own.
 */
export type ToolClass = "read" | "write" | "run";
