// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tightening } from "./Tightening";

export type ToolInfo = { 
/**
 * Canonical name (`fs.read`).
 */
name: string, 
/**
 * Name on the wire (`fs_read`).
 */
wire_name: string, family: string, description: string, 
/**
 * `read`, `write`, or `run`.
 */
class: string, 
/**
 * `inproc` or `job`.
 */
backend: string, 
/**
 * The posture the gate applies now: `open`, `notify`, or `approve`.
 */
policy: string, 
/**
 * What chose it: a config setting (`enforcement = notify`), or a
 * tightening (`tightened by discord:zeroaltitude`).
 */
setting: string, 
/**
 * What the config alone says (theseus-sgh). It differs from `policy`
 * only while a tightening is stricter.
 */
config_posture: string, config_setting: string, 
/**
 * Someone pressed "should have asked" for this tool.
 */
tightened?: Tightening, input_schema: unknown, 
/**
 * Calls since the daemon started.
 */
calls: number, 
/**
 * Calls whose input did not parse as JSON, since the daemon started
 * (theseus-9dt2): the cost of a tool whose input streams as it is written.
 */
invalid_json: number, };
