// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One trim: when, how long it took, and the resident set it gave back.
 */
export type TrimHealth = { at_ms: number, ms: number, rss_before_bytes: number, rss_after_bytes: number, };
