// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalText } from "./ExternalText";

/**
 * What a trust cleared, and who cleared it: `policy.trust`'s result, and the
 * params of `session.trusted`.
 */
export type TrustResult = { session_id: string, 
/**
 * Who trusted it, as a label.
 */
by: string, 
/**
 * Who, as the approval rule knows them, and the channel it came through.
 */
who: string, via: string, 
/**
 * `policy.trust`, or `action.confirm` for an approval that trusted the
 * session too.
 */
how: string, 
/**
 * The approval that trusted it, when one did.
 */
correlation_id?: string, at_ms: number, 
/**
 * The hold it cleared.
 */
held: ExternalText, 
/**
 * When the hold began, in the daemon's local time (theseus-qiy), as
 * health's `since_local`. Empty from a daemon before it.
 */
since_local?: string, };
