// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How routing placed one turn.
 */
export type TurnRoute = { 
/**
 * The mode the route pack answered (`trivial`, `quick` since route.v2,
 * `chat`, `sophisticated`, `deep_coding`, `routine_coding`, `other`),
 * when a verdict was read.
 */
mode?: string, 
/**
 * `verdict`, `detour`, `capped`, `fallback`, `cache_hold`, `unsure`,
 * `late`, `unreachable`, `no_verdict`, `pinned`, or `shadow`.
 */
reason: string, 
/**
 * The profile the session ran on before routing.
 */
from: string, 
/**
 * route.v3's answer about the reply's effort (`low`, `medium`, `high`,
 * `xhigh`, `max`, or `unclear`), when a verdict was read (theseus-qe3v).
 */
effort?: string, 
/**
 * Why the turn ran at its effort, beside `effort`: `applied`, `clamped`
 * (to `[routing] effort_bounds`), `unsure`, `unclear`, `fixed` (the
 * profile's `effort_fixed`), `no_effort` (its model takes none),
 * `carried` (a late verdict's), or `recorded` (shadow, or a pin).
 */
effort_reason?: string, 
/**
 * The effort Jev's answer set on the turn's requests, when it applied:
 * `effort` itself, or the bound it was clamped to.
 */
effort_applied?: string, };
