// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { McpPromptRef } from "./McpPromptRef";

export type TurnSubmitParams = { 
/**
 * Omit to open a fresh conversation session for this turn.
 */
session_id: string | null, input: string, 
/**
 * Profile for this turn (a configured profile name); default is the live profile.
 */
profile: string | null, 
/**
 * Raw override of the profile's provider for this turn.
 */
provider: string | null, 
/**
 * Raw override of the profile's model for this turn.
 */
model: string | null, 
/**
 * `profile` is carried from the session's last turn (the CLI's pane),
 * not the owner's choice: routing may still move the turn (M5 25e).
 */
carried?: boolean, 
/**
 * Who wrote the input, as a label on the message node (e.g. `discord:zeroaltitude`).
 * Default: the connection's own label. A label, not an authority: every
 * local protocol client acts as the operator.
 */
author?: string, 
/**
 * Files that came with the input, in order (theseus-9g2). With any, the
 * input may be empty.
 */
attachments?: Array<Attachment>, 
/**
 * The surface's message this turn answers (a Discord message id): the
 * reply's first message is posted as a reply to it (theseus-q4v).
 */
reply_to?: string, 
/**
 * The session whose job sent this turn (theseus-b5cl): the session the
 * turn opens or names takes its hold of external text.
 */
opened_from?: string, 
/**
 * An MCP server's prompt as the turn's input (M7 36c): the core asks
 * the server for it, and `input` stays empty. Only a private place's
 * session may run one.
 */
prompt?: McpPromptRef, 
/**
 * The directory the session works in (theseus-aab7), as
 * `SessionOpenParams.dir`: the session this turn opens is created
 * there, and a session named by `session_id` moves there. Absent: a new
 * session takes the daemon's `[tools] cwd`, and a named one keeps its
 * own.
 */
dir?: string, };
