// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";
import type { TurnFallback } from "./TurnFallback";
import type { TurnRoute } from "./TurnRoute";
import type { Usage } from "./Usage";

export type TurnSubmitResult = { session_id: string, turn_id: string, loops: number, output: string, 
/**
 * Why the Advancer ended the turn.
 */
stop_reason: string, 
/**
 * The provider's own stop reason for the last loop.
 */
provider_stop_reason: string | null, model: string, provider: string, 
/**
 * Profile the turn ran under ("" when raw overrides bypassed profiles entirely).
 */
profile: string, usage: Usage, elapsed_ms: number, 
/**
 * Time to the first streamed token of the last loop.
 */
first_token_ms: number | null, 
/**
 * Provider request id of the last loop, for support tickets.
 */
request_id: string | null, 
/**
 * Every timed thing in the turn, nested: turn > loops > provider/tools/advancer.
 */
trace: Span | null, execution_id: string | null, 
/**
 * Dollars for this turn's provider calls, from the model catalog (None: model not in catalog).
 */
cost_usd: number | null, 
/**
 * What the session has cost in all, this turn included (theseus-c0bb).
 */
session_cost_usd?: number, tool_calls: number, 
/**
 * Set when the turn parked waiting for the operator to confirm this action.
 */
awaiting_confirm: string | null, 
/**
 * The provider's `stop_details` (a refusal's category).
 */
stop_details: unknown, 
/**
 * The turn ran without new input (a continuation: late results, a confirm answer, a restart).
 */
continuation: boolean, 
/**
 * The notes recall put in front of the model this turn (M6 30b: canary and live; never shadow).
 */
recalled?: number, 
/**
 * How routing placed the turn (M5 25e); absent when it was not asked.
 */
route?: TurnRoute, 
/**
 * A refusal moved the turn to its model's fallback (theseus-7gir.18); absent when none did.
 */
fallback?: TurnFallback, };
