// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How routing placed one turn.
 */
export type TurnRoute = { 
/**
 * The mode the route pack answered (`trivial`, `quick` since route.v2,
 * `chat`, `sophisticated`, `deep_coding`, `routine_coding`, `other`),
 * when a verdict was read.
 */
mode?: string, 
/**
 * `verdict`, `detour`, `capped`, `fallback`, `cache_hold`, `unsure`,
 * `late`, `unreachable`, `no_verdict`, `pinned`, or `shadow`.
 */
reason: string, 
/**
 * The profile the session ran on before routing.
 */
from: string, 
/**
 * `correction` when the owner's correction (or the live layer's entry
 * close to this message) placed the turn ahead of the verdict
 * (theseus-q31l); absent when the verdict did.
 */
source?: string, };
