// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A refusal's client-side fallback in one turn (theseus-7gir.18): the model
 * that declined, the one its request went to instead, for the rest of the
 * turn, and the refusal's category. `line` is the one wording every surface
 * shows (`cockpit/src/lib/fallback.ts` mirrors it).
 */
export type TurnFallback = { from: string, to: string, 
/**
 * The refusal's `stop_details.category` (`cyber`), when it named one.
 */
category?: string, 
/**
 * `to` answered: false when it declined too, or never ran (the spend
 * limit, a stop, a failed call).
 */
answered: boolean, };
