// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How routing placed one turn.
 */
export type TurnRoute = { 
/**
 * The mode `route.v1` answered (`trivial`, `chat`, `sophisticated`,
 * `deep_coding`, `routine_coding`, `other`), when a verdict was read.
 */
mode?: string, 
/**
 * `verdict`, `detour`, `capped`, `fallback`, `cache_hold`, `unsure`,
 * `late`, `no_verdict`, `pinned`, or `shadow`.
 */
reason: string, 
/**
 * The profile the session ran on before routing.
 */
from: string, };
