// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A notification's params: a field it lacks reads as its default, as the
 * renderers always read them (theseus-0g4).
 */
export type TurnStarted = { session_id: string, turn_id: string, execution_id: string | null, continuation: boolean, };
