// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How urgently a notice asks for the owner.
 */
export type Urgency = "quiet" | "inform" | "interrupt";
