// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Usage = { input_tokens: number, output_tokens: number, cache_read_input_tokens: number, 
/**
 * Every cache write, whatever its TTL.
 */
cache_creation_input_tokens: number, 
/**
 * Of `cache_creation_input_tokens`, those written with the 1-hour TTL
 * (Anthropic's `usage.cache_creation.ephemeral_1h_input_tokens`), which
 * cost 2 × input against 1.25 × for the rest (theseus-ev1). Absent when
 * 0, so a row or record from before it reads as none.
 */
cache_creation_1h_input_tokens?: number, };
