// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who a notice would reach, as the surface knows them.
 */
export type Viewer = { 
/**
 * The work or session on the viewer's screen.
 */
focused?: string, 
/**
 * The position of the work's view the viewer last saw; 0 for none.
 */
seen: number, 
/**
 * How long the viewer has been away (the terminal lost focus); 0 while
 * present. Focus counts only while present.
 */
away_ms: number, 
/**
 * The viewer asked for no pings (`--notify off`).
 */
quiet: boolean, 
/**
 * A ping may make a sound.
 */
sound: boolean, };
