// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The binding's voice, for health and `theseus health`.
 */
export type VoiceStatus = { 
/**
 * off | ready | joined
 */
state: string, 
/**
 * The voice place joined.
 */
channel?: string, 
/**
 * Whom it hears there, by name: the place's users.
 */
hears: Array<string>, 
/**
 * Since when, while joined.
 */
since_ms?: number, 
/**
 * Since the start: calls joined, utterances transcribed, sentences
 * synthesized, barge-ins, stops that resumed (theseus-qb8o), failed
 * calls.
 */
joins: number, utterances: number, sentences: number, barge_ins: number, resumes: number, failures: number, 
/**
 * The speech heard, and the characters spoken.
 */
heard_ms: number, spoken_chars: number, 
/**
 * What speech cost since the start, booked to its sessions.
 */
spend_micros: number, last_error?: string, 
/**
 * The call joined but hears nothing (theseus-d93y): since when, until
 * it hears a listed speaker.
 */
deaf_since_ms?: number, 
/**
 * This call's rejoins for deafness: at most one.
 */
rejoins: number, 
/**
 * The rejoin heard nothing either: the call stays, deaf.
 */
deaf_failed: boolean, };
