// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `session.wait` waits for (design `stage2` §2.6).
 */
export type WaitUntil = "blocked" | "settled" | "terminal";
