// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `wake.list`: every pending wake, soonest first, or only one session's, or
 * only those whose turns post to one place.
 */
export type WakeListParams = { session_id?: string, 
/**
 * Only the wakes whose turns post to this place (`discord:dm:<user>`).
 */
target?: string, };
