// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `wake.cancel`: cancel a pending wake, so nothing fires.
 */
export type WakeCancelParams = { 
/**
 * Its id, or the end of it (`a1b2c3`), as long as one wake matches.
 */
wake: string, 
/**
 * Who asked, as the ledger names them. Default: the surface (`the CLI`,
 * `the web UI`).
 */
author?: string, };
