// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeInfo } from "./WakeInfo";

export type WakeListResult = { wakes: Array<WakeInfo>, };
