// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WakeInfo } from "./WakeInfo";

export type WakeCancelResult = { 
/**
 * The wake as it was before the cancel.
 */
wake: WakeInfo, };
