// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WarmStamp } from "./WarmStamp";

/**
 * Health's `warm` block: what the notices opened, and when.
 */
export type WarmHealth = { 
/**
 * Notices that started a warm-up since the daemon began.
 */
started: number, 
/**
 * Notices dropped: inside a session's idle spell, or from someone the
 * daemon does not warm for.
 */
dropped: number, 
/**
 * The model provider's connection, last warmed.
 */
provider?: WarmStamp, 
/**
 * The index tender's embedding model, last warmed.
 */
tender?: WarmStamp, };
