// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One warm-up: when, what it found, and how long it took.
 */
export type WarmStamp = { 
/**
 * Unix ms when it finished.
 */
at_ms: number, 
/**
 * How long it took, in ms.
 */
took_ms: number, 
/**
 * What it found: `opened` (a connection was made) or `warm` (one was
 * open already) for the provider; the model's state (`loaded`,
 * `loading`, …) for the tender; or `failed: why`.
 */
outcome: string, };
