// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the web UI refused (theseus-70f): a request whose `Host` is not the
 * UI's own loopback address and port (DNS rebinding), a WebSocket upgrade
 * whose `Origin` is not the UI's own page (any other page in the operator's
 * browser), and a connection whose client socket another uid owns (another
 * local user's process, theseus-3qf). Each kind is ledgered as
 * `web.refused`, at most once a minute, with how many refusals the row
 * stands for.
 */
export type WebStatus = { refused_host: number, refused_origin: number, refused_peer: number, 
/**
 * Set where the port cannot check its clients' owner: why (a platform
 * with no table of socket owners, not Linux). Then a local process of
 * any user is served.
 */
peer_unchecked?: string, 
/**
 * `[web] dev_origin`, when set (theseus-zab): the Vite dev page, whose
 * `/ws` upgrades are served beside the UI's own page.
 */
dev_origin?: string, 
/**
 * The `/ws` upgrades served for it, each ledgered as `web.dev_origin`
 * at most once a minute.
 */
dev_origin_served?: number, };
