// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a notice was given: the policy's rule.
 */
export type Why = "asked" | "reminder" | "answered" | "expired" | "failed" | "blocked" | "finished" | "reported" | "spend_crossed" | "woke";
