// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wake whose turn just ended: its note and when it fired.
 */
export type Woke = { note: string, at_ms: number, };
