// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkKind } from "./WorkKind";

/**
 * A reference to a piece of work, as a notice or a question names it.
 */
export type WorkRef = { id: string, kind: WorkKind, session_id?: string, 
/**
 * Empty while unknown.
 */
title: string, };
