// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a piece of work stands. A newer daemon's state reads as `unknown`.
 */
export type WorkState = "queued" | "running" | "waiting" | "needs_you" | "ready" | "done" | "failed" | "cancelled" | "expired" | "unknown";
