// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a piece of work is.
 */
export type WorkKind = "conversation" | "task" | "step" | "job" | "question" | "wake" | "system";
