// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attention } from "./Attention";
import type { Cost } from "./Cost";
import type { Doing } from "./Doing";
import type { Eta } from "./Eta";
import type { Progress } from "./Progress";
import type { Question } from "./Question";
import type { Rollup } from "./Rollup";
import type { Woke } from "./Woke";
import type { WorkKind } from "./WorkKind";
import type { WorkReport } from "./WorkReport";
import type { WorkState } from "./WorkState";

/**
 * One piece of work as every surface shows it.
 */
export type WorkView = { 
/**
 * `exe_…` (a conversation, a task), `act_…` (a job, a question),
 * `wak_…` (a wake), `tsk_…` (a step).
 */
id: string, kind: WorkKind, 
/**
 * The WAL position of the frame this view comes from, and when it was
 * committed: a client applies a view only if its position is greater
 * than the last it applied for the same id (the position rule).
 */
position: number, at_ms: number, 
/**
 * What it is under: the tree.
 */
parent?: string, 
/**
 * The conversation at the top of its tree, or `system`.
 */
root: string, session_id?: string, 
/**
 * The session's or the task's title, a job's command (`cargo test -p
 * core`), a wake's note, or the question. Empty while unknown.
 */
title: string, 
/**
 * The place rule's name for where it lives: `cli`, `web`, `discord dm`.
 */
place?: string, state: WorkState, 
/**
 * The state before this frame; absent for work first seen.
 */
previous?: WorkState, 
/**
 * The same four levels and labels for every kind.
 */
attention: Attention, 
/**
 * When it was opened, dispatched, asked, or set; 0 when the source does
 * not say.
 */
started_at_ms: number, state_since_ms: number, ended_at_ms?: number, 
/**
 * A conversation's or a task's doing now.
 */
doing?: Doing, 
/**
 * Plan steps, and the model's last word.
 */
progress?: Progress, 
/**
 * A question's whole self; on an execution, its open one in brief.
 */
question?: Question, 
/**
 * Spend and limit since the last reset, and this turn's.
 */
cost?: Cost, 
/**
 * A job: the usual time of the same program on this machine.
 */
eta?: Eta, 
/**
 * Its subtree, counted by level.
 */
below?: Rollup, 
/**
 * Why it was queued (`wake`, `report`, `task`, `input`), kept while it
 * is queued.
 */
why?: string, 
/**
 * A task's ending: its report, so a terminal hears it at once rather
 * than at the parent's next turn.
 */
report?: WorkReport, 
/**
 * The wake whose turn just ended: a client says `⏰ ops · the tide
 * turns` even when the level did not change.
 */
woke?: Woke, 
/**
 * The owner asked to hear when it is done ("tell me when it's done").
 */
flagged?: boolean, };
