// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Urgency } from "./Urgency";
import type { Why } from "./Why";
import type { WorkRef } from "./WorkRef";

/**
 * One notice: what changed, for whom, and its one line.
 */
export type WorkNotice = { urgency: Urgency, why: Why, work: WorkRef, root: WorkRef, 
/**
 * `● Beta summary asks: fs.write create notes.txt (40 B)? · expires 18:36`.
 */
line: string, 
/**
 * The question it is about.
 */
question?: string, 
/**
 * The question whose ping this clears, on every surface.
 */
retracts?: string, position: number, at_ms: number, };
