// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task's report, on its ending view: `{"outcome": "failed", "reason":
 * "the provider refused the request (400)"}`.
 */
export type WorkReport = { 
/**
 * `done`, `failed`, `cancelled`; a question's `approved`, `declined`.
 */
outcome: string, first_line?: string, reason?: string, };
